CREATE TABLE `auditLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`userRole` varchar(20),
	`action` varchar(100) NOT NULL,
	`entityType` varchar(50) NOT NULL,
	`entityId` int,
	`oldValues` json,
	`newValues` json,
	`ipAddress` varchar(45),
	`userAgent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `auditLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `batchCustomerPricing` (
	`id` int AUTO_INCREMENT NOT NULL,
	`batchId` int NOT NULL,
	`customerId` int NOT NULL,
	`pricePerKg` decimal(10,2),
	`pricePerCbm` decimal(10,2),
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `batchCustomerPricing_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `batchPricingTiers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`batchId` int NOT NULL,
	`minValue` decimal(10,4) NOT NULL,
	`maxValue` decimal(10,4),
	`pricePerUnit` decimal(10,2) NOT NULL,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `batchPricingTiers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `batches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`batchCode` varchar(50) NOT NULL,
	`originWarehouseId` int NOT NULL,
	`destinationCountryId` int NOT NULL,
	`shippingType` enum('air_regular','air_irregular','sea') NOT NULL,
	`carrierInfo` varchar(255),
	`departureDate` timestamp,
	`estimatedArrival` timestamp,
	`actualArrival` timestamp,
	`status` enum('preparing','in_transit','arrived','customs','delivered','closed') NOT NULL DEFAULT 'preparing',
	`totalPackages` int NOT NULL DEFAULT 0,
	`totalWeight` decimal(10,2),
	`actualWeightKg` decimal(10,2),
	`actualCbm` decimal(10,4),
	`chargedWeightKg` decimal(10,2),
	`chargedCbm` decimal(10,4),
	`costPerKg` decimal(10,2),
	`costPerCbm` decimal(10,2),
	`pricePerKg` decimal(10,2),
	`pricePerCbm` decimal(10,2),
	`useTieredPricing` boolean NOT NULL DEFAULT false,
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `batches_id` PRIMARY KEY(`id`),
	CONSTRAINT `batches_batchCode_unique` UNIQUE(`batchCode`)
);
--> statement-breakpoint
CREATE TABLE `blogPosts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`titleEn` varchar(500) NOT NULL,
	`titleKu` varchar(500),
	`titleAr` varchar(500),
	`contentEn` text NOT NULL,
	`contentKu` text,
	`contentAr` text,
	`summaryEn` text,
	`summaryKu` text,
	`summaryAr` text,
	`coverImageUrl` varchar(500),
	`category` enum('announcement','news','promotion','update','guide') NOT NULL DEFAULT 'announcement',
	`status` enum('draft','published','archived') NOT NULL DEFAULT 'draft',
	`isFeatured` boolean NOT NULL DEFAULT false,
	`publishedAt` timestamp,
	`expiresAt` timestamp,
	`slug` varchar(255),
	`viewCount` int NOT NULL DEFAULT 0,
	`authorId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blogPosts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blogPosts_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `cashAccounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountName` varchar(255) NOT NULL,
	`accountNameKu` varchar(255),
	`accountType` enum('cash','bank','mobile_wallet') NOT NULL,
	`bankName` varchar(255),
	`accountNumber` varchar(100),
	`currency` enum('USD','IQD') NOT NULL DEFAULT 'USD',
	`currentBalance` decimal(14,2) NOT NULL DEFAULT '0',
	`initialBalance` decimal(14,2) NOT NULL DEFAULT '0',
	`description` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`isPrimary` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cashAccounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cashTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`transactionType` enum('deposit','withdrawal','transfer_in','transfer_out','customer_payment','expense','debt_payment','partner_deposit','partner_withdrawal','adjustment') NOT NULL,
	`amount` decimal(14,2) NOT NULL,
	`balanceBefore` decimal(14,2) NOT NULL,
	`balanceAfter` decimal(14,2) NOT NULL,
	`relatedAccountId` int,
	`relatedEntityType` varchar(50),
	`relatedEntityId` int,
	`description` text,
	`transactionDate` timestamp NOT NULL,
	`referenceNumber` varchar(100),
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cashTransactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `companyDebts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`creditorName` varchar(255) NOT NULL,
	`creditorType` enum('personal','bank','supplier','other') NOT NULL,
	`creditorPhone` varchar(20),
	`creditorEmail` varchar(320),
	`principalAmount` decimal(14,2) NOT NULL,
	`currency` enum('USD','IQD') NOT NULL DEFAULT 'USD',
	`principalAmountUsd` decimal(14,2) NOT NULL,
	`interestRate` decimal(5,2) DEFAULT '0',
	`totalInterest` decimal(14,2) DEFAULT '0',
	`totalAmount` decimal(14,2) NOT NULL,
	`paidAmount` decimal(14,2) NOT NULL DEFAULT '0',
	`remainingAmount` decimal(14,2) NOT NULL,
	`startDate` timestamp NOT NULL,
	`dueDate` timestamp,
	`installmentCount` int,
	`installmentAmount` decimal(14,2),
	`status` enum('active','paid','overdue','restructured') NOT NULL DEFAULT 'active',
	`purpose` text,
	`collateral` text,
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `companyDebts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `countries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nameEn` varchar(100) NOT NULL,
	`nameAr` varchar(100),
	`nameKu` varchar(100),
	`nameZh` varchar(100),
	`nameTr` varchar(100),
	`nameFa` varchar(100),
	`isoCode` varchar(3) NOT NULL,
	`defaultCurrency` varchar(3),
	`isActive` boolean NOT NULL DEFAULT true,
	`isOrigin` boolean NOT NULL DEFAULT false,
	`isDestination` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `countries_id` PRIMARY KEY(`id`),
	CONSTRAINT `countries_isoCode_unique` UNIQUE(`isoCode`)
);
--> statement-breakpoint
CREATE TABLE `creditAdjustments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`transactionId` int,
	`adjustmentType` enum('increase_debt','decrease_debt','write_off') NOT NULL,
	`amountUsd` decimal(10,2) DEFAULT '0',
	`amountIqd` decimal(15,0) DEFAULT '0',
	`reason` text NOT NULL,
	`supportingDocument` varchar(500),
	`requestedById` int NOT NULL,
	`approvedById` int,
	`approvalStatus` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`approvalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`approvedAt` timestamp,
	CONSTRAINT `creditAdjustments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customerAccounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`accountNumber` varchar(50) NOT NULL,
	`currentBalanceUsd` decimal(12,2) NOT NULL DEFAULT '0',
	`currentBalanceIqd` decimal(15,0) NOT NULL DEFAULT '0',
	`creditLimitUsd` decimal(10,2) DEFAULT '500',
	`creditLimitIqd` decimal(15,0) DEFAULT '750000',
	`totalDebitUsd` decimal(12,2) NOT NULL DEFAULT '0',
	`totalCreditUsd` decimal(12,2) NOT NULL DEFAULT '0',
	`totalDebitIqd` decimal(15,0) NOT NULL DEFAULT '0',
	`totalCreditIqd` decimal(15,0) NOT NULL DEFAULT '0',
	`accountStatus` enum('active','suspended','blocked') NOT NULL DEFAULT 'active',
	`customerScore` decimal(3,1) DEFAULT '5.0',
	`paymentRating` enum('excellent','good','fair','poor') DEFAULT 'good',
	`lastTransactionAt` timestamp,
	`lastPaymentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customerAccounts_id` PRIMARY KEY(`id`),
	CONSTRAINT `customerAccounts_customerId_unique` UNIQUE(`customerId`),
	CONSTRAINT `customerAccounts_accountNumber_unique` UNIQUE(`accountNumber`)
);
--> statement-breakpoint
CREATE TABLE `customerAddresses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`label` varchar(100) NOT NULL,
	`recipientName` varchar(255) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`country` varchar(100) NOT NULL DEFAULT 'Iraq',
	`city` varchar(100) NOT NULL,
	`district` varchar(100),
	`street` varchar(255),
	`building` varchar(100),
	`floor` varchar(20),
	`apartment` varchar(20),
	`landmark` text,
	`notes` text,
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`isDefault` boolean NOT NULL DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customerAddresses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customerMessages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`conversationId` varchar(50) NOT NULL,
	`customerId` int NOT NULL,
	`message` text NOT NULL,
	`senderType` enum('customer','admin') NOT NULL,
	`senderId` int NOT NULL,
	`isRead` boolean NOT NULL DEFAULT false,
	`readAt` timestamp,
	`attachmentUrl` varchar(500),
	`attachmentType` enum('image','document','other'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `customerMessages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customerNotificationPrefs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`emailEnabled` boolean DEFAULT true,
	`smsEnabled` boolean DEFAULT true,
	`whatsappEnabled` boolean DEFAULT false,
	`packageRegistered` boolean DEFAULT true,
	`packageStatusChange` boolean DEFAULT true,
	`packageDelivered` boolean DEFAULT true,
	`paymentReminder` boolean DEFAULT true,
	`promotions` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customerNotificationPrefs_id` PRIMARY KEY(`id`),
	CONSTRAINT `customerNotificationPrefs_customerId_unique` UNIQUE(`customerId`)
);
--> statement-breakpoint
CREATE TABLE `customerNotifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`titleKu` varchar(255),
	`titleAr` varchar(255),
	`message` text NOT NULL,
	`messageKu` text,
	`messageAr` text,
	`type` enum('info','success','warning','error','package','payment','promotion') NOT NULL DEFAULT 'info',
	`relatedType` enum('package','batch','payment','invoice','full_package'),
	`relatedId` int,
	`actionUrl` varchar(500),
	`actionLabel` varchar(100),
	`isRead` boolean NOT NULL DEFAULT false,
	`readAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `customerNotifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerCode` varchar(100) NOT NULL,
	`sequenceNumber` int NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`fullNameArabic` varchar(255),
	`fullNameKurdish` varchar(255),
	`mobileNumber` varchar(20) NOT NULL,
	`passwordHash` varchar(255) NOT NULL,
	`email` varchar(320),
	`country` varchar(100),
	`city` varchar(100),
	`address` text,
	`goodsTypePreferences` json,
	`shippingTypePreferences` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`notes` text,
	`linkedUserId` int,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customers_id` PRIMARY KEY(`id`),
	CONSTRAINT `customers_customerCode_unique` UNIQUE(`customerCode`),
	CONSTRAINT `customers_sequenceNumber_unique` UNIQUE(`sequenceNumber`),
	CONSTRAINT `customers_mobileNumber_unique` UNIQUE(`mobileNumber`)
);
--> statement-breakpoint
CREATE TABLE `dailyFinancialSummary` (
	`id` int AUTO_INCREMENT NOT NULL,
	`summaryDate` timestamp NOT NULL,
	`totalRevenue` decimal(14,2) NOT NULL DEFAULT '0',
	`packageRevenue` decimal(14,2) DEFAULT '0',
	`fullPackageRevenue` decimal(14,2) DEFAULT '0',
	`serviceRevenue` decimal(14,2) DEFAULT '0',
	`otherRevenue` decimal(14,2) DEFAULT '0',
	`totalExpenses` decimal(14,2) NOT NULL DEFAULT '0',
	`shippingExpenses` decimal(14,2) DEFAULT '0',
	`purchaseExpenses` decimal(14,2) DEFAULT '0',
	`operationalExpenses` decimal(14,2) DEFAULT '0',
	`otherExpenses` decimal(14,2) DEFAULT '0',
	`grossProfit` decimal(14,2) DEFAULT '0',
	`netProfit` decimal(14,2) DEFAULT '0',
	`cashIn` decimal(14,2) DEFAULT '0',
	`cashOut` decimal(14,2) DEFAULT '0',
	`netCashFlow` decimal(14,2) DEFAULT '0',
	`packagesDelivered` int DEFAULT 0,
	`fullPackagesSold` int DEFAULT 0,
	`invoicesIssued` int DEFAULT 0,
	`paymentsReceived` int DEFAULT 0,
	`totalReceivables` decimal(14,2) DEFAULT '0',
	`totalPayables` decimal(14,2) DEFAULT '0',
	`isFinalized` boolean NOT NULL DEFAULT false,
	`finalizedAt` timestamp,
	`finalizedById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dailyFinancialSummary_id` PRIMARY KEY(`id`),
	CONSTRAINT `dailyFinancialSummary_summaryDate_unique` UNIQUE(`summaryDate`)
);
--> statement-breakpoint
CREATE TABLE `debtPayments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`debtId` int NOT NULL,
	`amount` decimal(14,2) NOT NULL,
	`currency` enum('USD','IQD') NOT NULL DEFAULT 'USD',
	`amountUsd` decimal(14,2) NOT NULL,
	`principalPaid` decimal(14,2) NOT NULL,
	`interestPaid` decimal(14,2) DEFAULT '0',
	`paymentDate` timestamp NOT NULL,
	`paymentMethod` enum('cash','bank_transfer','card','other') NOT NULL DEFAULT 'cash',
	`cashAccountId` int,
	`remainingAfter` decimal(14,2),
	`referenceNumber` varchar(100),
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `debtPayments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `exchangeRates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`baseCurrency` varchar(3) NOT NULL DEFAULT 'USD',
	`targetCurrency` varchar(3) NOT NULL,
	`rate` decimal(15,6) NOT NULL,
	`source` varchar(50),
	`isManualOverride` boolean NOT NULL DEFAULT false,
	`effectiveFrom` timestamp NOT NULL DEFAULT (now()),
	`effectiveTo` timestamp,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `exchangeRates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `expenseCategories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nameEn` varchar(100) NOT NULL,
	`nameAr` varchar(100),
	`nameKu` varchar(100),
	`icon` varchar(50),
	`color` varchar(20),
	`description` text,
	`isRecurring` boolean NOT NULL DEFAULT false,
	`sortOrder` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `expenseCategories_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `expenses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`categoryId` int NOT NULL,
	`amount` decimal(12,2) NOT NULL,
	`currency` enum('USD','IQD') NOT NULL DEFAULT 'USD',
	`exchangeRate` decimal(10,4),
	`amountUsd` decimal(12,2) NOT NULL,
	`description` text,
	`expenseDate` timestamp NOT NULL,
	`receiptUrl` varchar(500),
	`paymentMethod` enum('cash','bank_transfer','card','other') NOT NULL DEFAULT 'cash',
	`cashAccountId` int,
	`isRecurring` boolean NOT NULL DEFAULT false,
	`recurringDay` int,
	`vendor` varchar(255),
	`referenceNumber` varchar(100),
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `expenses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `extraServices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`serviceNumber` varchar(50) NOT NULL,
	`serviceTypeId` int NOT NULL,
	`customerId` int,
	`description` text NOT NULL,
	`costAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`priceAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`profitAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`currency` enum('USD','IQD','CNY') NOT NULL DEFAULT 'USD',
	`exchangeRate` decimal(10,2),
	`isPaid` boolean NOT NULL DEFAULT false,
	`paidAt` timestamp,
	`paidAmount` decimal(10,2),
	`paymentMethod` enum('cash','card','transfer','balance'),
	`addedToBalance` boolean NOT NULL DEFAULT false,
	`ledgerTransactionId` int,
	`invoiceId` int,
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `extraServices_id` PRIMARY KEY(`id`),
	CONSTRAINT `extraServices_serviceNumber_unique` UNIQUE(`serviceNumber`)
);
--> statement-breakpoint
CREATE TABLE `financialPeriods` (
	`id` int AUTO_INCREMENT NOT NULL,
	`periodType` enum('monthly','quarterly','yearly') NOT NULL,
	`year` int NOT NULL,
	`month` int,
	`quarter` int,
	`startDate` timestamp NOT NULL,
	`endDate` timestamp NOT NULL,
	`totalRevenue` decimal(14,2) DEFAULT '0',
	`packageRevenue` decimal(14,2) DEFAULT '0',
	`fullPackageRevenue` decimal(14,2) DEFAULT '0',
	`otherRevenue` decimal(14,2) DEFAULT '0',
	`totalExpenses` decimal(14,2) DEFAULT '0',
	`grossProfit` decimal(14,2) DEFAULT '0',
	`netProfit` decimal(14,2) DEFAULT '0',
	`status` enum('open','closed','locked') NOT NULL DEFAULT 'open',
	`closedAt` timestamp,
	`closedById` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financialPeriods_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fullPackageOrders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderCode` varchar(50) NOT NULL,
	`customerId` int NOT NULL,
	`supplierId` int,
	`orderType` enum('resale','purchase') NOT NULL DEFAULT 'resale',
	`productName` varchar(500) NOT NULL,
	`productLink` text,
	`productImage` text,
	`productImages` json,
	`productDescription` text,
	`quantity` int NOT NULL DEFAULT 1,
	`color` varchar(100),
	`size` varchar(100),
	`supplierTrackingNumber` varchar(100),
	`supplierOrderNumber` varchar(100),
	`purchaseInvoiceUrl` text,
	`purchasePriceUsd` decimal(10,2),
	`purchasePriceCny` decimal(10,2),
	`sellingPriceUsd` decimal(10,2),
	`estimatedPriceUsd` decimal(10,2),
	`actualPriceUsd` decimal(10,2),
	`purchaseFeeUsd` decimal(10,2),
	`commissionRate` decimal(5,2),
	`commissionAmount` decimal(10,2),
	`shippingType` enum('air_regular','air_irregular','sea'),
	`weightKg` decimal(10,3),
	`volumeCbm` decimal(10,6),
	`dimensionLength` decimal(10,2),
	`dimensionWidth` decimal(10,2),
	`dimensionHeight` decimal(10,2),
	`shippingCostUsd` decimal(10,2) DEFAULT '0',
	`totalCostUsd` decimal(10,2),
	`profitUsd` decimal(10,2),
	`paidFromBalanceUsd` decimal(10,2) DEFAULT '0',
	`remainingBalanceUsd` decimal(10,2) DEFAULT '0',
	`isPaid` boolean DEFAULT false,
	`orderNumber` varchar(100),
	`trackingNumber` varchar(100),
	`orderDate` timestamp,
	`trackingAddedDate` timestamp,
	`expectedDeliveryDate` timestamp,
	`arrivedDate` timestamp,
	`deliveredDate` timestamp,
	`actualDeliveryDate` timestamp,
	`qualityCheckStatus` enum('pending','passed','failed','partial'),
	`qualityCheckNotes` text,
	`qualityCheckDate` timestamp,
	`qualityCheckById` int,
	`isReturned` boolean DEFAULT false,
	`returnReason` text,
	`returnDate` timestamp,
	`returnStatus` enum('requested','approved','rejected','completed'),
	`refundAmount` decimal(10,2),
	`status` enum('pending','approved','ordered','tracking_added','in_china_warehouse','quality_check','in_batch','in_transit','arrived','ready_for_delivery','delivered','cancelled','refunded','returned') NOT NULL DEFAULT 'pending',
	`batchId` int,
	`packageId` int,
	`priority` enum('low','normal','high','urgent') DEFAULT 'normal',
	`tags` json,
	`trackingReminderSent` boolean DEFAULT false,
	`alertLevel` enum('none','warning','urgent','critical') DEFAULT 'none',
	`lastAlertSentAt` timestamp,
	`alertCount` int DEFAULT 0,
	`customerNotes` text,
	`notes` text,
	`internalNotes` text,
	`createdById` int NOT NULL,
	`assignedToId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fullPackageOrders_id` PRIMARY KEY(`id`),
	CONSTRAINT `fullPackageOrders_orderCode_unique` UNIQUE(`orderCode`)
);
--> statement-breakpoint
CREATE TABLE `fullPackageStatusHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`previousStatus` varchar(50),
	`newStatus` varchar(50) NOT NULL,
	`changedById` int NOT NULL,
	`changedByName` varchar(255),
	`notes` text,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `fullPackageStatusHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoiceTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL DEFAULT 'Default',
	`isDefault` boolean NOT NULL DEFAULT true,
	`style` enum('modern','classic','minimal') NOT NULL DEFAULT 'modern',
	`companyName` varchar(255),
	`companyNameAr` varchar(255),
	`companyNameKu` varchar(255),
	`companyAddress` text,
	`companyAddressAr` text,
	`companyAddressKu` text,
	`companyPhone` varchar(50),
	`companyPhone2` varchar(50),
	`companyEmail` varchar(255),
	`companyWebsite` varchar(255),
	`logoUrl` varchar(500),
	`logoWidth` int DEFAULT 150,
	`logoPosition` enum('left','center','right') DEFAULT 'left',
	`primaryColor` varchar(7) DEFAULT '#3b82f6',
	`secondaryColor` varchar(7) DEFAULT '#10b981',
	`accentColor` varchar(7) DEFAULT '#f59e0b',
	`textColor` varchar(7) DEFAULT '#1f2937',
	`backgroundColor` varchar(7) DEFAULT '#ffffff',
	`fontFamily` varchar(100) DEFAULT 'Arial',
	`fontSize` int DEFAULT 10,
	`bankName` varchar(255),
	`bankAccountName` varchar(255),
	`bankAccountNumber` varchar(100),
	`bankIban` varchar(50),
	`bankSwift` varchar(20),
	`bank2Name` varchar(255),
	`bank2AccountName` varchar(255),
	`bank2AccountNumber` varchar(100),
	`bank2Currency` varchar(10),
	`footerText` text,
	`footerTextAr` text,
	`footerTextKu` text,
	`termsText` text,
	`termsTextAr` text,
	`termsTextKu` text,
	`showQrCode` boolean DEFAULT true,
	`showWatermark` boolean DEFAULT false,
	`watermarkText` varchar(100),
	`invoicePrefix` varchar(20) DEFAULT 'INV',
	`invoiceNumberDigits` int DEFAULT 6,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdById` int,
	CONSTRAINT `invoiceTemplates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceNumber` varchar(50) NOT NULL,
	`customerId` int NOT NULL,
	`packageId` int,
	`batchId` int,
	`subtotalUsd` decimal(12,2) NOT NULL,
	`taxUsd` decimal(12,2) DEFAULT '0',
	`totalUsd` decimal(12,2) NOT NULL,
	`exchangeRateIqd` decimal(12,2),
	`exchangeRateRmb` decimal(12,6),
	`totalIqd` decimal(15,0),
	`totalRmb` decimal(12,2),
	`status` enum('draft','issued','paid','partially_paid','cancelled','refunded') NOT NULL DEFAULT 'draft',
	`issuedAt` timestamp,
	`dueDate` timestamp,
	`paidAt` timestamp,
	`pdfUrl` text,
	`lineItems` json,
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`),
	CONSTRAINT `invoices_invoiceNumber_unique` UNIQUE(`invoiceNumber`)
);
--> statement-breakpoint
CREATE TABLE `labelTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`isDefault` boolean NOT NULL DEFAULT false,
	`size` enum('10x15','10x10','A6','A5','custom') NOT NULL DEFAULT '10x15',
	`widthMm` int DEFAULT 100,
	`heightMm` int DEFAULT 150,
	`showQrCode` boolean NOT NULL DEFAULT true,
	`qrCodeSize` int DEFAULT 80,
	`qrCodePosition` enum('top-left','top-right','bottom-left','bottom-right','center') DEFAULT 'top-right',
	`showBarcode` boolean NOT NULL DEFAULT true,
	`barcodeType` enum('code128','code39','ean13','qr') DEFAULT 'code128',
	`showLogo` boolean NOT NULL DEFAULT true,
	`logoUrl` varchar(500),
	`logoWidth` int DEFAULT 60,
	`showTrackingNumber` boolean NOT NULL DEFAULT true,
	`showCustomerName` boolean NOT NULL DEFAULT true,
	`showCustomerCode` boolean NOT NULL DEFAULT true,
	`showCustomerPhone` boolean NOT NULL DEFAULT true,
	`showDestinationCity` boolean NOT NULL DEFAULT true,
	`showWeight` boolean NOT NULL DEFAULT true,
	`showDimensions` boolean NOT NULL DEFAULT false,
	`showShippingType` boolean NOT NULL DEFAULT true,
	`showBatchNumber` boolean NOT NULL DEFAULT true,
	`showDate` boolean NOT NULL DEFAULT true,
	`showPrice` boolean NOT NULL DEFAULT false,
	`primaryColor` varchar(7) DEFAULT '#000000',
	`fontFamily` varchar(100) DEFAULT 'Arial',
	`fontSize` int DEFAULT 12,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `labelTemplates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ledgerEntries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`entryType` enum('charge','payment','refund','adjustment') NOT NULL,
	`amountUsd` decimal(12,2) NOT NULL,
	`balanceAfterUsd` decimal(12,2) NOT NULL,
	`description` text,
	`referenceType` varchar(50),
	`referenceId` int,
	`packageId` int,
	`invoiceId` int,
	`paymentMethod` varchar(50),
	`exchangeRateUsed` decimal(12,6),
	`originalCurrency` varchar(3),
	`originalAmount` decimal(12,2),
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ledgerEntries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ledgerTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`transactionNumber` varchar(50) NOT NULL,
	`transactionType` enum('DEBIT_PACKAGE','DEBIT_SERVICE','DEBIT_PENALTY','DEBIT_OTHER','CREDIT_PAYMENT','CREDIT_REFUND','CREDIT_DISCOUNT','CREDIT_OTHER','ADJUSTMENT_DEBIT','ADJUSTMENT_CREDIT') NOT NULL,
	`amountUsd` decimal(10,2) DEFAULT '0',
	`amountIqd` decimal(15,0) DEFAULT '0',
	`exchangeRate` decimal(10,2),
	`balanceBeforeUsd` decimal(12,2) NOT NULL,
	`balanceAfterUsd` decimal(12,2) NOT NULL,
	`balanceBeforeIqd` decimal(15,0) NOT NULL,
	`balanceAfterIqd` decimal(15,0) NOT NULL,
	`referenceType` enum('package','payment','adjustment','service','manual'),
	`referenceId` int,
	`description` text,
	`createdById` int NOT NULL,
	`approvedById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ledgerTransactions_id` PRIMARY KEY(`id`),
	CONSTRAINT `ledgerTransactions_transactionNumber_unique` UNIQUE(`transactionNumber`)
);
--> statement-breakpoint
CREATE TABLE `notificationLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int,
	`channel` enum('email','whatsapp','sms') NOT NULL,
	`eventType` varchar(100) NOT NULL,
	`recipient` varchar(255) NOT NULL,
	`subject` varchar(500),
	`content` text,
	`status` enum('pending','sent','failed','delivered') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`sentAt` timestamp,
	`deliveredAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `notificationLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `notificationSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventType` varchar(50) NOT NULL,
	`emailEnabled` boolean NOT NULL DEFAULT false,
	`smsEnabled` boolean NOT NULL DEFAULT false,
	`whatsappEnabled` boolean NOT NULL DEFAULT false,
	`whatsappApiKey` varchar(255),
	`whatsappPhoneNumberId` varchar(50),
	`whatsappTemplateId` varchar(100),
	`customSubject` varchar(255),
	`customBody` text,
	`updatedById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notificationSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `notificationSettings_eventType_unique` UNIQUE(`eventType`)
);
--> statement-breakpoint
CREATE TABLE `notificationTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventType` enum('package_received','package_shipped','package_arrived','package_delivered','payment_received','invoice_created','batch_shipped','batch_arrived','custom') NOT NULL,
	`name` varchar(100) NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`smsTemplate` text,
	`smsTemplateAr` text,
	`smsTemplateKu` text,
	`whatsappTemplate` text,
	`whatsappTemplateAr` text,
	`whatsappTemplateKu` text,
	`emailSubject` varchar(255),
	`emailSubjectAr` varchar(255),
	`emailSubjectKu` varchar(255),
	`emailTemplate` text,
	`emailTemplateAr` text,
	`emailTemplateKu` text,
	`pushTitle` varchar(100),
	`pushTitleAr` varchar(100),
	`pushTitleKu` varchar(100),
	`pushTemplate` text,
	`pushTemplateAr` text,
	`pushTemplateKu` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notificationTemplates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `packageClaimRequests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestNumber` varchar(50) NOT NULL,
	`packageId` int NOT NULL,
	`trackingNumber` varchar(100) NOT NULL,
	`customerId` int NOT NULL,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`customerNote` text,
	`reviewedById` int,
	`reviewedAt` timestamp,
	`adminNote` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `packageClaimRequests_id` PRIMARY KEY(`id`),
	CONSTRAINT `packageClaimRequests_requestNumber_unique` UNIQUE(`requestNumber`)
);
--> statement-breakpoint
CREATE TABLE `packageQrCodes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`packageId` int NOT NULL,
	`packageType` enum('regular','full_package') NOT NULL DEFAULT 'regular',
	`qrCode` varchar(100) NOT NULL,
	`qrImageUrl` text,
	`lastScannedAt` timestamp,
	`lastScannedById` int,
	`scanCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `packageQrCodes_id` PRIMARY KEY(`id`),
	CONSTRAINT `packageQrCodes_qrCode_unique` UNIQUE(`qrCode`)
);
--> statement-breakpoint
CREATE TABLE `packageScans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`packageId` int,
	`trackingNumber` varchar(100) NOT NULL,
	`scanType` enum('registered','received_china','in_batch','in_transit','received_local','out_for_delivery','delivered','returned','customs_hold') NOT NULL,
	`scannedById` int NOT NULL,
	`warehouseId` int,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`locationName` varchar(255),
	`notes` text,
	`photoUrl` varchar(500),
	`deviceId` int,
	`deviceInfo` json,
	`scannedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `packageScans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `packageStatusHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`packageId` int NOT NULL,
	`fromStatus` varchar(50),
	`toStatus` varchar(50) NOT NULL,
	`changedById` int NOT NULL,
	`changeMethod` enum('scan','manual','system','api') NOT NULL DEFAULT 'manual',
	`scanId` int,
	`reason` varchar(255),
	`notes` text,
	`metadata` json,
	`changedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `packageStatusHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `packages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`packageCode` varchar(50) NOT NULL,
	`trackingNumber` varchar(100),
	`customerId` int,
	`originWarehouseId` int NOT NULL,
	`batchId` int,
	`categoryId` int,
	`isUnclaimed` boolean NOT NULL DEFAULT false,
	`claimedAt` timestamp,
	`claimedById` int,
	`qrCodeData` text,
	`qrCodeSignature` varchar(255),
	`weightKg` decimal(10,3),
	`lengthCm` decimal(10,2),
	`widthCm` decimal(10,2),
	`heightCm` decimal(10,2),
	`volumeCbm` decimal(10,6),
	`shippingType` enum('air_regular','air_irregular','sea') NOT NULL,
	`description` text,
	`photos` json,
	`calculatedCostUsd` decimal(10,2),
	`appliedPricingRuleId` int,
	`isCharged` boolean NOT NULL DEFAULT false,
	`deliveryType` enum('air_transit','warehouse_pickup','direct_delivery'),
	`status` enum('registered','in_batch','in_transit','customs_processing','ready_for_delivery','out_for_delivery','delivered','returned','cancelled') NOT NULL DEFAULT 'registered',
	`registeredAt` timestamp NOT NULL DEFAULT (now()),
	`registeredById` int NOT NULL,
	`deliveredAt` timestamp,
	`deliveredById` int,
	`recipientName` varchar(255),
	`recipientSignature` text,
	`deliveryPhoto` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `packages_id` PRIMARY KEY(`id`),
	CONSTRAINT `packages_packageCode_unique` UNIQUE(`packageCode`)
);
--> statement-breakpoint
CREATE TABLE `partnerTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`partnerId` int NOT NULL,
	`transactionType` enum('capital_contribution','profit_share','withdrawal','loan_to_company','loan_repayment','adjustment') NOT NULL,
	`amount` decimal(14,2) NOT NULL,
	`currency` enum('USD','IQD') NOT NULL DEFAULT 'USD',
	`amountUsd` decimal(14,2) NOT NULL,
	`balanceBefore` decimal(14,2) NOT NULL,
	`balanceAfter` decimal(14,2) NOT NULL,
	`description` text,
	`transactionDate` timestamp NOT NULL,
	`periodMonth` int,
	`periodYear` int,
	`cashAccountId` int,
	`referenceNumber` varchar(100),
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `partnerTransactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partners` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`nameKu` varchar(255),
	`email` varchar(320),
	`phone` varchar(20),
	`ownershipPercentage` decimal(5,2) NOT NULL,
	`initialCapital` decimal(14,2) NOT NULL DEFAULT '0',
	`currentBalance` decimal(14,2) NOT NULL DEFAULT '0',
	`joinDate` timestamp NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `partners_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paymentRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`transactionId` int,
	`paymentNumber` varchar(50) NOT NULL,
	`amountUsd` decimal(10,2) DEFAULT '0',
	`amountIqd` decimal(15,0) DEFAULT '0',
	`exchangeRate` decimal(10,2),
	`paymentMethod` enum('CASH','BANK_TRANSFER','FIB','FASTPAY','ZAINCASH','ASIAHAWALA','CARD','OTHER') NOT NULL,
	`paymentStatus` enum('pending','confirmed','cancelled','refunded') NOT NULL DEFAULT 'confirmed',
	`receiptNumber` varchar(100),
	`bankReference` varchar(100),
	`receiptPhoto` varchar(500),
	`notes` text,
	`receivedById` int NOT NULL,
	`confirmedById` int,
	`cancelledById` int,
	`cancelReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`confirmedAt` timestamp,
	`cancelledAt` timestamp,
	CONSTRAINT `paymentRecords_id` PRIMARY KEY(`id`),
	CONSTRAINT `paymentRecords_paymentNumber_unique` UNIQUE(`paymentNumber`)
);
--> statement-breakpoint
CREATE TABLE `paymentReminders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`reminderType` enum('sms','whatsapp','email','call') NOT NULL,
	`messageTemplate` text,
	`customMessage` text,
	`scheduledAt` timestamp NOT NULL,
	`sentAt` timestamp,
	`status` enum('pending','sent','failed','cancelled') NOT NULL DEFAULT 'pending',
	`failureReason` text,
	`customerResponse` text,
	`promisedPaymentDate` timestamp,
	`promisedAmount` decimal(10,2),
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `paymentReminders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`invoiceId` int,
	`amountUsd` decimal(10,2) NOT NULL,
	`amountLocal` decimal(15,2),
	`currency` varchar(3) DEFAULT 'USD',
	`exchangeRate` decimal(10,4),
	`paymentMethod` enum('cash','bank_transfer','mobile_money','card','other') NOT NULL DEFAULT 'cash',
	`referenceNumber` varchar(100),
	`status` enum('pending','completed','failed','refunded') NOT NULL DEFAULT 'completed',
	`notes` text,
	`receivedById` int NOT NULL,
	`paymentDate` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pricingRules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`originCountryId` int NOT NULL,
	`originWarehouseId` int,
	`destinationCountryId` int NOT NULL,
	`shippingType` enum('air_regular','air_irregular','sea') NOT NULL,
	`pricePerUnit` decimal(10,2) NOT NULL,
	`unit` enum('kg','cbm') NOT NULL,
	`effectiveFrom` timestamp NOT NULL,
	`effectiveTo` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pricingRules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `productCategories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nameEn` varchar(100) NOT NULL,
	`nameAr` varchar(100),
	`nameKu` varchar(100),
	`icon` varchar(50),
	`color` varchar(20),
	`sortOrder` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `productCategories_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `revenueRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`recordDate` timestamp NOT NULL,
	`recordNumber` varchar(50) NOT NULL,
	`revenueType` enum('package_delivery','full_package_sale','full_package_commission','service_fee','extra_service','shipping_fee','other') NOT NULL,
	`amountUsd` decimal(12,2) NOT NULL,
	`amountIqd` decimal(15,0),
	`exchangeRate` decimal(10,2),
	`costUsd` decimal(12,2) DEFAULT '0',
	`profitUsd` decimal(12,2) DEFAULT '0',
	`referenceType` enum('package','fullPackageOrder','invoice','service','manual'),
	`referenceId` int,
	`customerId` int,
	`description` text,
	`status` enum('pending','confirmed','cancelled') NOT NULL DEFAULT 'confirmed',
	`createdById` int NOT NULL,
	`confirmedById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `revenueRecords_id` PRIMARY KEY(`id`),
	CONSTRAINT `revenueRecords_recordNumber_unique` UNIQUE(`recordNumber`)
);
--> statement-breakpoint
CREATE TABLE `scanDevices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`deviceName` varchar(100) NOT NULL,
	`deviceType` enum('mobile','scanner','tablet','desktop') NOT NULL DEFAULT 'mobile',
	`deviceIdentifier` varchar(255),
	`assignedToId` int,
	`warehouseId` int,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastActiveAt` timestamp,
	`totalScans` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scanDevices_id` PRIMARY KEY(`id`),
	CONSTRAINT `scanDevices_deviceIdentifier_unique` UNIQUE(`deviceIdentifier`)
);
--> statement-breakpoint
CREATE TABLE `scanHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`packageId` int,
	`fullPackageOrderId` int,
	`trackingNumber` varchar(100) NOT NULL,
	`scanType` enum('register','receive','ship','arrive','deliver','return','other') NOT NULL,
	`status` enum('success','error','not_found') NOT NULL DEFAULT 'success',
	`errorMessage` text,
	`customerName` varchar(255),
	`customerId` int,
	`weightKg` decimal(10,3),
	`shippingType` varchar(50),
	`batchId` int,
	`batchCode` varchar(50),
	`calculatedCost` decimal(10,2),
	`scannedById` int NOT NULL,
	`scannedByName` varchar(255),
	`deviceType` varchar(50),
	`warehouseId` int,
	`scannedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `scanHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scheduledTasksLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`taskName` varchar(100) NOT NULL,
	`taskType` varchar(50) NOT NULL,
	`startedAt` timestamp NOT NULL,
	`completedAt` timestamp,
	`status` enum('running','completed','failed') NOT NULL DEFAULT 'running',
	`itemsProcessed` int DEFAULT 0,
	`itemsSucceeded` int DEFAULT 0,
	`itemsFailed` int DEFAULT 0,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `scheduledTasksLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `serviceTypes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nameEn` varchar(100) NOT NULL,
	`nameKu` varchar(100),
	`nameAr` varchar(100),
	`icon` varchar(50),
	`color` varchar(20),
	`defaultCost` decimal(10,2),
	`defaultPrice` decimal(10,2),
	`requiresCustomer` boolean NOT NULL DEFAULT true,
	`addToCustomerBalance` boolean NOT NULL DEFAULT true,
	`sortOrder` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `serviceTypes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stockCategories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`nameKu` varchar(100),
	`nameAr` varchar(100),
	`slug` varchar(100),
	`description` text,
	`parentId` int,
	`image` varchar(500),
	`sortOrder` int DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `stockCategories_id` PRIMARY KEY(`id`),
	CONSTRAINT `stockCategories_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `stockMovements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productId` int NOT NULL,
	`warehouseId` int,
	`movementType` enum('purchase_in','sale_out','adjustment_in','adjustment_out','transfer_in','transfer_out','return_in','return_out','damage_out') NOT NULL,
	`quantity` int NOT NULL,
	`stockBefore` int NOT NULL,
	`stockAfter` int NOT NULL,
	`unitCost` decimal(10,2),
	`totalCost` decimal(12,2),
	`referenceType` varchar(50),
	`referenceId` int,
	`referenceCode` varchar(50),
	`notes` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stockMovements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stockProducts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sku` varchar(50) NOT NULL,
	`barcode` varchar(100),
	`name` varchar(255) NOT NULL,
	`nameKu` varchar(255),
	`nameAr` varchar(255),
	`nameCn` varchar(255),
	`categoryId` int,
	`description` text,
	`shortDescription` varchar(500),
	`mainImage` varchar(500),
	`images` json,
	`costPrice` decimal(10,2) DEFAULT '0',
	`sellingPrice` decimal(10,2) DEFAULT '0',
	`minSellingPrice` decimal(10,2),
	`unit` varchar(50) DEFAULT 'piece',
	`minStockLevel` int DEFAULT 5,
	`maxStockLevel` int,
	`reorderQuantity` int DEFAULT 10,
	`currentStock` int DEFAULT 0,
	`reservedStock` int DEFAULT 0,
	`availableStock` int DEFAULT 0,
	`trackInventory` boolean NOT NULL DEFAULT true,
	`allowNegativeStock` boolean NOT NULL DEFAULT false,
	`weight` decimal(8,3),
	`length` decimal(8,2),
	`width` decimal(8,2),
	`height` decimal(8,2),
	`isActive` boolean NOT NULL DEFAULT true,
	`isFeatured` boolean NOT NULL DEFAULT false,
	`defaultSupplierId` int,
	`supplierSku` varchar(100),
	`tags` json,
	`notes` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `stockProducts_id` PRIMARY KEY(`id`),
	CONSTRAINT `stockProducts_sku_unique` UNIQUE(`sku`),
	CONSTRAINT `stockProducts_barcode_unique` UNIQUE(`barcode`)
);
--> statement-breakpoint
CREATE TABLE `stockPurchaseItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`purchaseId` int NOT NULL,
	`productId` int NOT NULL,
	`orderedQuantity` int NOT NULL,
	`receivedQuantity` int DEFAULT 0,
	`unitCost` decimal(10,2) NOT NULL,
	`totalCost` decimal(12,2) NOT NULL,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stockPurchaseItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stockPurchases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`purchaseCode` varchar(50) NOT NULL,
	`supplierId` int,
	`supplierName` varchar(255),
	`warehouseId` int,
	`status` enum('draft','ordered','shipped','received','cancelled') NOT NULL DEFAULT 'draft',
	`orderDate` timestamp,
	`expectedDate` timestamp,
	`receivedDate` timestamp,
	`subtotal` decimal(12,2) DEFAULT '0',
	`shippingCost` decimal(10,2) DEFAULT '0',
	`otherCosts` decimal(10,2) DEFAULT '0',
	`discount` decimal(10,2) DEFAULT '0',
	`totalCost` decimal(12,2) DEFAULT '0',
	`currency` varchar(3) DEFAULT 'USD',
	`exchangeRate` decimal(10,4) DEFAULT '1',
	`paymentStatus` enum('unpaid','partial','paid') DEFAULT 'unpaid',
	`paidAmount` decimal(12,2) DEFAULT '0',
	`notes` text,
	`internalNotes` text,
	`createdById` int,
	`receivedById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `stockPurchases_id` PRIMARY KEY(`id`),
	CONSTRAINT `stockPurchases_purchaseCode_unique` UNIQUE(`purchaseCode`)
);
--> statement-breakpoint
CREATE TABLE `stockSaleItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`saleId` int NOT NULL,
	`productId` int NOT NULL,
	`productName` varchar(255),
	`productSku` varchar(50),
	`quantity` int NOT NULL,
	`unitPrice` decimal(10,2) NOT NULL,
	`unitCost` decimal(10,2) NOT NULL,
	`discount` decimal(10,2) DEFAULT '0',
	`totalPrice` decimal(12,2) NOT NULL,
	`totalCost` decimal(12,2) NOT NULL,
	`profit` decimal(12,2) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stockSaleItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stockSales` (
	`id` int AUTO_INCREMENT NOT NULL,
	`saleCode` varchar(50) NOT NULL,
	`saleType` enum('account','cash') NOT NULL DEFAULT 'account',
	`customerId` int,
	`customerName` varchar(255),
	`customerPhone` varchar(20),
	`warehouseId` int,
	`status` enum('draft','confirmed','shipped','delivered','cancelled','returned') NOT NULL DEFAULT 'confirmed',
	`saleDate` timestamp DEFAULT (now()),
	`shippedDate` timestamp,
	`deliveredDate` timestamp,
	`subtotal` decimal(12,2) DEFAULT '0',
	`discount` decimal(10,2) DEFAULT '0',
	`discountPercent` decimal(5,2) DEFAULT '0',
	`shippingCharge` decimal(10,2) DEFAULT '0',
	`totalAmount` decimal(12,2) DEFAULT '0',
	`totalCost` decimal(12,2) DEFAULT '0',
	`profit` decimal(12,2) DEFAULT '0',
	`profitMargin` decimal(5,2) DEFAULT '0',
	`paymentMethod` enum('cash','card','transfer','balance') DEFAULT 'cash',
	`amountReceived` decimal(12,2) DEFAULT '0',
	`changeGiven` decimal(10,2) DEFAULT '0',
	`addedToLedger` boolean DEFAULT false,
	`ledgerTransactionId` int,
	`notes` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `stockSales_id` PRIMARY KEY(`id`),
	CONSTRAINT `stockSales_saleCode_unique` UNIQUE(`saleCode`)
);
--> statement-breakpoint
CREATE TABLE `suppliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`nameArabic` varchar(255),
	`nameChinese` varchar(255),
	`contactPerson` varchar(255),
	`phone` varchar(50),
	`wechatId` varchar(100),
	`email` varchar(320),
	`platform` enum('1688','taobao','alibaba','pinduoduo','other') DEFAULT '1688',
	`platformShopUrl` text,
	`rating` decimal(3,2) DEFAULT '5.00',
	`totalOrders` int DEFAULT 0,
	`totalSpentUsd` decimal(12,2) DEFAULT '0',
	`notes` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `suppliers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `systemSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`settingKey` varchar(100) NOT NULL,
	`settingValue` text,
	`settingType` varchar(20) DEFAULT 'string',
	`description` text,
	`updatedById` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `systemSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `systemSettings_settingKey_unique` UNIQUE(`settingKey`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64),
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin','employee','accountant','customer') NOT NULL DEFAULT 'user',
	`customerCode` varchar(100),
	`sequenceNumber` int,
	`fullName` varchar(255),
	`fullNameArabic` varchar(255),
	`fullNameKurdish` varchar(255),
	`gender` enum('male','female'),
	`nationality` varchar(100),
	`businessType` varchar(100),
	`mobileNumber` varchar(20),
	`secondaryMobile` varchar(20),
	`passwordHash` varchar(255),
	`country` varchar(100),
	`city` varchar(100),
	`district` varchar(100),
	`address` text,
	`passportUrl` varchar(500),
	`nationalIdUrl` varchar(500),
	`contractUrl` varchar(500),
	`goodsTypePreferences` json,
	`shippingTypePreferences` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`notes` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`),
	CONSTRAINT `users_customerCode_unique` UNIQUE(`customerCode`),
	CONSTRAINT `users_sequenceNumber_unique` UNIQUE(`sequenceNumber`),
	CONSTRAINT `users_mobileNumber_unique` UNIQUE(`mobileNumber`)
);
--> statement-breakpoint
CREATE TABLE `vipCustomers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`tier` enum('silver','gold','platinum') NOT NULL DEFAULT 'silver',
	`discountPercent` decimal(5,2) DEFAULT '0',
	`fixedPricePerKgAir` decimal(10,2),
	`fixedPricePerKgSea` decimal(10,2),
	`creditLimitUsd` decimal(10,2) DEFAULT '0',
	`notes` text,
	`validFrom` timestamp NOT NULL DEFAULT (now()),
	`validTo` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vipCustomers_id` PRIMARY KEY(`id`),
	CONSTRAINT `vipCustomers_customerId_unique` UNIQUE(`customerId`)
);
--> statement-breakpoint
CREATE TABLE `warehouses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nameEn` varchar(200) NOT NULL,
	`nameAr` varchar(200),
	`nameKu` varchar(200),
	`nameZh` varchar(200),
	`nameTr` varchar(200),
	`nameFa` varchar(200),
	`countryId` int NOT NULL,
	`city` varchar(100) NOT NULL,
	`addressEn` text,
	`addressAr` text,
	`addressKu` text,
	`warehouseType` enum('air','sea','custom') NOT NULL,
	`codePrefix` varchar(10) NOT NULL,
	`expectedDeliveryMin` int,
	`expectedDeliveryMax` int,
	`pricingModel` enum('per_kg','per_cbm') NOT NULL,
	`contactInfo` text,
	`notes` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `warehouses_id` PRIMARY KEY(`id`)
);
