CREATE TABLE `purchaseRequestStatusHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestId` int NOT NULL,
	`fromStatus` varchar(50),
	`toStatus` varchar(50) NOT NULL,
	`changedById` int,
	`changedByName` varchar(255),
	`changedByRole` varchar(50),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `purchaseRequestStatusHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `purchaseRequests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestCode` varchar(50) NOT NULL,
	`customerId` int NOT NULL,
	`customerName` varchar(255),
	`customerCode` varchar(100),
	`productUrl` varchar(1000),
	`productName` varchar(500),
	`productDescription` text,
	`productImages` json,
	`color` varchar(100),
	`size` varchar(100),
	`quantity` int NOT NULL DEFAULT 1,
	`customerNotes` text,
	`deliveryAddress` text,
	`deliveryCity` varchar(100),
	`deliveryPhone` varchar(20),
	`status` enum('pending','quoted','accepted','rejected','cancelled','payment_pending','paid','purchasing','purchased','in_transit','arrived','delivered','completed') NOT NULL DEFAULT 'pending',
	`productPrice` decimal(10,2),
	`productPriceCurrency` varchar(10) DEFAULT 'USD',
	`shippingCost` decimal(10,2),
	`serviceFee` decimal(10,2),
	`localDeliveryCost` decimal(10,2),
	`totalPrice` decimal(10,2),
	`adminNotes` text,
	`quotedById` int,
	`quotedByName` varchar(255),
	`quotedAt` timestamp,
	`customerResponse` enum('pending','accepted','rejected','negotiating') DEFAULT 'pending',
	`customerResponseAt` timestamp,
	`customerResponseNotes` text,
	`paidFromWallet` boolean DEFAULT false,
	`paymentTransactionId` int,
	`paidAt` timestamp,
	`purchaseOrderNumber` varchar(100),
	`purchaseReceipt` varchar(500),
	`purchasedAt` timestamp,
	`purchasedById` int,
	`trackingNumber` varchar(100),
	`trackingCarrier` varchar(100),
	`estimatedDelivery` timestamp,
	`linkedPackageId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `purchaseRequests_id` PRIMARY KEY(`id`),
	CONSTRAINT `purchaseRequests_requestCode_unique` UNIQUE(`requestCode`)
);
