CREATE TABLE `fullPackageOrders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`productName` varchar(500) NOT NULL,
	`productLink` text,
	`productImage` text,
	`quantity` int NOT NULL DEFAULT 1,
	`purchasePriceUsd` decimal(10,2) NOT NULL,
	`sellingPriceUsd` decimal(10,2) NOT NULL,
	`shippingCostUsd` decimal(10,2) DEFAULT '0',
	`profitUsd` decimal(10,2),
	`orderNumber` varchar(100),
	`trackingNumber` varchar(100),
	`orderDate` timestamp,
	`trackingAddedDate` timestamp,
	`status` enum('pending','ordered','tracking_added','in_china_warehouse','in_batch','in_transit','delivered','cancelled') NOT NULL DEFAULT 'pending',
	`batchId` int,
	`trackingReminderSent` boolean DEFAULT false,
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fullPackageOrders_id` PRIMARY KEY(`id`)
);
