CREATE TABLE `backups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`filename` varchar(255) NOT NULL,
	`fileKey` varchar(500) NOT NULL,
	`fileUrl` varchar(1000) NOT NULL,
	`fileSize` int,
	`backupType` enum('manual','scheduled') NOT NULL,
	`schedule` enum('daily','weekly','monthly'),
	`status` enum('in_progress','completed','failed') NOT NULL DEFAULT 'in_progress',
	`errorMessage` text,
	`databaseName` varchar(255),
	`tablesCount` int,
	`recordsCount` int,
	`createdById` int,
	`createdByName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`expiresAt` timestamp,
	CONSTRAINT `backups_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `errorLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`severity` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`errorType` varchar(100) NOT NULL,
	`errorCode` varchar(50),
	`message` text NOT NULL,
	`stackTrace` text,
	`endpoint` varchar(500),
	`method` varchar(10),
	`requestBody` json,
	`responseBody` json,
	`userId` int,
	`userName` varchar(255),
	`userRole` varchar(50),
	`userAgent` varchar(500),
	`ipAddress` varchar(45),
	`environment` enum('development','staging','production') NOT NULL DEFAULT 'production',
	`isResolved` boolean NOT NULL DEFAULT false,
	`resolvedAt` timestamp,
	`resolvedById` int,
	`resolvedByName` varchar(255),
	`resolutionNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `errorLogs_id` PRIMARY KEY(`id`)
);
