CREATE TABLE `creditAdjustments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`transactionId` int,
	`adjustmentType` enum('increase_debt','decrease_debt','write_off') NOT NULL,
	`amountUsd` decimal(10,2) DEFAULT '0',
	`amountIqd` decimal(15,0) DEFAULT '0',
	`reason` text NOT NULL,
	`supportingDocument` varchar(500),
	`requestedById` int NOT NULL,
	`approvedById` int,
	`approvalStatus` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`approvalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`approvedAt` timestamp,
	CONSTRAINT `creditAdjustments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customerAccounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`accountNumber` varchar(50) NOT NULL,
	`currentBalanceUsd` decimal(12,2) NOT NULL DEFAULT '0',
	`currentBalanceIqd` decimal(15,0) NOT NULL DEFAULT '0',
	`creditLimitUsd` decimal(10,2) DEFAULT '500',
	`creditLimitIqd` decimal(15,0) DEFAULT '750000',
	`totalDebitUsd` decimal(12,2) NOT NULL DEFAULT '0',
	`totalCreditUsd` decimal(12,2) NOT NULL DEFAULT '0',
	`totalDebitIqd` decimal(15,0) NOT NULL DEFAULT '0',
	`totalCreditIqd` decimal(15,0) NOT NULL DEFAULT '0',
	`accountStatus` enum('active','suspended','blocked') NOT NULL DEFAULT 'active',
	`customerScore` decimal(3,1) DEFAULT '5.0',
	`paymentRating` enum('excellent','good','fair','poor') DEFAULT 'good',
	`lastTransactionAt` timestamp,
	`lastPaymentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customerAccounts_id` PRIMARY KEY(`id`),
	CONSTRAINT `customerAccounts_customerId_unique` UNIQUE(`customerId`),
	CONSTRAINT `customerAccounts_accountNumber_unique` UNIQUE(`accountNumber`)
);
--> statement-breakpoint
CREATE TABLE `ledgerTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`transactionNumber` varchar(50) NOT NULL,
	`transactionType` enum('DEBIT_PACKAGE','DEBIT_SERVICE','DEBIT_PENALTY','DEBIT_OTHER','CREDIT_PAYMENT','CREDIT_REFUND','CREDIT_DISCOUNT','CREDIT_OTHER','ADJUSTMENT_DEBIT','ADJUSTMENT_CREDIT') NOT NULL,
	`amountUsd` decimal(10,2) DEFAULT '0',
	`amountIqd` decimal(15,0) DEFAULT '0',
	`exchangeRate` decimal(10,2),
	`balanceBeforeUsd` decimal(12,2) NOT NULL,
	`balanceAfterUsd` decimal(12,2) NOT NULL,
	`balanceBeforeIqd` decimal(15,0) NOT NULL,
	`balanceAfterIqd` decimal(15,0) NOT NULL,
	`referenceType` enum('package','payment','adjustment','service','manual'),
	`referenceId` int,
	`description` text,
	`createdById` int NOT NULL,
	`approvedById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ledgerTransactions_id` PRIMARY KEY(`id`),
	CONSTRAINT `ledgerTransactions_transactionNumber_unique` UNIQUE(`transactionNumber`)
);
--> statement-breakpoint
CREATE TABLE `paymentRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`transactionId` int,
	`paymentNumber` varchar(50) NOT NULL,
	`amountUsd` decimal(10,2) DEFAULT '0',
	`amountIqd` decimal(15,0) DEFAULT '0',
	`exchangeRate` decimal(10,2),
	`paymentMethod` enum('CASH','BANK_TRANSFER','FIB','FASTPAY','ZAINCASH','ASIAHAWALA','CARD','OTHER') NOT NULL,
	`paymentStatus` enum('pending','confirmed','cancelled','refunded') NOT NULL DEFAULT 'confirmed',
	`receiptNumber` varchar(100),
	`bankReference` varchar(100),
	`receiptPhoto` varchar(500),
	`notes` text,
	`receivedById` int NOT NULL,
	`confirmedById` int,
	`cancelledById` int,
	`cancelReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`confirmedAt` timestamp,
	`cancelledAt` timestamp,
	CONSTRAINT `paymentRecords_id` PRIMARY KEY(`id`),
	CONSTRAINT `paymentRecords_paymentNumber_unique` UNIQUE(`paymentNumber`)
);
--> statement-breakpoint
CREATE TABLE `paymentReminders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`reminderType` enum('sms','whatsapp','email','call') NOT NULL,
	`messageTemplate` text,
	`customMessage` text,
	`scheduledAt` timestamp NOT NULL,
	`sentAt` timestamp,
	`status` enum('pending','sent','failed','cancelled') NOT NULL DEFAULT 'pending',
	`failureReason` text,
	`customerResponse` text,
	`promisedPaymentDate` timestamp,
	`promisedAmount` decimal(10,2),
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `paymentReminders_id` PRIMARY KEY(`id`)
);
