CREATE TABLE `cashAccounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountName` varchar(255) NOT NULL,
	`accountNameKu` varchar(255),
	`accountType` enum('cash','bank','mobile_wallet') NOT NULL,
	`bankName` varchar(255),
	`accountNumber` varchar(100),
	`currency` enum('USD','IQD') NOT NULL DEFAULT 'USD',
	`currentBalance` decimal(14,2) NOT NULL DEFAULT '0',
	`initialBalance` decimal(14,2) NOT NULL DEFAULT '0',
	`description` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`isPrimary` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cashAccounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cashTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`transactionType` enum('deposit','withdrawal','transfer_in','transfer_out','customer_payment','expense','debt_payment','partner_deposit','partner_withdrawal','adjustment') NOT NULL,
	`amount` decimal(14,2) NOT NULL,
	`balanceBefore` decimal(14,2) NOT NULL,
	`balanceAfter` decimal(14,2) NOT NULL,
	`relatedAccountId` int,
	`relatedEntityType` varchar(50),
	`relatedEntityId` int,
	`description` text,
	`transactionDate` timestamp NOT NULL,
	`referenceNumber` varchar(100),
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cashTransactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `companyDebts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`creditorName` varchar(255) NOT NULL,
	`creditorType` enum('personal','bank','supplier','other') NOT NULL,
	`creditorPhone` varchar(20),
	`creditorEmail` varchar(320),
	`principalAmount` decimal(14,2) NOT NULL,
	`currency` enum('USD','IQD') NOT NULL DEFAULT 'USD',
	`principalAmountUsd` decimal(14,2) NOT NULL,
	`interestRate` decimal(5,2) DEFAULT '0',
	`totalInterest` decimal(14,2) DEFAULT '0',
	`totalAmount` decimal(14,2) NOT NULL,
	`paidAmount` decimal(14,2) NOT NULL DEFAULT '0',
	`remainingAmount` decimal(14,2) NOT NULL,
	`startDate` timestamp NOT NULL,
	`dueDate` timestamp,
	`installmentCount` int,
	`installmentAmount` decimal(14,2),
	`status` enum('active','paid','overdue','restructured') NOT NULL DEFAULT 'active',
	`purpose` text,
	`collateral` text,
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `companyDebts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `debtPayments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`debtId` int NOT NULL,
	`amount` decimal(14,2) NOT NULL,
	`currency` enum('USD','IQD') NOT NULL DEFAULT 'USD',
	`amountUsd` decimal(14,2) NOT NULL,
	`principalPaid` decimal(14,2) NOT NULL,
	`interestPaid` decimal(14,2) DEFAULT '0',
	`paymentDate` timestamp NOT NULL,
	`paymentMethod` enum('cash','bank_transfer','card','other') NOT NULL DEFAULT 'cash',
	`cashAccountId` int,
	`remainingAfter` decimal(14,2) NOT NULL,
	`referenceNumber` varchar(100),
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `debtPayments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `expenseCategories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nameEn` varchar(100) NOT NULL,
	`nameAr` varchar(100),
	`nameKu` varchar(100),
	`icon` varchar(50),
	`color` varchar(20),
	`description` text,
	`isRecurring` boolean NOT NULL DEFAULT false,
	`sortOrder` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `expenseCategories_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `expenses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`categoryId` int NOT NULL,
	`amount` decimal(12,2) NOT NULL,
	`currency` enum('USD','IQD') NOT NULL DEFAULT 'USD',
	`exchangeRate` decimal(10,4),
	`amountUsd` decimal(12,2) NOT NULL,
	`description` text,
	`expenseDate` timestamp NOT NULL,
	`receiptUrl` varchar(500),
	`paymentMethod` enum('cash','bank_transfer','card','other') NOT NULL DEFAULT 'cash',
	`cashAccountId` int,
	`isRecurring` boolean NOT NULL DEFAULT false,
	`recurringDay` int,
	`vendor` varchar(255),
	`referenceNumber` varchar(100),
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `expenses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `financialPeriods` (
	`id` int AUTO_INCREMENT NOT NULL,
	`periodType` enum('monthly','quarterly','yearly') NOT NULL,
	`year` int NOT NULL,
	`month` int,
	`quarter` int,
	`startDate` timestamp NOT NULL,
	`endDate` timestamp NOT NULL,
	`totalRevenue` decimal(14,2) DEFAULT '0',
	`packageRevenue` decimal(14,2) DEFAULT '0',
	`fullPackageRevenue` decimal(14,2) DEFAULT '0',
	`otherRevenue` decimal(14,2) DEFAULT '0',
	`totalExpenses` decimal(14,2) DEFAULT '0',
	`grossProfit` decimal(14,2) DEFAULT '0',
	`netProfit` decimal(14,2) DEFAULT '0',
	`status` enum('open','closed','locked') NOT NULL DEFAULT 'open',
	`closedAt` timestamp,
	`closedById` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financialPeriods_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partnerTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`partnerId` int NOT NULL,
	`transactionType` enum('capital_contribution','profit_share','withdrawal','loan_to_company','loan_repayment','adjustment') NOT NULL,
	`amount` decimal(14,2) NOT NULL,
	`currency` enum('USD','IQD') NOT NULL DEFAULT 'USD',
	`amountUsd` decimal(14,2) NOT NULL,
	`balanceBefore` decimal(14,2) NOT NULL,
	`balanceAfter` decimal(14,2) NOT NULL,
	`description` text,
	`transactionDate` timestamp NOT NULL,
	`periodMonth` int,
	`periodYear` int,
	`cashAccountId` int,
	`referenceNumber` varchar(100),
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `partnerTransactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partners` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`nameKu` varchar(255),
	`email` varchar(320),
	`phone` varchar(20),
	`ownershipPercentage` decimal(5,2) NOT NULL,
	`initialCapital` decimal(14,2) NOT NULL DEFAULT '0',
	`currentBalance` decimal(14,2) NOT NULL DEFAULT '0',
	`joinDate` timestamp NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `partners_id` PRIMARY KEY(`id`)
);
