CREATE TABLE `extraServices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`serviceNumber` varchar(50) NOT NULL,
	`serviceTypeId` int NOT NULL,
	`customerId` int,
	`description` text NOT NULL,
	`costAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`priceAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`profitAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`currency` enum('USD','IQD','CNY') NOT NULL DEFAULT 'USD',
	`exchangeRate` decimal(10,2),
	`isPaid` boolean NOT NULL DEFAULT false,
	`paidAt` timestamp,
	`paidAmount` decimal(10,2),
	`paymentMethod` enum('cash','card','transfer','balance'),
	`addedToBalance` boolean NOT NULL DEFAULT false,
	`ledgerTransactionId` int,
	`invoiceId` int,
	`notes` text,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `extraServices_id` PRIMARY KEY(`id`),
	CONSTRAINT `extraServices_serviceNumber_unique` UNIQUE(`serviceNumber`)
);
--> statement-breakpoint
CREATE TABLE `serviceTypes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nameEn` varchar(100) NOT NULL,
	`nameKu` varchar(100),
	`nameAr` varchar(100),
	`icon` varchar(50),
	`color` varchar(20),
	`defaultCost` decimal(10,2),
	`defaultPrice` decimal(10,2),
	`requiresCustomer` boolean NOT NULL DEFAULT true,
	`addToCustomerBalance` boolean NOT NULL DEFAULT true,
	`sortOrder` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `serviceTypes_id` PRIMARY KEY(`id`)
);
