CREATE TABLE `invoiceTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL DEFAULT 'Default',
	`isDefault` boolean NOT NULL DEFAULT true,
	`style` enum('modern','classic','minimal') NOT NULL DEFAULT 'modern',
	`companyName` varchar(255),
	`companyNameAr` varchar(255),
	`companyNameKu` varchar(255),
	`companyAddress` text,
	`companyAddressAr` text,
	`companyAddressKu` text,
	`companyPhone` varchar(50),
	`companyPhone2` varchar(50),
	`companyEmail` varchar(255),
	`companyWebsite` varchar(255),
	`logoUrl` varchar(500),
	`logoWidth` int DEFAULT 150,
	`logoPosition` enum('left','center','right') DEFAULT 'left',
	`primaryColor` varchar(7) DEFAULT '#3b82f6',
	`secondaryColor` varchar(7) DEFAULT '#10b981',
	`accentColor` varchar(7) DEFAULT '#f59e0b',
	`textColor` varchar(7) DEFAULT '#1f2937',
	`backgroundColor` varchar(7) DEFAULT '#ffffff',
	`fontFamily` varchar(100) DEFAULT 'Arial',
	`fontSize` int DEFAULT 10,
	`bankName` varchar(255),
	`bankAccountName` varchar(255),
	`bankAccountNumber` varchar(100),
	`bankIban` varchar(50),
	`bankSwift` varchar(20),
	`bank2Name` varchar(255),
	`bank2AccountName` varchar(255),
	`bank2AccountNumber` varchar(100),
	`bank2Currency` varchar(10),
	`footerText` text,
	`footerTextAr` text,
	`footerTextKu` text,
	`termsText` text,
	`termsTextAr` text,
	`termsTextKu` text,
	`showQrCode` boolean DEFAULT true,
	`showWatermark` boolean DEFAULT false,
	`watermarkText` varchar(100),
	`invoicePrefix` varchar(20) DEFAULT 'INV',
	`invoiceNumberDigits` int DEFAULT 6,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdById` int,
	CONSTRAINT `invoiceTemplates_id` PRIMARY KEY(`id`)
);
