CREATE TABLE `labelTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`isDefault` boolean NOT NULL DEFAULT false,
	`size` enum('10x15','10x10','A6','A5','custom') NOT NULL DEFAULT '10x15',
	`widthMm` int DEFAULT 100,
	`heightMm` int DEFAULT 150,
	`showQrCode` boolean NOT NULL DEFAULT true,
	`qrCodeSize` int DEFAULT 80,
	`qrCodePosition` enum('top-left','top-right','bottom-left','bottom-right','center') DEFAULT 'top-right',
	`showBarcode` boolean NOT NULL DEFAULT true,
	`barcodeType` enum('code128','code39','ean13','qr') DEFAULT 'code128',
	`showLogo` boolean NOT NULL DEFAULT true,
	`logoUrl` varchar(500),
	`logoWidth` int DEFAULT 60,
	`showTrackingNumber` boolean NOT NULL DEFAULT true,
	`showCustomerName` boolean NOT NULL DEFAULT true,
	`showCustomerCode` boolean NOT NULL DEFAULT true,
	`showCustomerPhone` boolean NOT NULL DEFAULT true,
	`showDestinationCity` boolean NOT NULL DEFAULT true,
	`showWeight` boolean NOT NULL DEFAULT true,
	`showDimensions` boolean NOT NULL DEFAULT false,
	`showShippingType` boolean NOT NULL DEFAULT true,
	`showBatchNumber` boolean NOT NULL DEFAULT true,
	`showDate` boolean NOT NULL DEFAULT true,
	`showPrice` boolean NOT NULL DEFAULT false,
	`primaryColor` varchar(7) DEFAULT '#000000',
	`fontFamily` varchar(100) DEFAULT 'Arial',
	`fontSize` int DEFAULT 12,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `labelTemplates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `notificationTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventType` enum('package_received','package_shipped','package_arrived','package_delivered','payment_received','invoice_created','batch_shipped','batch_arrived','custom') NOT NULL,
	`name` varchar(100) NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`smsTemplate` text,
	`smsTemplateAr` text,
	`smsTemplateKu` text,
	`whatsappTemplate` text,
	`whatsappTemplateAr` text,
	`whatsappTemplateKu` text,
	`emailSubject` varchar(255),
	`emailSubjectAr` varchar(255),
	`emailSubjectKu` varchar(255),
	`emailTemplate` text,
	`emailTemplateAr` text,
	`emailTemplateKu` text,
	`pushTitle` varchar(100),
	`pushTitleAr` varchar(100),
	`pushTitleKu` varchar(100),
	`pushTemplate` text,
	`pushTemplateAr` text,
	`pushTemplateKu` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notificationTemplates_id` PRIMARY KEY(`id`)
);
