CREATE TABLE `dailyFinancialSummary` (
	`id` int AUTO_INCREMENT NOT NULL,
	`summaryDate` timestamp NOT NULL,
	`totalRevenue` decimal(14,2) NOT NULL DEFAULT '0',
	`packageRevenue` decimal(14,2) DEFAULT '0',
	`fullPackageRevenue` decimal(14,2) DEFAULT '0',
	`serviceRevenue` decimal(14,2) DEFAULT '0',
	`otherRevenue` decimal(14,2) DEFAULT '0',
	`totalExpenses` decimal(14,2) NOT NULL DEFAULT '0',
	`shippingExpenses` decimal(14,2) DEFAULT '0',
	`purchaseExpenses` decimal(14,2) DEFAULT '0',
	`operationalExpenses` decimal(14,2) DEFAULT '0',
	`otherExpenses` decimal(14,2) DEFAULT '0',
	`grossProfit` decimal(14,2) DEFAULT '0',
	`netProfit` decimal(14,2) DEFAULT '0',
	`cashIn` decimal(14,2) DEFAULT '0',
	`cashOut` decimal(14,2) DEFAULT '0',
	`netCashFlow` decimal(14,2) DEFAULT '0',
	`packagesDelivered` int DEFAULT 0,
	`fullPackagesSold` int DEFAULT 0,
	`invoicesIssued` int DEFAULT 0,
	`paymentsReceived` int DEFAULT 0,
	`totalReceivables` decimal(14,2) DEFAULT '0',
	`totalPayables` decimal(14,2) DEFAULT '0',
	`isFinalized` boolean NOT NULL DEFAULT false,
	`finalizedAt` timestamp,
	`finalizedById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dailyFinancialSummary_id` PRIMARY KEY(`id`),
	CONSTRAINT `dailyFinancialSummary_summaryDate_unique` UNIQUE(`summaryDate`)
);
--> statement-breakpoint
CREATE TABLE `revenueRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`recordDate` timestamp NOT NULL,
	`recordNumber` varchar(50) NOT NULL,
	`revenueType` enum('package_delivery','full_package_sale','full_package_commission','service_fee','extra_service','shipping_fee','other') NOT NULL,
	`amountUsd` decimal(12,2) NOT NULL,
	`amountIqd` decimal(15,0),
	`exchangeRate` decimal(10,2),
	`costUsd` decimal(12,2) DEFAULT '0',
	`profitUsd` decimal(12,2) DEFAULT '0',
	`referenceType` enum('package','fullPackageOrder','invoice','service','manual'),
	`referenceId` int,
	`customerId` int,
	`description` text,
	`status` enum('pending','confirmed','cancelled') NOT NULL DEFAULT 'confirmed',
	`createdById` int NOT NULL,
	`confirmedById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `revenueRecords_id` PRIMARY KEY(`id`),
	CONSTRAINT `revenueRecords_recordNumber_unique` UNIQUE(`recordNumber`)
);
