import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar" | "ku" | "zh" | "tr" | "fa";

const RTL_LANGUAGES: Language[] = ["ar", "ku", "fa"];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    customers: "Customers",
    packages: "Packages",
    batches: "Batches",
    warehouses: "Warehouses",
    countries: "Countries",
    pricing: "Pricing",
    accounting: "Accounting",
    invoices: "Invoices",
    reports: "Reports",
    users: "Users",
    settings: "Settings",
    auditLogs: "Audit Logs",
    dataManagement: "Data Management",
    operations: "Operations",
    finance: "Finance",
    configuration: "Configuration",
    administration: "Administration",
    scanner: "Scanner",
    smartScanner: "Smart Scanner",
    continuousScan: "Continuous Scan",
    fullPackage: "Full Package",
    customerLedger: "Customer Ledger",
    payments: "Payments",
    vipCustomers: "VIP Customers",
    warehouseOperations: "Warehouse Operations",
    scanDashboard: "Scan Dashboard",
    scanReports: "Scan Reports",
    customerPricing: "Customer Pricing",
    
    // Actions
    create: "Create",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    search: "Search",
    filter: "Filter",
    export: "Export",
    
    // Status
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    delivered: "Delivered",
    inTransit: "In Transit",
    
    // Common
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    status: "Status",
    date: "Date",
    amount: "Amount",
    balance: "Balance",
    total: "Total",
    
    // Logistics specific
    trackingNumber: "Tracking Number",
    weight: "Weight",
    dimensions: "Dimensions",
    shippingType: "Shipping Type",
    airRegular: "Air Regular",
    airIrregular: "Air Irregular",
    sea: "Sea",
    customerCode: "Customer Code",
    packageCode: "Package Code",
    batchCode: "Batch Code",
    warehouse: "Warehouse",
    origin: "Origin",
    destination: "Destination",
    
    // Auth
    signIn: "Sign In",
    signOut: "Sign Out",
    welcome: "Welcome",
    // Customer Portal
    home: "Home",
    shipments: "Shipments",
    financial: "Financial",
    me: "Me",
    trackPackage: "Track Package",
    enterTrackingNumber: "Enter tracking number...",
    searching: "Searching...",
    packageNotFound: "Package not found",
    checkTrackingNumber: "Please check the tracking number and try again",
    enterTrackingToSearch: "Enter a tracking number to search",
    welcomeBack: "Welcome back",
    totalBatches: "Total Batches",
    recentShipments: "Recent Shipments",
    noShipments: "No shipments yet",
    announcements: "Announcements",
    welcomeToWazn: "Welcome to Wazn Express!",
    trackPackagesEasily: "Track your packages easily through this portal.",
    yourPackages: "Your Packages",
    pendingPackages: "Pending Packages",
    packagesWaitingBatch: "packages waiting to be batched",
    noShipmentsFound: "No shipments found",
    tryDifferentFilter: "Try a different filter",
    trackYourPackages: "Track your packages",
    customerBalance: "Customer Balance",
    youOwe: "You owe",
    creditBalance: "Credit balance",
    creditLimit: "Credit Limit",
    totalPaid: "Total Paid",
    transactionList: "Transaction List",
    allTime: "All Time",
    thisMonth: "This Month",
    thisYear: "This Year",
    noTransactions: "No transactions found",
    deliveryCharge: "Delivery Charge",
    messageCenter: "Message Center",
    addresses: "Addresses",
    termsConditions: "Terms & Conditions",
    ourServices: "Our Services",
    withoutShippingMark: "Without Shipping Mark",
    accountSettings: "Account Settings",
    security: "Security",
    estimatedArrival: "Est. Arrival",
    viewAll: "View All",
    back: "Back",
    preparing: "Preparing",
    arrived: "Arrived",
    customs: "Customs",
    closed: "Closed",
    all: "All",
    logout: "Logout",
    notifications: "Notifications",
    payment: "Payment",
    registered: "Registered",
    inBatch: "In Batch",
    customsProcessing: "Customs Processing",
    readyForDelivery: "Ready for Delivery",
    outForDelivery: "Out for Delivery",
    noPackages: "No packages",
    yourAccountBalance: "Your account balance",
    // Unclaimed Packages
    unclaimedPackages: "Unclaimed Packages",
    findYourPackage: "Find your package among unclaimed shipments",
    searchByTrackingNumber: "Search by tracking number...",
    availablePackages: "Available Packages",
    myRequests: "My Requests",
    claimThisPackage: "Claim This Package",
    claimPackage: "Claim Package",
    claimPackageDesc: "Submit a claim request for this package",
    addNote: "Add a note (optional)",
    claimNotePlaceholder: "Explain why this package belongs to you...",
    submitClaim: "Submit Claim",
    noClaimRequests: "No claim requests",
    claimRequestsWillAppearHere: "Your claim requests will appear here",
    claimSubmitted: "Claim Submitted",
    claimSubmittedDesc: "Your claim request has been submitted and is pending review",
    approved: "Approved",
    rejected: "Rejected",
  },
  ar: {
    dashboard: "لوحة التحكم",
    customers: "العملاء",
    packages: "الطرود",
    batches: "الدفعات",
    warehouses: "المستودعات",
    countries: "الدول",
    pricing: "التسعير",
    accounting: "المحاسبة",
    invoices: "الفواتير",
    reports: "التقارير",
    users: "المستخدمين",
    settings: "الإعدادات",
    auditLogs: "سجلات التدقيق",
    dataManagement: "إدارة البيانات",
    create: "إنشاء",
    edit: "تعديل",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    search: "بحث",
    filter: "تصفية",
    export: "تصدير",
    active: "نشط",
    inactive: "غير نشط",
    pending: "قيد الانتظار",
    delivered: "تم التسليم",
    inTransit: "في الطريق",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    address: "العنوان",
    status: "الحالة",
    date: "التاريخ",
    amount: "المبلغ",
    balance: "الرصيد",
    total: "المجموع",
    trackingNumber: "رقم التتبع",
    weight: "الوزن",
    dimensions: "الأبعاد",
    shippingType: "نوع الشحن",
    airRegular: "جوي عادي",
    airIrregular: "جوي غير منتظم",
    sea: "بحري",
    customerCode: "رمز العميل",
    packageCode: "رمز الطرد",
    batchCode: "رمز الدفعة",
    warehouse: "المستودع",
    origin: "المصدر",
    destination: "الوجهة",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    welcome: "مرحباً",
  },
  ku: {
    dashboard: "داشبۆرد",
    customers: "کڕیارەکان",
    packages: "پاکەتەکان",
    batches: "کۆمەڵەکان",
    warehouses: "کۆگاکان",
    countries: "وڵاتەکان",
    pricing: "نرخدانان",
    accounting: "ژمێریاری",
    invoices: "پسوڵەکان",
    reports: "ڕاپۆرتەکان",
    users: "بەکارهێنەرەکان",
    settings: "ڕێکخستنەکان",
    auditLogs: "تۆماری پشکنین",
    dataManagement: "بەڕێوەبردنی داتا",
    operations: "کارەکان",
    finance: "دارایی",
    configuration: "ڕێکخستن",
    administration: "بەڕێوەبردن",
    scanner: "سکانەر",
    smartScanner: "سکانەری هەمەکارە",
    continuousScan: "سکانی بەردەوام",
    fullPackage: "پاکەتی تەواو",
    customerLedger: "حسابی کڕیار",
    payments: "پارەدانەکان",
    vipCustomers: "کڕیارە تایبەتەکان",
    warehouseOperations: "کارەکانی کۆگا",
    scanDashboard: "داشبۆردی سکان",
    scanReports: "ڕاپۆرتی سکان",
    customerPricing: "نرخی تایبەت بۆ کڕیار",
    create: "دروستکردن",
    edit: "دەستکاری",
    delete: "سڕینەوە",
    save: "پاشەکەوت",
    cancel: "هەڵوەشاندنەوە",
    search: "گەڕان",
    filter: "فلتەر",
    export: "هەناردن",
    active: "چالاک",
    inactive: "ناچالاک",
    pending: "چاوەڕوان",
    delivered: "گەیشت",
    inTransit: "لە ڕێگادا",
    name: "ناو",
    email: "ئیمەیڵ",
    phone: "تەلەفۆن",
    address: "ناونیشان",
    status: "دۆخ",
    date: "بەروار",
    amount: "بڕ",
    balance: "باڵانس",
    total: "کۆی گشتی",
    trackingNumber: "ژمارەی شوێنکەوتن",
    weight: "کێش",
    dimensions: "قەبارە",
    shippingType: "جۆری ناردن",
    airRegular: "ئاسمانی ئاسایی",
    airIrregular: "ئاسمانی نائاسایی",
    sea: "دەریایی",
    customerCode: "کۆدی کڕیار",
    packageCode: "کۆدی پاکەت",
    batchCode: "کۆدی کۆمەڵە",
    warehouse: "کۆگا",
    origin: "سەرچاوە",
    destination: "مەبەست",
    signIn: "چوونەژوورەوە",
    signOut: "چوونەدەرەوە",
    welcome: "بەخێربێیت",
    // Customer Portal
    home: "سەرەتا",
    shipments: "گواستنەوەکان",
    financial: "دارایی",
    me: "من",
    trackPackage: "شوێنکەوتنی پاکەت",
    enterTrackingNumber: "ژمارەی شوێنکەوتن بنووسە...",
    searching: "گەڕان...",
    packageNotFound: "پاکەت نەدۆزرایەوە",
    checkTrackingNumber: "تکایە ژمارەی شوێنکەوتن بپشکنە و دووبارە هەوڵ بدەرەوە",
    enterTrackingToSearch: "ژمارەی شوێنکەوتن بنووسە بۆ گەڕان",
    welcomeBack: "بەخێربێیتەوە",
    totalBatches: "کۆی باچەکان",
    recentShipments: "گواستنەوە نوێیەکان",
    noShipments: "هیچ گواستنەوەیەک نییە",
    announcements: "ڕاگەیاندنەکان",
    welcomeToWazn: "بەخێربێیت بۆ وەزن ئێکسپرێس!",
    trackPackagesEasily: "پاکەتەکانت بە ئاسانی شوێن بکەوە لەم پۆرتاڵەوە.",
    yourPackages: "پاکەتەکانت",
    pendingPackages: "پاکەتە چاوەڕوانەکان",
    packagesWaitingBatch: "پاکەت چاوەڕوانی باچن",
    noShipmentsFound: "هیچ گواستنەوەیەک نەدۆزرایەوە",
    tryDifferentFilter: "فلتەرێکی جیاواز تاقی بکەرەوە",
    trackYourPackages: "پاکەتەکانت شوێن بکەوە",
    customerBalance: "باڵانسی کڕیار",
    youOwe: "قەرزت هەیە",
    creditBalance: "باڵانسی کرێدیت",
    creditLimit: "سنووری کرێدیت",
    totalPaid: "کۆی پارەدراو",
    transactionList: "لیستی مامەڵەکان",
    allTime: "هەموو کات",
    thisMonth: "ئەم مانگە",
    thisYear: "ئەم ساڵە",
    noTransactions: "هیچ مامەڵەیەک نەدۆزرایەوە",
    deliveryCharge: "کرێی گەیاندن",
    messageCenter: "ناوەندی پەیام",
    addresses: "ناونیشانەکان",
    termsConditions: "مەرج و مەرجەکان",
    ourServices: "خزمەتگوزارییەکانمان",
    withoutShippingMark: "بێ نیشانەی ناردن",
    accountSettings: "ڕێکخستنەکانی هەژمار",
    security: "پاراستن",
    estimatedArrival: "کاتی گەیشتنی خەمڵێنراو",
    viewAll: "هەموو ببینە",
    back: "گەڕانەوە",
    preparing: "ئامادەکردن",
    arrived: "گەیشتووە",
    customs: "گومرگ",
    closed: "داخراو",
    all: "هەموو",
    logout: "چوونەدەرەوە",
    notifications: "ئاگادارییەکان",
    payment: "پارەدان",
    registered: "تۆمارکراو",
    inBatch: "لە باچدا",
    customsProcessing: "لە گومرگ",
    readyForDelivery: "ئامادەی گەیاندن",
    outForDelivery: "لە ڕێگای گەیاندن",
    noPackages: "هیچ پاکەتێک نییە",
    yourAccountBalance: "باڵانسی هەژمارەکەت",
    // Unclaimed Packages
    unclaimedPackages: "بارە بێ خاوەنەکان",
    findYourPackage: "بارەکەت بدۆزەرەوە لەناو بارە بێ خاوەنەکان",
    searchByTrackingNumber: "بە ژمارەی شوێنکەوتن بگەڕێ...",
    availablePackages: "بارە بەردەستەکان",
    myRequests: "داواکارییەکانم",
    claimThisPackage: "داوای ئەم بارە بکە",
    claimPackage: "داواکردنی بار",
    claimPackageDesc: "داواکاری بنێرە بۆ ئەم بارە",
    addNote: "تێبینی زیاد بکە (ئارەزوومەندانە)",
    claimNotePlaceholder: "ڕوونی بکەرەوە بۆچی ئەم بارە هی تۆیە...",
    submitClaim: "داواکاری بنێرە",
    noClaimRequests: "هیچ داواکارییەک نییە",
    claimRequestsWillAppearHere: "داواکارییەکانت لێرە دەردەکەون",
    claimSubmitted: "داواکاری نێردرا",
    claimSubmittedDesc: "داواکارییەکەت نێردرا و چاوەڕوانی پشکنینە",
    approved: "پەسەندکرا",
    rejected: "ڕەتکرایەوە",
  },
  zh: {
    dashboard: "仪表板",
    customers: "客户",
    packages: "包裹",
    batches: "批次",
    warehouses: "仓库",
    countries: "国家",
    pricing: "定价",
    accounting: "会计",
    invoices: "发票",
    reports: "报告",
    users: "用户",
    settings: "设置",
    auditLogs: "审计日志",
    dataManagement: "数据管理",
    create: "创建",
    edit: "编辑",
    delete: "删除",
    save: "保存",
    cancel: "取消",
    search: "搜索",
    filter: "筛选",
    export: "导出",
    active: "活跃",
    inactive: "非活跃",
    pending: "待处理",
    delivered: "已送达",
    inTransit: "运输中",
    name: "名称",
    email: "邮箱",
    phone: "电话",
    address: "地址",
    status: "状态",
    date: "日期",
    amount: "金额",
    balance: "余额",
    total: "总计",
    trackingNumber: "追踪号",
    weight: "重量",
    dimensions: "尺寸",
    shippingType: "运输类型",
    airRegular: "普通空运",
    airIrregular: "非常规空运",
    sea: "海运",
    customerCode: "客户代码",
    packageCode: "包裹代码",
    batchCode: "批次代码",
    warehouse: "仓库",
    origin: "起点",
    destination: "目的地",
    signIn: "登录",
    signOut: "登出",
    welcome: "欢迎",
  },
  tr: {
    dashboard: "Gösterge Paneli",
    customers: "Müşteriler",
    packages: "Paketler",
    batches: "Partiler",
    warehouses: "Depolar",
    countries: "Ülkeler",
    pricing: "Fiyatlandırma",
    accounting: "Muhasebe",
    invoices: "Faturalar",
    reports: "Raporlar",
    users: "Kullanıcılar",
    settings: "Ayarlar",
    auditLogs: "Denetim Günlükleri",
    dataManagement: "Veri Yönetimi",
    create: "Oluştur",
    edit: "Düzenle",
    delete: "Sil",
    save: "Kaydet",
    cancel: "İptal",
    search: "Ara",
    filter: "Filtrele",
    export: "Dışa Aktar",
    active: "Aktif",
    inactive: "Pasif",
    pending: "Beklemede",
    delivered: "Teslim Edildi",
    inTransit: "Yolda",
    name: "Ad",
    email: "E-posta",
    phone: "Telefon",
    address: "Adres",
    status: "Durum",
    date: "Tarih",
    amount: "Miktar",
    balance: "Bakiye",
    total: "Toplam",
    trackingNumber: "Takip Numarası",
    weight: "Ağırlık",
    dimensions: "Boyutlar",
    shippingType: "Gönderim Türü",
    airRegular: "Normal Hava",
    airIrregular: "Düzensiz Hava",
    sea: "Deniz",
    customerCode: "Müşteri Kodu",
    packageCode: "Paket Kodu",
    batchCode: "Parti Kodu",
    warehouse: "Depo",
    origin: "Kaynak",
    destination: "Hedef",
    signIn: "Giriş Yap",
    signOut: "Çıkış Yap",
    welcome: "Hoş Geldiniz",
  },
  fa: {
    dashboard: "داشبورد",
    customers: "مشتریان",
    packages: "بسته‌ها",
    batches: "دسته‌ها",
    warehouses: "انبارها",
    countries: "کشورها",
    pricing: "قیمت‌گذاری",
    accounting: "حسابداری",
    invoices: "فاکتورها",
    reports: "گزارش‌ها",
    users: "کاربران",
    settings: "تنظیمات",
    auditLogs: "لاگ‌های حسابرسی",
    dataManagement: "مدیریت داده‌ها",
    create: "ایجاد",
    edit: "ویرایش",
    delete: "حذف",
    save: "ذخیره",
    cancel: "لغو",
    search: "جستجو",
    filter: "فیلتر",
    export: "خروجی",
    active: "فعال",
    inactive: "غیرفعال",
    pending: "در انتظار",
    delivered: "تحویل داده شده",
    inTransit: "در حال ارسال",
    name: "نام",
    email: "ایمیل",
    phone: "تلفن",
    address: "آدرس",
    status: "وضعیت",
    date: "تاریخ",
    amount: "مبلغ",
    balance: "موجودی",
    total: "جمع",
    trackingNumber: "شماره پیگیری",
    weight: "وزن",
    dimensions: "ابعاد",
    shippingType: "نوع ارسال",
    airRegular: "هوایی معمولی",
    airIrregular: "هوایی نامنظم",
    sea: "دریایی",
    customerCode: "کد مشتری",
    packageCode: "کد بسته",
    batchCode: "کد دسته",
    warehouse: "انبار",
    origin: "مبدأ",
    destination: "مقصد",
    signIn: "ورود",
    signOut: "خروج",
    welcome: "خوش آمدید",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("wazn-language");
    return (saved as Language) || "en";
  });

  const isRTL = RTL_LANGUAGES.includes(language);

  useEffect(() => {
    localStorage.setItem("wazn-language", language);
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
