#!/usr/bin/env python3
"""
Comprehensive translation script for all remaining pages in Wazn Express.
This script will add all necessary translations to locale files and update TSX files.
"""

import json
import re
from pathlib import Path
from collections import defaultdict

LOCALES_DIR = Path("/home/ubuntu/wazn-express/client/src/locales")
PAGES_DIR = Path("/home/ubuntu/wazn-express/client/src/pages")

# Comprehensive translations dictionary organized by section
ALL_TRANSLATIONS = {
    # ============ COMMON ============
    "common": {
        "save": {"ku": "تۆمارکردن", "en": "Save", "ar": "حفظ", "zh": "保存"},
        "saving": {"ku": "تۆمارکردن...", "en": "Saving...", "ar": "جاري الحفظ...", "zh": "保存中..."},
        "edit": {"ku": "دەستکاری", "en": "Edit", "ar": "تعديل", "zh": "编辑"},
        "delete": {"ku": "سڕینەوە", "en": "Delete", "ar": "حذف", "zh": "删除"},
        "add": {"ku": "زیادکردن", "en": "Add", "ar": "إضافة", "zh": "添加"},
        "create": {"ku": "دروستکردن", "en": "Create", "ar": "إنشاء", "zh": "创建"},
        "update": {"ku": "نوێکردنەوە", "en": "Update", "ar": "تحديث", "zh": "更新"},
        "search": {"ku": "گەڕان", "en": "Search", "ar": "بحث", "zh": "搜索"},
        "filter": {"ku": "فلتەر", "en": "Filter", "ar": "تصفية", "zh": "筛选"},
        "filters": {"ku": "فلتەرەکان", "en": "Filters", "ar": "التصفيات", "zh": "筛选"},
        "export": {"ku": "هەناردەکردن", "en": "Export", "ar": "تصدير", "zh": "导出"},
        "import": {"ku": "هاوردەکردن", "en": "Import", "ar": "استيراد", "zh": "导入"},
        "close": {"ku": "داخستن", "en": "Close", "ar": "إغلاق", "zh": "关闭"},
        "confirm": {"ku": "دڵنیاکردنەوە", "en": "Confirm", "ar": "تأكيد", "zh": "确认"},
        "yes": {"ku": "بەڵێ", "en": "Yes", "ar": "نعم", "zh": "是"},
        "no": {"ku": "نەخێر", "en": "No", "ar": "لا", "zh": "否"},
        "all": {"ku": "هەموو", "en": "All", "ar": "الكل", "zh": "全部"},
        "none": {"ku": "هیچ", "en": "None", "ar": "لا شيء", "zh": "无"},
        "actions": {"ku": "کردارەکان", "en": "Actions", "ar": "الإجراءات", "zh": "操作"},
        "status": {"ku": "بارودۆخ", "en": "Status", "ar": "الحالة", "zh": "状态"},
        "date": {"ku": "بەروار", "en": "Date", "ar": "التاريخ", "zh": "日期"},
        "time": {"ku": "کات", "en": "Time", "ar": "الوقت", "zh": "时间"},
        "name": {"ku": "ناو", "en": "Name", "ar": "الاسم", "zh": "名称"},
        "description": {"ku": "وەسف", "en": "Description", "ar": "الوصف", "zh": "描述"},
        "notes": {"ku": "تێبینی", "en": "Notes", "ar": "ملاحظات", "zh": "备注"},
        "total": {"ku": "کۆ", "en": "Total", "ar": "المجموع", "zh": "总计"},
        "amount": {"ku": "بڕ", "en": "Amount", "ar": "المبلغ", "zh": "金额"},
        "price": {"ku": "نرخ", "en": "Price", "ar": "السعر", "zh": "价格"},
        "quantity": {"ku": "ژمارە", "en": "Quantity", "ar": "الكمية", "zh": "数量"},
        "weight": {"ku": "کێش", "en": "Weight", "ar": "الوزن", "zh": "重量"},
        "volume": {"ku": "قەبارە", "en": "Volume", "ar": "الحجم", "zh": "体积"},
        "success": {"ku": "سەرکەوتوو", "en": "Success", "ar": "نجاح", "zh": "成功"},
        "error": {"ku": "هەڵە", "en": "Error", "ar": "خطأ", "zh": "错误"},
        "warning": {"ku": "ئاگاداری", "en": "Warning", "ar": "تحذير", "zh": "警告"},
        "info": {"ku": "زانیاری", "en": "Info", "ar": "معلومات", "zh": "信息"},
        "noData": {"ku": "داتا نییە", "en": "No data", "ar": "لا توجد بيانات", "zh": "无数据"},
        "noResults": {"ku": "ئەنجام نەدۆزرایەوە", "en": "No results found", "ar": "لم يتم العثور على نتائج", "zh": "未找到结果"},
        "back": {"ku": "گەڕانەوە", "en": "Back", "ar": "رجوع", "zh": "返回"},
        "next": {"ku": "دواتر", "en": "Next", "ar": "التالي", "zh": "下一步"},
        "previous": {"ku": "پێشتر", "en": "Previous", "ar": "السابق", "zh": "上一步"},
        "submit": {"ku": "ناردن", "en": "Submit", "ar": "إرسال", "zh": "提交"},
        "reset": {"ku": "ڕیسێتکردن", "en": "Reset", "ar": "إعادة تعيين", "zh": "重置"},
        "clear": {"ku": "پاککردنەوە", "en": "Clear", "ar": "مسح", "zh": "清除"},
        "select": {"ku": "هەڵبژاردن", "en": "Select", "ar": "اختيار", "zh": "选择"},
        "download": {"ku": "داگرتن", "en": "Download", "ar": "تحميل", "zh": "下载"},
        "upload": {"ku": "بارکردن", "en": "Upload", "ar": "رفع", "zh": "上传"},
        "print": {"ku": "چاپکردن", "en": "Print", "ar": "طباعة", "zh": "打印"},
        "copy": {"ku": "کۆپیکردن", "en": "Copy", "ar": "نسخ", "zh": "复制"},
        "view": {"ku": "بینین", "en": "View", "ar": "عرض", "zh": "查看"},
        "details": {"ku": "وردەکاری", "en": "Details", "ar": "التفاصيل", "zh": "详情"},
        "more": {"ku": "زیاتر", "en": "More", "ar": "المزيد", "zh": "更多"},
        "less": {"ku": "کەمتر", "en": "Less", "ar": "أقل", "zh": "更少"},
        "active": {"ku": "چالاک", "en": "Active", "ar": "نشط", "zh": "活跃"},
        "inactive": {"ku": "ناچالاک", "en": "Inactive", "ar": "غير نشط", "zh": "不活跃"},
        "required": {"ku": "پێویست", "en": "Required", "ar": "مطلوب", "zh": "必填"},
        "optional": {"ku": "ئارەزوومەندانە", "en": "Optional", "ar": "اختياري", "zh": "可选"},
        "new": {"ku": "نوێ", "en": "New", "ar": "جديد", "zh": "新"},
        "old": {"ku": "کۆن", "en": "Old", "ar": "قديم", "zh": "旧"},
        "from": {"ku": "لە", "en": "From", "ar": "من", "zh": "从"},
        "to": {"ku": "بۆ", "en": "To", "ar": "إلى", "zh": "到"},
        "today": {"ku": "ئەمڕۆ", "en": "Today", "ar": "اليوم", "zh": "今天"},
        "yesterday": {"ku": "دوێنێ", "en": "Yesterday", "ar": "أمس", "zh": "昨天"},
        "tomorrow": {"ku": "سبەینێ", "en": "Tomorrow", "ar": "غداً", "zh": "明天"},
        "thisWeek": {"ku": "ئەم هەفتەیە", "en": "This Week", "ar": "هذا الأسبوع", "zh": "本周"},
        "lastWeek": {"ku": "هەفتەی ڕابردوو", "en": "Last Week", "ar": "الأسبوع الماضي", "zh": "上周"},
        "thisMonth": {"ku": "ئەم مانگە", "en": "This Month", "ar": "هذا الشهر", "zh": "本月"},
        "lastMonth": {"ku": "مانگی ڕابردوو", "en": "Last Month", "ar": "الشهر الماضي", "zh": "上个月"},
        "thisYear": {"ku": "ئەم ساڵە", "en": "This Year", "ar": "هذا العام", "zh": "今年"},
        "lastYear": {"ku": "ساڵی ڕابردوو", "en": "Last Year", "ar": "العام الماضي", "zh": "去年"},
        "loading": {"ku": "چاوەڕوانبە...", "en": "Loading...", "ar": "جاري التحميل...", "zh": "加载中..."},
        "cancel": {"ku": "پاشگەزبوونەوە", "en": "Cancel", "ar": "إلغاء", "zh": "取消"},
        "viewAll": {"ku": "هەموو ببینە", "en": "View All", "ar": "عرض الكل", "zh": "查看全部"},
        "type": {"ku": "جۆر", "en": "Type", "ar": "النوع", "zh": "类型"},
        "days": {"ku": "ڕۆژ", "en": "Days", "ar": "أيام", "zh": "天"},
        "hours": {"ku": "کاتژمێر", "en": "Hours", "ar": "ساعات", "zh": "小时"},
        "minutes": {"ku": "خولەک", "en": "Minutes", "ar": "دقائق", "zh": "分钟"},
        "seconds": {"ku": "چرکە", "en": "Seconds", "ar": "ثواني", "zh": "秒"},
        "kg": {"ku": "کیلۆگرام", "en": "kg", "ar": "كغ", "zh": "公斤"},
        "cbm": {"ku": "مەتری کیوبی", "en": "CBM", "ar": "متر مكعب", "zh": "立方米"},
        "usd": {"ku": "دۆلار", "en": "USD", "ar": "دولار", "zh": "美元"},
        "iqd": {"ku": "دینار", "en": "IQD", "ar": "دينار", "zh": "第纳尔"},
        "cny": {"ku": "یوان", "en": "CNY", "ar": "يوان", "zh": "人民币"},
        "code": {"ku": "کۆد", "en": "Code", "ar": "الرمز", "zh": "代码"},
        "phone": {"ku": "تەلەفۆن", "en": "Phone", "ar": "الهاتف", "zh": "电话"},
        "email": {"ku": "ئیمەیڵ", "en": "Email", "ar": "البريد الإلكتروني", "zh": "邮箱"},
        "address": {"ku": "ناونیشان", "en": "Address", "ar": "العنوان", "zh": "地址"},
        "city": {"ku": "شار", "en": "City", "ar": "المدينة", "zh": "城市"},
        "country": {"ku": "وڵات", "en": "Country", "ar": "البلد", "zh": "国家"},
        "governorate": {"ku": "پارێزگا", "en": "Governorate", "ar": "المحافظة", "zh": "省份"},
        "confirmDelete": {"ku": "دڵنیایت لە سڕینەوە؟", "en": "Are you sure you want to delete?", "ar": "هل أنت متأكد من الحذف؟", "zh": "确定要删除吗？"},
        "deleteSuccess": {"ku": "بە سەرکەوتوویی سڕایەوە", "en": "Deleted successfully", "ar": "تم الحذف بنجاح", "zh": "删除成功"},
        "saveSuccess": {"ku": "بە سەرکەوتوویی تۆمارکرا", "en": "Saved successfully", "ar": "تم الحفظ بنجاح", "zh": "保存成功"},
        "updateSuccess": {"ku": "بە سەرکەوتوویی نوێکرایەوە", "en": "Updated successfully", "ar": "تم التحديث بنجاح", "zh": "更新成功"},
        "createSuccess": {"ku": "بە سەرکەوتوویی دروستکرا", "en": "Created successfully", "ar": "تم الإنشاء بنجاح", "zh": "创建成功"},
        "searchPlaceholder": {"ku": "گەڕان...", "en": "Search...", "ar": "بحث...", "zh": "搜索..."},
        "noResultsFound": {"ku": "هیچ ئەنجامێک نەدۆزرایەوە", "en": "No results found", "ar": "لم يتم العثور على نتائج", "zh": "未找到结果"},
        "selectOption": {"ku": "هەڵبژێرە", "en": "Select an option", "ar": "اختر خياراً", "zh": "选择一个选项"},
        "enterValue": {"ku": "بەها داخڵ بکە", "en": "Enter value", "ar": "أدخل القيمة", "zh": "输入值"},
        "refresh": {"ku": "نوێکردنەوە", "en": "Refresh", "ar": "تحديث", "zh": "刷新"},
        "retry": {"ku": "دووبارە هەوڵبدەرەوە", "en": "Retry", "ar": "إعادة المحاولة", "zh": "重试"},
        "somethingWentWrong": {"ku": "کێشەیەک ڕوویدا", "en": "Something went wrong", "ar": "حدث خطأ ما", "zh": "出了点问题"},
    },
    
    # ============ CUSTOMERS ============
    "customers": {
        "title": {"ku": "کڕیارەکان", "en": "Customers", "ar": "العملاء", "zh": "客户"},
        "addCustomer": {"ku": "زیادکردنی کڕیار", "en": "Add Customer", "ar": "إضافة عميل", "zh": "添加客户"},
        "editCustomer": {"ku": "دەستکاریکردنی کڕیار", "en": "Edit Customer", "ar": "تعديل العميل", "zh": "编辑客户"},
        "deleteCustomer": {"ku": "سڕینەوەی کڕیار", "en": "Delete Customer", "ar": "حذف العميل", "zh": "删除客户"},
        "customerName": {"ku": "ناوی کڕیار", "en": "Customer Name", "ar": "اسم العميل", "zh": "客户名称"},
        "customerCode": {"ku": "کۆدی کڕیار", "en": "Customer Code", "ar": "رمز العميل", "zh": "客户代码"},
        "fullName": {"ku": "ناوی تەواو", "en": "Full Name", "ar": "الاسم الكامل", "zh": "全名"},
        "balance": {"ku": "باڵانس", "en": "Balance", "ar": "الرصيد", "zh": "余额"},
        "totalPackages": {"ku": "کۆی پاکەتەکان", "en": "Total Packages", "ar": "إجمالي الطرود", "zh": "总包裹数"},
        "vipCustomer": {"ku": "کڕیاری VIP", "en": "VIP Customer", "ar": "عميل VIP", "zh": "VIP客户"},
        "regularCustomer": {"ku": "کڕیاری ئاسایی", "en": "Regular Customer", "ar": "عميل عادي", "zh": "普通客户"},
        "customerDetails": {"ku": "وردەکاری کڕیار", "en": "Customer Details", "ar": "تفاصيل العميل", "zh": "客户详情"},
        "customerHistory": {"ku": "مێژووی کڕیار", "en": "Customer History", "ar": "سجل العميل", "zh": "客户历史"},
        "searchCustomers": {"ku": "گەڕان بە کڕیار...", "en": "Search customers...", "ar": "البحث عن عملاء...", "zh": "搜索客户..."},
        "noCustomers": {"ku": "هیچ کڕیارێک نییە", "en": "No customers found", "ar": "لم يتم العثور على عملاء", "zh": "未找到客户"},
        "customerCreated": {"ku": "کڕیار دروستکرا", "en": "Customer created", "ar": "تم إنشاء العميل", "zh": "客户已创建"},
        "customerUpdated": {"ku": "کڕیار نوێکرایەوە", "en": "Customer updated", "ar": "تم تحديث العميل", "zh": "客户已更新"},
        "customerDeleted": {"ku": "کڕیار سڕایەوە", "en": "Customer deleted", "ar": "تم حذف العميل", "zh": "客户已删除"},
        "mobile": {"ku": "مۆبایل", "en": "Mobile", "ar": "الجوال", "zh": "手机"},
        "secondaryPhone": {"ku": "ژمارەی دووەم", "en": "Secondary Phone", "ar": "الهاتف الثانوي", "zh": "备用电话"},
        "notes": {"ku": "تێبینی", "en": "Notes", "ar": "ملاحظات", "zh": "备注"},
        "registrationDate": {"ku": "بەرواری تۆمارکردن", "en": "Registration Date", "ar": "تاريخ التسجيل", "zh": "注册日期"},
        "lastActivity": {"ku": "دوایین چالاکی", "en": "Last Activity", "ar": "آخر نشاط", "zh": "最后活动"},
    },
    
    # ============ PACKAGES ============
    "packages": {
        "title": {"ku": "پاکەتەکان", "en": "Packages", "ar": "الطرود", "zh": "包裹"},
        "registerPackage": {"ku": "تۆمارکردنی پاکەت", "en": "Register Package", "ar": "تسجيل طرد", "zh": "登记包裹"},
        "packageCode": {"ku": "کۆدی پاکەت", "en": "Package Code", "ar": "رمز الطرد", "zh": "包裹代码"},
        "trackingNumber": {"ku": "ژمارەی تراکینگ", "en": "Tracking Number", "ar": "رقم التتبع", "zh": "追踪号"},
        "actualWeight": {"ku": "کێشی ڕاستەقینە", "en": "Actual Weight", "ar": "الوزن الفعلي", "zh": "实际重量"},
        "volumetricWeight": {"ku": "کێشی قەبارەیی", "en": "Volumetric Weight", "ar": "الوزن الحجمي", "zh": "体积重量"},
        "chargeableWeight": {"ku": "کێشی حیسابکراو", "en": "Chargeable Weight", "ar": "الوزن المحاسب", "zh": "计费重量"},
        "dimensions": {"ku": "قەبارەکان", "en": "Dimensions", "ar": "الأبعاد", "zh": "尺寸"},
        "length": {"ku": "درێژی", "en": "Length", "ar": "الطول", "zh": "长度"},
        "width": {"ku": "پانی", "en": "Width", "ar": "العرض", "zh": "宽度"},
        "height": {"ku": "بەرزی", "en": "Height", "ar": "الارتفاع", "zh": "高度"},
        "registered": {"ku": "تۆمارکراو", "en": "Registered", "ar": "مسجل", "zh": "已登记"},
        "inWarehouse": {"ku": "لە کۆگا", "en": "In Warehouse", "ar": "في المستودع", "zh": "在仓库"},
        "inBatch": {"ku": "لە باچ", "en": "In Batch", "ar": "في الدفعة", "zh": "在批次中"},
        "onRoute": {"ku": "لە ڕێگا", "en": "On Route", "ar": "في الطريق", "zh": "运输中"},
        "arrived": {"ku": "گەیشتووە", "en": "Arrived", "ar": "وصل", "zh": "已到达"},
        "delivered": {"ku": "گەیاندرا", "en": "Delivered", "ar": "تم التسليم", "zh": "已送达"},
        "returned": {"ku": "گەڕێندراوە", "en": "Returned", "ar": "مرتجع", "zh": "已退回"},
        "lost": {"ku": "ونبووە", "en": "Lost", "ar": "مفقود", "zh": "丢失"},
        "damaged": {"ku": "زیانی پێگەیشتووە", "en": "Damaged", "ar": "تالف", "zh": "损坏"},
        "airRegular": {"ku": "ئاسمانی ئاسایی", "en": "Air Regular", "ar": "جوي عادي", "zh": "普通空运"},
        "airIrregular": {"ku": "ئاسمانی نائاسایی", "en": "Air Irregular", "ar": "جوي غير عادي", "zh": "特殊空运"},
        "sea": {"ku": "دەریایی", "en": "Sea", "ar": "بحري", "zh": "海运"},
        "shippingType": {"ku": "جۆری گواستنەوە", "en": "Shipping Type", "ar": "نوع الشحن", "zh": "运输类型"},
        "packageDetails": {"ku": "وردەکاری پاکەت", "en": "Package Details", "ar": "تفاصيل الطرد", "zh": "包裹详情"},
        "searchPackages": {"ku": "گەڕان بە پاکەت...", "en": "Search packages...", "ar": "البحث عن طرود...", "zh": "搜索包裹..."},
        "noPackages": {"ku": "هیچ پاکەتێک نییە", "en": "No packages found", "ar": "لم يتم العثور على طرود", "zh": "未找到包裹"},
        "packageCreated": {"ku": "پاکەت تۆمارکرا", "en": "Package registered", "ar": "تم تسجيل الطرد", "zh": "包裹已登记"},
        "packageUpdated": {"ku": "پاکەت نوێکرایەوە", "en": "Package updated", "ar": "تم تحديث الطرد", "zh": "包裹已更新"},
        "packageDeleted": {"ku": "پاکەت سڕایەوە", "en": "Package deleted", "ar": "تم حذف الطرد", "zh": "包裹已删除"},
        "shippingCost": {"ku": "کرێی گواستنەوە", "en": "Shipping Cost", "ar": "تكلفة الشحن", "zh": "运费"},
        "totalCost": {"ku": "کۆی تێچوو", "en": "Total Cost", "ar": "التكلفة الإجمالية", "zh": "总费用"},
        "content": {"ku": "ناوەڕۆک", "en": "Content", "ar": "المحتوى", "zh": "内容"},
        "contentDescription": {"ku": "وەسفی ناوەڕۆک", "en": "Content Description", "ar": "وصف المحتوى", "zh": "内容描述"},
        "declaredValue": {"ku": "نرخی ڕاگەیەندراو", "en": "Declared Value", "ar": "القيمة المعلنة", "zh": "申报价值"},
        "insurance": {"ku": "بیمە", "en": "Insurance", "ar": "التأمين", "zh": "保险"},
        "insured": {"ku": "بیمەکراو", "en": "Insured", "ar": "مؤمن", "zh": "已投保"},
        "notInsured": {"ku": "بیمە نەکراو", "en": "Not Insured", "ar": "غير مؤمن", "zh": "未投保"},
        "fragile": {"ku": "شکێنەر", "en": "Fragile", "ar": "قابل للكسر", "zh": "易碎"},
        "dangerous": {"ku": "مەترسیدار", "en": "Dangerous", "ar": "خطر", "zh": "危险品"},
        "receiver": {"ku": "وەرگر", "en": "Receiver", "ar": "المستلم", "zh": "收件人"},
        "sender": {"ku": "ناردەر", "en": "Sender", "ar": "المرسل", "zh": "寄件人"},
        "origin": {"ku": "سەرچاوە", "en": "Origin", "ar": "المصدر", "zh": "起点"},
        "destination": {"ku": "مەبەست", "en": "Destination", "ar": "الوجهة", "zh": "目的地"},
        "eta": {"ku": "کاتی گەیشتنی چاوەڕوانکراو", "en": "ETA", "ar": "الوصول المتوقع", "zh": "预计到达"},
        "ata": {"ku": "کاتی گەیشتنی ڕاستەقینە", "en": "ATA", "ar": "الوصول الفعلي", "zh": "实际到达"},
        "pieces": {"ku": "پارچە", "en": "Pieces", "ar": "قطع", "zh": "件"},
        "boxes": {"ku": "سندوق", "en": "Boxes", "ar": "صناديق", "zh": "箱"},
        "pallets": {"ku": "پالێت", "en": "Pallets", "ar": "منصات", "zh": "托盘"},
    },
    
    # ============ BATCHES ============
    "batches": {
        "title": {"ku": "باچەکان", "en": "Batches", "ar": "الدفعات", "zh": "批次"},
        "newBatch": {"ku": "باچی نوێ", "en": "New Batch", "ar": "دفعة جديدة", "zh": "新批次"},
        "batchCode": {"ku": "کۆدی باچ", "en": "Batch Code", "ar": "رمز الدفعة", "zh": "批次代码"},
        "batchName": {"ku": "ناوی باچ", "en": "Batch Name", "ar": "اسم الدفعة", "zh": "批次名称"},
        "carrier": {"ku": "گواستنەوە", "en": "Carrier", "ar": "الناقل", "zh": "承运商"},
        "departureDate": {"ku": "بەرواری ڕۆیشتن", "en": "Departure Date", "ar": "تاريخ المغادرة", "zh": "出发日期"},
        "expectedArrival": {"ku": "گەیشتنی چاوەڕوانکراو", "en": "Expected Arrival", "ar": "الوصول المتوقع", "zh": "预计到达"},
        "actualArrival": {"ku": "گەیشتنی ڕاستەقینە", "en": "Actual Arrival", "ar": "الوصول الفعلي", "zh": "实际到达"},
        "preparing": {"ku": "ئامادەکردن", "en": "Preparing", "ar": "جاري التحضير", "zh": "准备中"},
        "departed": {"ku": "ڕۆیشتووە", "en": "Departed", "ar": "غادر", "zh": "已出发"},
        "inTransit": {"ku": "لە گواستنەوە", "en": "In Transit", "ar": "في الطريق", "zh": "运输中"},
        "completed": {"ku": "تەواوبوو", "en": "Completed", "ar": "مكتمل", "zh": "已完成"},
        "cancelled": {"ku": "هەڵوەشێنراوە", "en": "Cancelled", "ar": "ملغى", "zh": "已取消"},
        "batchDetails": {"ku": "وردەکاری باچ", "en": "Batch Details", "ar": "تفاصيل الدفعة", "zh": "批次详情"},
        "packagesInBatch": {"ku": "پاکەتەکانی باچ", "en": "Packages in Batch", "ar": "الطرود في الدفعة", "zh": "批次中的包裹"},
        "addToBatch": {"ku": "زیادکردن بۆ باچ", "en": "Add to Batch", "ar": "إضافة للدفعة", "zh": "添加到批次"},
        "removeFromBatch": {"ku": "لابردن لە باچ", "en": "Remove from Batch", "ar": "إزالة من الدفعة", "zh": "从批次移除"},
        "closeBatch": {"ku": "داخستنی باچ", "en": "Close Batch", "ar": "إغلاق الدفعة", "zh": "关闭批次"},
        "totalWeight": {"ku": "کۆی کێش", "en": "Total Weight", "ar": "الوزن الإجمالي", "zh": "总重量"},
        "totalVolume": {"ku": "کۆی قەبارە", "en": "Total Volume", "ar": "الحجم الإجمالي", "zh": "总体积"},
        "totalPackages": {"ku": "کۆی پاکەتەکان", "en": "Total Packages", "ar": "إجمالي الطرود", "zh": "总包裹数"},
        "flightNumber": {"ku": "ژمارەی فڕۆکە", "en": "Flight Number", "ar": "رقم الرحلة", "zh": "航班号"},
        "vesselName": {"ku": "ناوی کەشتی", "en": "Vessel Name", "ar": "اسم السفينة", "zh": "船名"},
        "containerNumber": {"ku": "ژمارەی کۆنتەینەر", "en": "Container Number", "ar": "رقم الحاوية", "zh": "集装箱号"},
        "blNumber": {"ku": "ژمارەی B/L", "en": "B/L Number", "ar": "رقم بوليصة الشحن", "zh": "提单号"},
        "route": {"ku": "ڕێگا", "en": "Route", "ar": "المسار", "zh": "路线"},
        "searchBatches": {"ku": "گەڕان بە باچ...", "en": "Search batches...", "ar": "البحث عن دفعات...", "zh": "搜索批次..."},
        "noBatches": {"ku": "هیچ باچێک نییە", "en": "No batches found", "ar": "لم يتم العثور على دفعات", "zh": "未找到批次"},
        "batchCreated": {"ku": "باچ دروستکرا", "en": "Batch created", "ar": "تم إنشاء الدفعة", "zh": "批次已创建"},
        "batchUpdated": {"ku": "باچ نوێکرایەوە", "en": "Batch updated", "ar": "تم تحديث الدفعة", "zh": "批次已更新"},
        "batchDeleted": {"ku": "باچ سڕایەوە", "en": "Batch deleted", "ar": "تم حذف الدفعة", "zh": "批次已删除"},
    },
    
    # ============ FINANCE ============
    "finance": {
        "title": {"ku": "دارایی", "en": "Finance", "ar": "المالية", "zh": "财务"},
        "payments": {"ku": "پارەدانەکان", "en": "Payments", "ar": "المدفوعات", "zh": "付款"},
        "recordPayment": {"ku": "تۆمارکردنی پارەدان", "en": "Record Payment", "ar": "تسجيل دفعة", "zh": "记录付款"},
        "debtors": {"ku": "قەرزداران", "en": "Debtors", "ar": "المدينون", "zh": "债务人"},
        "totalDebt": {"ku": "کۆی قەرز", "en": "Total Debt", "ar": "إجمالي الدين", "zh": "总债务"},
        "totalPayments": {"ku": "کۆی پارەدان", "en": "Total Payments", "ar": "إجمالي المدفوعات", "zh": "总付款"},
        "totalAccounts": {"ku": "کۆی حسابەکان", "en": "Total Accounts", "ar": "إجمالي الحسابات", "zh": "账户总数"},
        "activeAccounts": {"ku": "حسابی چالاک", "en": "Active Accounts", "ar": "الحسابات النشطة", "zh": "活跃账户"},
        "netBalance": {"ku": "باڵانسی نێت", "en": "Net Balance", "ar": "الرصيد الصافي", "zh": "净余额"},
        "overview": {"ku": "پوختە", "en": "Overview", "ar": "نظرة عامة", "zh": "概览"},
        "accounts": {"ku": "حسابەکان", "en": "Accounts", "ar": "الحسابات", "zh": "账户"},
        "customerAccounts": {"ku": "حسابی کڕیاران", "en": "Customer Accounts", "ar": "حسابات العملاء", "zh": "客户账户"},
        "allAccounts": {"ku": "هەموو حسابەکان", "en": "All Accounts", "ar": "جميع الحسابات", "zh": "所有账户"},
        "accountNumber": {"ku": "ژمارەی حساب", "en": "Account Number", "ar": "رقم الحساب", "zh": "账号"},
        "cash": {"ku": "نەقد", "en": "Cash", "ar": "نقداً", "zh": "现金"},
        "bankTransfer": {"ku": "گواستنەوەی بانکی", "en": "Bank Transfer", "ar": "تحويل بنكي", "zh": "银行转账"},
        "card": {"ku": "کارت", "en": "Card", "ar": "بطاقة", "zh": "卡"},
        "bank": {"ku": "بانک", "en": "Bank", "ar": "بنك", "zh": "银行"},
        "method": {"ku": "شێواز", "en": "Method", "ar": "الطريقة", "zh": "方式"},
        "referenceNumber": {"ku": "ژمارەی سەند", "en": "Reference Number", "ar": "رقم المرجع", "zh": "参考编号"},
        "totalReceived": {"ku": "کۆی وەرگیراو", "en": "Total Received", "ar": "إجمالي المستلم", "zh": "总收款"},
        "income": {"ku": "داهات", "en": "Income", "ar": "الدخل", "zh": "收入"},
        "expense": {"ku": "خەرجی", "en": "Expense", "ar": "المصروف", "zh": "支出"},
        "profit": {"ku": "قازانج", "en": "Profit", "ar": "الربح", "zh": "利润"},
        "loss": {"ku": "زەرەر", "en": "Loss", "ar": "الخسارة", "zh": "亏损"},
        "balance": {"ku": "باڵانس", "en": "Balance", "ar": "الرصيد", "zh": "余额"},
        "debt": {"ku": "قەرز", "en": "Debt", "ar": "الدين", "zh": "债务"},
        "credit": {"ku": "کرێدیت", "en": "Credit", "ar": "الائتمان", "zh": "信用"},
        "paymentDate": {"ku": "بەرواری پارەدان", "en": "Payment Date", "ar": "تاريخ الدفع", "zh": "付款日期"},
        "paymentMethod": {"ku": "شێوازی پارەدان", "en": "Payment Method", "ar": "طريقة الدفع", "zh": "付款方式"},
        "paymentAmount": {"ku": "بڕی پارەدان", "en": "Payment Amount", "ar": "مبلغ الدفع", "zh": "付款金额"},
        "paymentNotes": {"ku": "تێبینی پارەدان", "en": "Payment Notes", "ar": "ملاحظات الدفع", "zh": "付款备注"},
        "noPayments": {"ku": "هیچ پارەدانێک نییە", "en": "No payments found", "ar": "لم يتم العثور على مدفوعات", "zh": "未找到付款"},
        "paymentRecorded": {"ku": "پارەدان تۆمارکرا", "en": "Payment recorded", "ar": "تم تسجيل الدفع", "zh": "付款已记录"},
        "selectCustomer": {"ku": "کڕیار هەڵبژێرە", "en": "Select customer", "ar": "اختر العميل", "zh": "选择客户"},
        "enterAmount": {"ku": "بڕ داخڵ بکە", "en": "Enter amount", "ar": "أدخل المبلغ", "zh": "输入金额"},
        "mobileMoney": {"ku": "پارەی مۆبایل", "en": "Mobile Money", "ar": "المال المتنقل", "zh": "移动支付"},
        "other": {"ku": "تر", "en": "Other", "ar": "أخرى", "zh": "其他"},
        "debtorCustomers": {"ku": "کڕیارە قەرزدارەکان", "en": "Debtor Customers", "ar": "العملاء المدينون", "zh": "欠款客户"},
        "balanceUsd": {"ku": "باڵانس (USD)", "en": "Balance (USD)", "ar": "الرصيد (USD)", "zh": "余额 (USD)"},
        "balanceIqd": {"ku": "باڵانس (IQD)", "en": "Balance (IQD)", "ar": "الرصيد (IQD)", "zh": "余额 (IQD)"},
        "searchPayments": {"ku": "گەڕان بە پارەدان...", "en": "Search payments...", "ar": "البحث عن مدفوعات...", "zh": "搜索付款..."},
        "searchAccounts": {"ku": "گەڕان بە حساب...", "en": "Search accounts...", "ar": "البحث عن حسابات...", "zh": "搜索账户..."},
        "recordFirstPayment": {"ku": "یەکەم پارەدان تۆمار بکە", "en": "Record your first payment", "ar": "سجل أول دفعة", "zh": "记录您的第一笔付款"},
    },
    
    # ============ DASHBOARD ============
    "dashboard": {
        "title": {"ku": "داشبۆرد", "en": "Dashboard", "ar": "لوحة التحكم", "zh": "仪表板"},
        "welcome": {"ku": "بەخێربێیت!", "en": "Welcome!", "ar": "مرحباً!", "zh": "欢迎！"},
        "dailyReport": {"ku": "ڕاپۆرتی ڕۆژانە", "en": "Daily Report", "ar": "التقرير اليومي", "zh": "每日报告"},
        "todayIncome": {"ku": "داهاتی ئەمڕۆ", "en": "Today's Income", "ar": "دخل اليوم", "zh": "今日收入"},
        "weeklyIncome": {"ku": "داهاتی هەفتانە", "en": "Weekly Income", "ar": "الدخل الأسبوعي", "zh": "周收入"},
        "monthlyIncome": {"ku": "داهاتی مانگانە", "en": "Monthly Income", "ar": "الدخل الشهري", "zh": "月收入"},
        "todayPackages": {"ku": "پاکەتەکانی ئەمڕۆ", "en": "Today's Packages", "ar": "طرود اليوم", "zh": "今日包裹"},
        "newCustomers": {"ku": "کڕیارە نوێیەکان", "en": "New Customers", "ar": "العملاء الجدد", "zh": "新客户"},
        "activeBatches": {"ku": "باچە چالاکەکان", "en": "Active Batches", "ar": "الدفعات النشطة", "zh": "活跃批次"},
        "recentActivity": {"ku": "چالاکیە تازەکان", "en": "Recent Activity", "ar": "النشاط الأخير", "zh": "最近活动"},
        "quickActions": {"ku": "کردارە خێراکان", "en": "Quick Actions", "ar": "إجراءات سريعة", "zh": "快速操作"},
        "statistics": {"ku": "ئامارەکان", "en": "Statistics", "ar": "الإحصائيات", "zh": "统计"},
        "overview": {"ku": "پوختە", "en": "Overview", "ar": "نظرة عامة", "zh": "概览"},
        "pdfDownloaded": {"ku": "PDF داگیرا", "en": "PDF downloaded", "ar": "تم تحميل PDF", "zh": "PDF已下载"},
        "pdfError": {"ku": "هەڵەی داگرتنی PDF", "en": "PDF download error", "ar": "خطأ في تحميل PDF", "zh": "PDF下载错误"},
        "exportPdf": {"ku": "هەناردەکردنی PDF", "en": "Export PDF", "ar": "تصدير PDF", "zh": "导出PDF"},
    },
    
    # ============ SETTINGS ============
    "settings": {
        "title": {"ku": "ڕێکخستنەکان", "en": "Settings", "ar": "الإعدادات", "zh": "设置"},
        "language": {"ku": "زمان", "en": "Language", "ar": "اللغة", "zh": "语言"},
        "appearance": {"ku": "ڕووکار", "en": "Appearance", "ar": "المظهر", "zh": "外观"},
        "darkMode": {"ku": "تاریک", "en": "Dark Mode", "ar": "الوضع المظلم", "zh": "深色模式"},
        "lightMode": {"ku": "ڕووناک", "en": "Light Mode", "ar": "الوضع الفاتح", "zh": "浅色模式"},
        "notifications": {"ku": "ئاگادارکردنەوەکان", "en": "Notifications", "ar": "الإشعارات", "zh": "通知"},
        "profile": {"ku": "پڕۆفایل", "en": "Profile", "ar": "الملف الشخصي", "zh": "个人资料"},
        "security": {"ku": "ئەمنیەت", "en": "Security", "ar": "الأمان", "zh": "安全"},
        "changePassword": {"ku": "گۆڕینی وشەی نهێنی", "en": "Change Password", "ar": "تغيير كلمة المرور", "zh": "修改密码"},
        "general": {"ku": "گشتی", "en": "General", "ar": "عام", "zh": "通用"},
        "account": {"ku": "هەژمار", "en": "Account", "ar": "الحساب", "zh": "账户"},
        "preferences": {"ku": "ڕێکخستنەکان", "en": "Preferences", "ar": "التفضيلات", "zh": "偏好设置"},
        "saveChanges": {"ku": "پاشەکەوتکردنی گۆڕانکاریەکان", "en": "Save Changes", "ar": "حفظ التغييرات", "zh": "保存更改"},
        "discardChanges": {"ku": "پاشگەزبوونەوە لە گۆڕانکاریەکان", "en": "Discard Changes", "ar": "تجاهل التغييرات", "zh": "放弃更改"},
    },
    
    # ============ REPORTS ============
    "reports": {
        "title": {"ku": "ڕاپۆرتەکان", "en": "Reports", "ar": "التقارير", "zh": "报告"},
        "weeklyReport": {"ku": "ڕاپۆرتی هەفتانە", "en": "Weekly Report", "ar": "التقرير الأسبوعي", "zh": "周报"},
        "monthlyReport": {"ku": "ڕاپۆرتی مانگانە", "en": "Monthly Report", "ar": "التقرير الشهري", "zh": "月报"},
        "yearlyReport": {"ku": "ڕاپۆرتی ساڵانە", "en": "Yearly Report", "ar": "التقرير السنوي", "zh": "年报"},
        "customReport": {"ku": "ڕاپۆرتی تایبەت", "en": "Custom Report", "ar": "تقرير مخصص", "zh": "自定义报告"},
        "generateReport": {"ku": "دروستکردنی ڕاپۆرت", "en": "Generate Report", "ar": "إنشاء التقرير", "zh": "生成报告"},
        "downloadReport": {"ku": "داگرتنی ڕاپۆرت", "en": "Download Report", "ar": "تحميل التقرير", "zh": "下载报告"},
        "printReport": {"ku": "چاپکردنی ڕاپۆرت", "en": "Print Report", "ar": "طباعة التقرير", "zh": "打印报告"},
        "dateRange": {"ku": "ماوەی بەروار", "en": "Date Range", "ar": "نطاق التاريخ", "zh": "日期范围"},
        "startDate": {"ku": "بەرواری دەستپێک", "en": "Start Date", "ar": "تاريخ البدء", "zh": "开始日期"},
        "endDate": {"ku": "بەرواری کۆتایی", "en": "End Date", "ar": "تاريخ الانتهاء", "zh": "结束日期"},
        "selectPeriod": {"ku": "ماوە هەڵبژێرە", "en": "Select Period", "ar": "اختر الفترة", "zh": "选择期间"},
        "financialReport": {"ku": "ڕاپۆرتی دارایی", "en": "Financial Report", "ar": "التقرير المالي", "zh": "财务报告"},
        "operationalReport": {"ku": "ڕاپۆرتی کارگێڕی", "en": "Operational Report", "ar": "التقرير التشغيلي", "zh": "运营报告"},
        "customerReport": {"ku": "ڕاپۆرتی کڕیاران", "en": "Customer Report", "ar": "تقرير العملاء", "zh": "客户报告"},
        "packageReport": {"ku": "ڕاپۆرتی پاکەتەکان", "en": "Package Report", "ar": "تقرير الطرود", "zh": "包裹报告"},
    },
    
    # ============ SCANNING ============
    "scanning": {
        "title": {"ku": "سکان", "en": "Scan", "ar": "مسح", "zh": "扫描"},
        "scanPackage": {"ku": "سکانی پاکەت", "en": "Scan Package", "ar": "مسح الطرد", "zh": "扫描包裹"},
        "scanBarcode": {"ku": "سکانی بارکۆد", "en": "Scan Barcode", "ar": "مسح الباركود", "zh": "扫描条码"},
        "camera": {"ku": "کامێرا", "en": "Camera", "ar": "الكاميرا", "zh": "相机"},
        "manualEntry": {"ku": "داخڵکردنی دەستی", "en": "Manual Entry", "ar": "إدخال يدوي", "zh": "手动输入"},
        "todayScans": {"ku": "سکانەکانی ئەمڕۆ", "en": "Today's Scans", "ar": "عمليات المسح اليوم", "zh": "今日扫描"},
        "totalScans": {"ku": "کۆی سکانەکان", "en": "Total Scans", "ar": "إجمالي عمليات المسح", "zh": "总扫描数"},
        "scanSuccess": {"ku": "سکان سەرکەوتوو بوو", "en": "Scan successful", "ar": "تم المسح بنجاح", "zh": "扫描成功"},
        "scanFailed": {"ku": "سکان سەرکەوتوو نەبوو", "en": "Scan failed", "ar": "فشل المسح", "zh": "扫描失败"},
        "packageNotFound": {"ku": "پاکەت نەدۆزرایەوە", "en": "Package not found", "ar": "الطرد غير موجود", "zh": "未找到包裹"},
        "alreadyScanned": {"ku": "پێشتر سکانکراوە", "en": "Already scanned", "ar": "تم المسح مسبقاً", "zh": "已扫描"},
        "enterTrackingNumber": {"ku": "ژمارەی تراکینگ داخڵ بکە", "en": "Enter tracking number", "ar": "أدخل رقم التتبع", "zh": "输入追踪号"},
        "scanHistory": {"ku": "مێژووی سکان", "en": "Scan History", "ar": "سجل المسح", "zh": "扫描历史"},
        "lastScanned": {"ku": "دوایین سکان", "en": "Last Scanned", "ar": "آخر مسح", "zh": "最后扫描"},
        "scanMode": {"ku": "شێوازی سکان", "en": "Scan Mode", "ar": "وضع المسح", "zh": "扫描模式"},
        "continuousScan": {"ku": "سکانی بەردەوام", "en": "Continuous Scan", "ar": "المسح المستمر", "zh": "连续扫描"},
        "singleScan": {"ku": "سکانی تاک", "en": "Single Scan", "ar": "مسح فردي", "zh": "单次扫描"},
    },
    
    # ============ FULL PACKAGE ============
    "fullPackage": {
        "title": {"ku": "پاکەتی تەواو", "en": "Full Package", "ar": "الطرد الكامل", "zh": "全包服务"},
        "newOrder": {"ku": "داواکاری نوێ", "en": "New Order", "ar": "طلب جديد", "zh": "新订单"},
        "orderCode": {"ku": "کۆدی داواکاری", "en": "Order Code", "ar": "رمز الطلب", "zh": "订单代码"},
        "productName": {"ku": "ناوی بەرهەم", "en": "Product Name", "ar": "اسم المنتج", "zh": "产品名称"},
        "productLink": {"ku": "لینکی بەرهەم", "en": "Product Link", "ar": "رابط المنتج", "zh": "产品链接"},
        "purchasePrice": {"ku": "نرخی کڕین", "en": "Purchase Price", "ar": "سعر الشراء", "zh": "采购价"},
        "sellingPrice": {"ku": "نرخی فرۆشتن", "en": "Selling Price", "ar": "سعر البيع", "zh": "售价"},
        "profit": {"ku": "قازانج", "en": "Profit", "ar": "الربح", "zh": "利润"},
        "supplier": {"ku": "دابینکەر", "en": "Supplier", "ar": "المورد", "zh": "供应商"},
        "orderStatus": {"ku": "بارودۆخی داواکاری", "en": "Order Status", "ar": "حالة الطلب", "zh": "订单状态"},
        "pending": {"ku": "چاوەڕوان", "en": "Pending", "ar": "قيد الانتظار", "zh": "待处理"},
        "processing": {"ku": "لە کاردا", "en": "Processing", "ar": "قيد المعالجة", "zh": "处理中"},
        "shipped": {"ku": "ناردراوە", "en": "Shipped", "ar": "تم الشحن", "zh": "已发货"},
        "delivered": {"ku": "گەیاندرا", "en": "Delivered", "ar": "تم التسليم", "zh": "已送达"},
        "cancelled": {"ku": "هەڵوەشێنراوە", "en": "Cancelled", "ar": "ملغى", "zh": "已取消"},
        "orderDetails": {"ku": "وردەکاری داواکاری", "en": "Order Details", "ar": "تفاصيل الطلب", "zh": "订单详情"},
        "orderHistory": {"ku": "مێژووی داواکاری", "en": "Order History", "ar": "سجل الطلبات", "zh": "订单历史"},
        "createOrder": {"ku": "دروستکردنی داواکاری", "en": "Create Order", "ar": "إنشاء طلب", "zh": "创建订单"},
        "editOrder": {"ku": "دەستکاریکردنی داواکاری", "en": "Edit Order", "ar": "تعديل الطلب", "zh": "编辑订单"},
        "deleteOrder": {"ku": "سڕینەوەی داواکاری", "en": "Delete Order", "ar": "حذف الطلب", "zh": "删除订单"},
        "searchOrders": {"ku": "گەڕان بە داواکاری...", "en": "Search orders...", "ar": "البحث عن طلبات...", "zh": "搜索订单..."},
        "noOrders": {"ku": "هیچ داواکاریەک نییە", "en": "No orders found", "ar": "لم يتم العثور على طلبات", "zh": "未找到订单"},
        "orderCreated": {"ku": "داواکاری دروستکرا", "en": "Order created", "ar": "تم إنشاء الطلب", "zh": "订单已创建"},
        "orderUpdated": {"ku": "داواکاری نوێکرایەوە", "en": "Order updated", "ar": "تم تحديث الطلب", "zh": "订单已更新"},
        "orderDeleted": {"ku": "داواکاری سڕایەوە", "en": "Order deleted", "ar": "تم حذف الطلب", "zh": "订单已删除"},
    },
    
    # ============ SUPPLIERS ============
    "suppliers": {
        "title": {"ku": "دابینکەرەکان", "en": "Suppliers", "ar": "الموردون", "zh": "供应商"},
        "addSupplier": {"ku": "زیادکردنی دابینکەر", "en": "Add Supplier", "ar": "إضافة مورد", "zh": "添加供应商"},
        "editSupplier": {"ku": "دەستکاریکردنی دابینکەر", "en": "Edit Supplier", "ar": "تعديل المورد", "zh": "编辑供应商"},
        "deleteSupplier": {"ku": "سڕینەوەی دابینکەر", "en": "Delete Supplier", "ar": "حذف المورد", "zh": "删除供应商"},
        "supplierName": {"ku": "ناوی دابینکەر", "en": "Supplier Name", "ar": "اسم المورد", "zh": "供应商名称"},
        "supplierCode": {"ku": "کۆدی دابینکەر", "en": "Supplier Code", "ar": "رمز المورد", "zh": "供应商代码"},
        "contactPerson": {"ku": "کەسی پەیوەندی", "en": "Contact Person", "ar": "جهة الاتصال", "zh": "联系人"},
        "searchSuppliers": {"ku": "گەڕان بە دابینکەر...", "en": "Search suppliers...", "ar": "البحث عن موردين...", "zh": "搜索供应商..."},
        "noSuppliers": {"ku": "هیچ دابینکەرێک نییە", "en": "No suppliers found", "ar": "لم يتم العثور على موردين", "zh": "未找到供应商"},
        "supplierCreated": {"ku": "دابینکەر دروستکرا", "en": "Supplier created", "ar": "تم إنشاء المورد", "zh": "供应商已创建"},
        "supplierUpdated": {"ku": "دابینکەر نوێکرایەوە", "en": "Supplier updated", "ar": "تم تحديث المورد", "zh": "供应商已更新"},
        "supplierDeleted": {"ku": "دابینکەر سڕایەوە", "en": "Supplier deleted", "ar": "تم حذف المورد", "zh": "供应商已删除"},
    },
    
    # ============ COMPANY FINANCE ============
    "companyFinance": {
        "title": {"ku": "دارایی کۆمپانیا", "en": "Company Finance", "ar": "مالية الشركة", "zh": "公司财务"},
        "profitLoss": {"ku": "قازانج و زەرەر", "en": "Profit & Loss", "ar": "الأرباح والخسائر", "zh": "盈亏"},
        "cashFlow": {"ku": "جووڵەی پارە", "en": "Cash Flow", "ar": "التدفق النقدي", "zh": "现金流"},
        "balanceSheet": {"ku": "تەرازووی حساب", "en": "Balance Sheet", "ar": "الميزانية العمومية", "zh": "资产负债表"},
        "bankAccounts": {"ku": "حسابە بانکییەکان", "en": "Bank Accounts", "ar": "الحسابات البنكية", "zh": "银行账户"},
        "expenses": {"ku": "خەرجییەکان", "en": "Expenses", "ar": "المصروفات", "zh": "支出"},
        "partners": {"ku": "هاوبەشەکان", "en": "Partners", "ar": "الشركاء", "zh": "合伙人"},
        "debts": {"ku": "قەرزەکان", "en": "Debts", "ar": "الديون", "zh": "债务"},
        "treasury": {"ku": "خەزنە", "en": "Treasury", "ar": "الخزينة", "zh": "财务"},
        "revenue": {"ku": "داهات", "en": "Revenue", "ar": "الإيرادات", "zh": "收入"},
        "grossProfit": {"ku": "قازانجی کۆ", "en": "Gross Profit", "ar": "الربح الإجمالي", "zh": "毛利润"},
        "netProfit": {"ku": "قازانجی نێت", "en": "Net Profit", "ar": "صافي الربح", "zh": "净利润"},
        "operatingExpenses": {"ku": "خەرجیە کارگێڕییەکان", "en": "Operating Expenses", "ar": "المصروفات التشغيلية", "zh": "运营费用"},
        "assets": {"ku": "سامانەکان", "en": "Assets", "ar": "الأصول", "zh": "资产"},
        "liabilities": {"ku": "ئەرکەکان", "en": "Liabilities", "ar": "الالتزامات", "zh": "负债"},
        "equity": {"ku": "سەرمایە", "en": "Equity", "ar": "حقوق الملكية", "zh": "权益"},
    },
    
    # ============ WAREHOUSES ============
    "warehouses": {
        "title": {"ku": "کۆگاکان", "en": "Warehouses", "ar": "المستودعات", "zh": "仓库"},
        "addWarehouse": {"ku": "زیادکردنی کۆگا", "en": "Add Warehouse", "ar": "إضافة مستودع", "zh": "添加仓库"},
        "warehouseName": {"ku": "ناوی کۆگا", "en": "Warehouse Name", "ar": "اسم المستودع", "zh": "仓库名称"},
        "warehouseCode": {"ku": "کۆدی کۆگا", "en": "Warehouse Code", "ar": "رمز المستودع", "zh": "仓库代码"},
        "location": {"ku": "شوێن", "en": "Location", "ar": "الموقع", "zh": "位置"},
        "capacity": {"ku": "گنجایش", "en": "Capacity", "ar": "السعة", "zh": "容量"},
        "currentStock": {"ku": "ئەمبارەی ئێستا", "en": "Current Stock", "ar": "المخزون الحالي", "zh": "当前库存"},
        "operations": {"ku": "کارەکان", "en": "Operations", "ar": "العمليات", "zh": "操作"},
        "inbound": {"ku": "هاتوو", "en": "Inbound", "ar": "الوارد", "zh": "入库"},
        "outbound": {"ku": "چوو", "en": "Outbound", "ar": "الصادر", "zh": "出库"},
    },
    
    # ============ LABELS ============
    "labels": {
        "title": {"ku": "لەیبڵەکان", "en": "Labels", "ar": "الملصقات", "zh": "标签"},
        "printLabel": {"ku": "چاپکردنی لەیبڵ", "en": "Print Label", "ar": "طباعة الملصق", "zh": "打印标签"},
        "labelTemplate": {"ku": "قاڵبی لەیبڵ", "en": "Label Template", "ar": "قالب الملصق", "zh": "标签模板"},
        "labelSize": {"ku": "قەبارەی لەیبڵ", "en": "Label Size", "ar": "حجم الملصق", "zh": "标签尺寸"},
        "printAll": {"ku": "چاپکردنی هەموو", "en": "Print All", "ar": "طباعة الكل", "zh": "打印全部"},
        "printSelected": {"ku": "چاپکردنی هەڵبژێردراوەکان", "en": "Print Selected", "ar": "طباعة المحدد", "zh": "打印选中"},
        "qrCode": {"ku": "کۆدی QR", "en": "QR Code", "ar": "رمز QR", "zh": "二维码"},
        "barcode": {"ku": "بارکۆد", "en": "Barcode", "ar": "الباركود", "zh": "条形码"},
    },
    
    # ============ INVOICES ============
    "invoices": {
        "title": {"ku": "پسوڵەکان", "en": "Invoices", "ar": "الفواتير", "zh": "发票"},
        "createInvoice": {"ku": "دروستکردنی پسوڵە", "en": "Create Invoice", "ar": "إنشاء فاتورة", "zh": "创建发票"},
        "invoiceNumber": {"ku": "ژمارەی پسوڵە", "en": "Invoice Number", "ar": "رقم الفاتورة", "zh": "发票号"},
        "invoiceDate": {"ku": "بەرواری پسوڵە", "en": "Invoice Date", "ar": "تاريخ الفاتورة", "zh": "发票日期"},
        "dueDate": {"ku": "بەرواری سەردەم", "en": "Due Date", "ar": "تاريخ الاستحقاق", "zh": "到期日"},
        "subtotal": {"ku": "کۆی لاوەکی", "en": "Subtotal", "ar": "المجموع الفرعي", "zh": "小计"},
        "tax": {"ku": "باج", "en": "Tax", "ar": "الضريبة", "zh": "税"},
        "discount": {"ku": "داشکاندن", "en": "Discount", "ar": "الخصم", "zh": "折扣"},
        "grandTotal": {"ku": "کۆی گشتی", "en": "Grand Total", "ar": "المجموع الكلي", "zh": "总计"},
        "paid": {"ku": "پارەدراو", "en": "Paid", "ar": "مدفوع", "zh": "已付"},
        "unpaid": {"ku": "پارەنەدراو", "en": "Unpaid", "ar": "غير مدفوع", "zh": "未付"},
        "partiallyPaid": {"ku": "بەشێکی پارەدراو", "en": "Partially Paid", "ar": "مدفوع جزئياً", "zh": "部分付款"},
        "overdue": {"ku": "دواکەوتوو", "en": "Overdue", "ar": "متأخر", "zh": "逾期"},
        "printInvoice": {"ku": "چاپکردنی پسوڵە", "en": "Print Invoice", "ar": "طباعة الفاتورة", "zh": "打印发票"},
        "downloadInvoice": {"ku": "داگرتنی پسوڵە", "en": "Download Invoice", "ar": "تحميل الفاتورة", "zh": "下载发票"},
        "sendInvoice": {"ku": "ناردنی پسوڵە", "en": "Send Invoice", "ar": "إرسال الفاتورة", "zh": "发送发票"},
    },
    
    # ============ PRICING ============
    "pricing": {
        "title": {"ku": "نرخەکان", "en": "Pricing", "ar": "الأسعار", "zh": "定价"},
        "pricePerKg": {"ku": "نرخی هەر کیلۆیەک", "en": "Price per KG", "ar": "السعر لكل كغ", "zh": "每公斤价格"},
        "pricePerCbm": {"ku": "نرخی هەر مەتری کیوبی", "en": "Price per CBM", "ar": "السعر لكل متر مكعب", "zh": "每立方米价格"},
        "minimumCharge": {"ku": "کەمترین نرخ", "en": "Minimum Charge", "ar": "الحد الأدنى للرسوم", "zh": "最低收费"},
        "additionalFees": {"ku": "کرێی زیادە", "en": "Additional Fees", "ar": "رسوم إضافية", "zh": "附加费"},
        "customPricing": {"ku": "نرخی تایبەت", "en": "Custom Pricing", "ar": "تسعير مخصص", "zh": "自定义定价"},
        "vipPricing": {"ku": "نرخی VIP", "en": "VIP Pricing", "ar": "تسعير VIP", "zh": "VIP定价"},
        "standardPricing": {"ku": "نرخی ستاندارد", "en": "Standard Pricing", "ar": "التسعير القياسي", "zh": "标准定价"},
        "serviceType": {"ku": "جۆری خزمەتگوزاری", "en": "Service Type", "ar": "نوع الخدمة", "zh": "服务类型"},
    },
    
    # ============ COUNTRIES ============
    "countries": {
        "title": {"ku": "وڵاتەکان", "en": "Countries", "ar": "البلدان", "zh": "国家"},
        "addCountry": {"ku": "زیادکردنی وڵات", "en": "Add Country", "ar": "إضافة بلد", "zh": "添加国家"},
        "countryName": {"ku": "ناوی وڵات", "en": "Country Name", "ar": "اسم البلد", "zh": "国家名称"},
        "countryCode": {"ku": "کۆدی وڵات", "en": "Country Code", "ar": "رمز البلد", "zh": "国家代码"},
        "currency": {"ku": "دراو", "en": "Currency", "ar": "العملة", "zh": "货币"},
        "timezone": {"ku": "ناوچەی کات", "en": "Timezone", "ar": "المنطقة الزمنية", "zh": "时区"},
    },
    
    # ============ SERVICE TYPES ============
    "serviceTypes": {
        "title": {"ku": "جۆرەکانی خزمەتگوزاری", "en": "Service Types", "ar": "أنواع الخدمات", "zh": "服务类型"},
        "addServiceType": {"ku": "زیادکردنی جۆری خزمەتگوزاری", "en": "Add Service Type", "ar": "إضافة نوع خدمة", "zh": "添加服务类型"},
        "serviceName": {"ku": "ناوی خزمەتگوزاری", "en": "Service Name", "ar": "اسم الخدمة", "zh": "服务名称"},
        "serviceCode": {"ku": "کۆدی خزمەتگوزاری", "en": "Service Code", "ar": "رمز الخدمة", "zh": "服务代码"},
        "deliveryTime": {"ku": "کاتی گەیاندن", "en": "Delivery Time", "ar": "وقت التسليم", "zh": "送达时间"},
    },
    
    # ============ AUTH ============
    "auth": {
        "login": {"ku": "چوونەژوورەوە", "en": "Login", "ar": "تسجيل الدخول", "zh": "登录"},
        "logout": {"ku": "چوونەدەرەوە", "en": "Logout", "ar": "تسجيل الخروج", "zh": "退出"},
        "register": {"ku": "تۆمارکردن", "en": "Register", "ar": "التسجيل", "zh": "注册"},
        "forgotPassword": {"ku": "وشەی نهێنیت بیرچووەتەوە؟", "en": "Forgot Password?", "ar": "نسيت كلمة المرور؟", "zh": "忘记密码？"},
        "resetPassword": {"ku": "ڕیسێتکردنی وشەی نهێنی", "en": "Reset Password", "ar": "إعادة تعيين كلمة المرور", "zh": "重置密码"},
        "password": {"ku": "وشەی نهێنی", "en": "Password", "ar": "كلمة المرور", "zh": "密码"},
        "confirmPassword": {"ku": "دڵنیاکردنەوەی وشەی نهێنی", "en": "Confirm Password", "ar": "تأكيد كلمة المرور", "zh": "确认密码"},
        "rememberMe": {"ku": "بمهێڵەرەوە", "en": "Remember Me", "ar": "تذكرني", "zh": "记住我"},
        "loginSuccess": {"ku": "چوونەژوورەوە سەرکەوتوو بوو", "en": "Login successful", "ar": "تم تسجيل الدخول بنجاح", "zh": "登录成功"},
        "logoutSuccess": {"ku": "چوونەدەرەوە سەرکەوتوو بوو", "en": "Logout successful", "ar": "تم تسجيل الخروج بنجاح", "zh": "退出成功"},
        "invalidCredentials": {"ku": "زانیاری هەڵە", "en": "Invalid credentials", "ar": "بيانات غير صحيحة", "zh": "凭据无效"},
        "sessionExpired": {"ku": "دانیشتنەکەت تەواوبووە", "en": "Session expired", "ar": "انتهت الجلسة", "zh": "会话已过期"},
        "staffLogin": {"ku": "چوونەژوورەوەی ستاف", "en": "Staff Login", "ar": "دخول الموظفين", "zh": "员工登录"},
        "customerLogin": {"ku": "چوونەژوورەوەی کڕیار", "en": "Customer Login", "ar": "دخول العملاء", "zh": "客户登录"},
    },
    
    # ============ NAVIGATION ============
    "nav": {
        "home": {"ku": "سەرەکی", "en": "Home", "ar": "الرئيسية", "zh": "首页"},
        "dashboard": {"ku": "داشبۆرد", "en": "Dashboard", "ar": "لوحة التحكم", "zh": "仪表板"},
        "customers": {"ku": "کڕیارەکان", "en": "Customers", "ar": "العملاء", "zh": "客户"},
        "packages": {"ku": "پاکەتەکان", "en": "Packages", "ar": "الطرود", "zh": "包裹"},
        "batches": {"ku": "باچەکان", "en": "Batches", "ar": "الدفعات", "zh": "批次"},
        "finance": {"ku": "دارایی", "en": "Finance", "ar": "المالية", "zh": "财务"},
        "reports": {"ku": "ڕاپۆرتەکان", "en": "Reports", "ar": "التقارير", "zh": "报告"},
        "settings": {"ku": "ڕێکخستنەکان", "en": "Settings", "ar": "الإعدادات", "zh": "设置"},
        "scan": {"ku": "سکان", "en": "Scan", "ar": "مسح", "zh": "扫描"},
        "fullPackage": {"ku": "پاکەتی تەواو", "en": "Full Package", "ar": "الطرد الكامل", "zh": "全包服务"},
        "suppliers": {"ku": "دابینکەرەکان", "en": "Suppliers", "ar": "الموردون", "zh": "供应商"},
        "warehouses": {"ku": "کۆگاکان", "en": "Warehouses", "ar": "المستودعات", "zh": "仓库"},
        "labels": {"ku": "لەیبڵەکان", "en": "Labels", "ar": "الملصقات", "zh": "标签"},
        "invoices": {"ku": "پسوڵەکان", "en": "Invoices", "ar": "الفواتير", "zh": "发票"},
        "pricing": {"ku": "نرخەکان", "en": "Pricing", "ar": "الأسعار", "zh": "定价"},
        "companyFinance": {"ku": "دارایی کۆمپانیا", "en": "Company Finance", "ar": "مالية الشركة", "zh": "公司财务"},
    },
}

def update_locale_files():
    """Update all locale files with comprehensive translations"""
    for lang in ['en', 'ku', 'ar', 'zh']:
        file_path = LOCALES_DIR / f"{lang}.json"
        
        # Read existing
        existing = {}
        if file_path.exists():
            with open(file_path, 'r', encoding='utf-8') as f:
                existing = json.load(f)
        
        # Add all translations
        for section, translations in ALL_TRANSLATIONS.items():
            if section not in existing:
                existing[section] = {}
            
            for key, values in translations.items():
                if key not in existing[section]:
                    existing[section][key] = values.get(lang, values.get('ku', ''))
        
        # Write back
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(existing, f, ensure_ascii=False, indent=2)
            f.write('\n')
        
        print(f"Updated {lang}.json")

if __name__ == "__main__":
    print("Updating all locale files with comprehensive translations...")
    update_locale_files()
    print("\nDone!")
