#!/usr/bin/env node
/**
 * Wazn Express - Round 3 Translation Script
 * 
 * Completes remaining Chinese (zh.json) and Arabic (ar.json) translations.
 * 
 * Approach:
 *   1. Read all 4 locale files (ku as source, en for reference, ar, zh)
 *   2. Flatten to dot-notation keys
 *   3. For keys where ar/zh values still equal Kurdish values:
 *      - Use the English value from en.json as reference
 *      - Apply comprehensive English→Chinese and English→Arabic dictionaries
 *   4. Write updated files and report counts
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const LOCALES_DIR = resolve(__dirname, '../client/src/locales');

// ============================================================
// HELPERS
// ============================================================

function flatten(obj, prefix = '') {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      Object.assign(result, flatten(value, path));
    } else {
      result[path] = value;
    }
  }
  return result;
}

function unflatten(flat) {
  const result = {};
  for (const [path, value] of Object.entries(flat)) {
    const keys = path.split('.');
    let current = result;
    for (let i = 0; i < keys.length - 1; i++) {
      if (!(keys[i] in current)) current[keys[i]] = {};
      current = current[keys[i]];
    }
    current[keys[keys.length - 1]] = value;
  }
  return result;
}

function containsKurdish(text) {
  if (typeof text !== 'string') return false;
  // Kurdish Sorani uses Arabic script with specific characters
  return /[\u0626-\u06CC\u06A9\u06AF\u0695\u0698\u06B5\u06B6\u06C6\u06D5\u06CE\u06BE]/.test(text);
}

// ============================================================
// COMPREHENSIVE English → Chinese DICTIONARY
// ============================================================

const enToZh = {
  // --- Financial / Balance Sheet ---
  "Balance Sheet": "资产负债表",
  "Assets": "资产",
  "Total Assets": "总资产",
  "Liabilities": "负债",
  "Total Liabilities": "负债总额",
  "Liabilities & Equity": "负债和权益",
  "Equity": "权益",
  "Current Assets": "流动资产",
  "Cash": "现金",
  "Bank Account": "银行账户",
  "Bank Accounts": "银行账户",
  "Customer Debts": "客户债务",
  "Customer Debt": "客户债务",
  "Packages in Transit": "运输中的包裹",
  "Supplier Debts": "供应商债务",
  "Unpaid Expenses": "未付费用",
  "Bank Debt": "银行债务",
  "Owners' Equity": "所有者权益",
  "Capital Structure": "资本结构",
  "Initial Capital": "初始资本",
  "Revenue": "收入",
  "Total Revenue": "总收入",
  "Total Income": "总收入",
  "Expenses": "支出",
  "Expense": "支出",
  "Total Expenses": "总支出",
  "Profit": "利润",
  "Net Profit": "净利润",
  "Net Loss": "净亏损",
  "Loss": "亏损",
  "Gross Profit": "毛利润",
  "Total Cost": "总成本",
  "Total Profit": "总利润",
  "Total Debt": "总债务",
  "Total Balance": "总余额",
  "Total": "总计",
  "Total Cash": "现金总额",
  "Income": "收入",
  "Income Increase": "收入增加",
  "Income Decrease": "收入减少",
  "Expenditures": "支出",
  "Total Expenditures": "总支出",
  "Accumulated Profit": "累计利润",
  "Retained Profit": "留存利润",
  "Retained Balance": "留存余额",
  "Profit Share": "利润分成",
  "Profit Rate": "利润率",
  "Profit Margin": "利润率",
  "Total Capital": "总资本",
  "Financial Ratios": "财务比率",
  "Current Ratio": "流动比率",
  "Debt Ratio": "债务比率",
  "Equity Ratio": "权益比率",
  "Working Capital": "营运资本",
  "Capital": "资本",
  "Withdrawal": "提款",
  "Debt to Company": "对公司的债务",
  "Debt Repayment": "偿还债务",
  "Adjustment": "调整",
  "Debit Adjustment": "借方调整",
  "Credit Adjustment": "贷方调整",
  "Other Debit": "其他借方",
  "Other Credit": "其他贷方",
  "Cash Flow": "现金流",
  "Cash Flow Report\n\n": "现金流报告\n\n",
  "Net Cash Flow": "净现金流",
  "Total Inflow": "总流入",
  "Total Outflow": "总流出",
  "Inflow": "流入",
  "Outflow": "流出",
  "Negative": "负数",
  "Positive": "正数",
  "Current Cash": "当前现金",
  "Cash Box": "现金箱",
  "Cash Accounts": "现金账户",
  "Main Cash": "主要现金",
  "Bank Card": "银行卡",
  "Main Bank Account": "主银行账户",
  "FIB Account": "FIB账户",
  "Kurdistan Bank": "库尔德斯坦银行",
  "Mobile Wallet": "手机钱包",
  "Transfer": "转账",
  "Transfer (In)": "转入",
  "Transfer (Out)": "转出",
  "Bank Transfer": "银行转账",
  "Deposit": "存款",
  "Account": "账户",
  "Account Name": "账户名称",
  "Account Number": "账号",
  "Transaction": "交易",
  "Balance": "余额",
  "Balance Sheet\n": "资产负债表\n",
  "Assets\n": "资产\n",
  "Liabilities\n": "负债\n",
  "Equity\n": "权益\n",
  "\nExpenses\n": "\n支出\n",
  "Revenue\n": "收入\n",
  "Profit & Loss Report\n\n": "盈亏报告\n\n",
  "Profit & Loss Statement": "盈亏报表",
  "Profit & Loss Report": "盈亏报告",

  // --- Monthly / Time ---
  "Monthly": "每月",
  "Daily": "每日",
  "Weekly": "每周",
  "Quarterly": "季度",
  "Yearly": "每年",
  "January": "一月",
  "February": "二月",
  "March": "三月",
  "April": "四月",
  "May": "五月",
  "June": "六月",
  "July": "七月",
  "August": "八月",
  "September": "九月",
  "October": "十月",
  "November": "十一月",
  "December": "十二月",
  "Today": "今天",
  "Yesterday": "昨天",
  "Tomorrow": "明天",
  "This Week": "本周",
  "Last Week": "上周",
  "This Month": "本月",
  "Last Month": "上月",
  "This Year": "今年",
  "Last Year": "去年",
  "All Time": "所有时间",
  "Last 3 Months": "最近3个月",
  "Period": "期间",

  // --- Payment / Invoice ---
  "Payment": "付款",
  "Payments": "付款",
  "Total Payments": "总付款",
  "Payment Method": "付款方式",
  "Payment Status": "付款状态",
  "Customer Payment": "客户付款",
  "Record Payment": "记录付款",
  "Record Customer Payment": "记录客户付款",
  "Paid": "已付款",
  "Unpaid": "未支付",
  "Invoice": "发票",
  "Invoices": "发票",
  "Invoice Style": "发票样式",
  "Invoice Template Settings": "发票模板设置",
  "Invoice Number Prefix": "发票号前缀",
  "Full Package Payment": "全套服务付款",

  // --- Customer ---
  "Customer": "客户",
  "Customers": "客户",
  "customers": "客户",
  "Total Customers": "总客户",
  "Customer Income": "客户收入",
  "Customer Name": "客户名称",
  "Customer Login": "客户登录",
  "Customer Pricing": "客户定价",
  "Customer-Specific Pricing": "客户专属定价",
  "Customer Report": "客户报告",
  "customers selected": "已选客户",
  "Selected Customers": "已选客户",

  // --- Package ---
  "Package": "包裹",
  "Packages": "包裹",
  "Total Packages": "总包裹",
  "Package Price": "包裹价格",
  "Package Number": "包裹数量",
  "Package Delivery": "包裹配送",
  "Selected Packages": "已选包裹",
  "Full Package": "全套服务",
  "Full Package Sale": "全套服务销售",
  "Full Package Commission": "全套服务佣金",
  "Full Package Profit": "全套服务利润",
  "Full Package Report": "全包报告",

  // --- Batch ---
  "Batch": "批次",
  "Batches": "批次",
  "Total Batches": "总批次",
  "Select Batch": "选择批次",
  "In Batch": "在批次中",
  "No Batch": "无批次",
  "Selected Batch": "已选批次",
  "Group/Batch": "批量",

  // --- Warehouse / Shipping ---
  "Warehouse": "仓库",
  "Delivery": "配送",
  "Shipping": "运输",
  "Shipping Type": "运输类型",
  "Shipping Fee": "运费",
  "Air": "空运",
  "Air Regular": "普通空运",
  "Air Irregular": "特殊空运",
  "Sea": "海运",
  "In Transit": "运输中",
  "In China Warehouse": "在中国仓库",
  "In Batch": "在批次中",
  "Delivered": "已交付",
  "Arrived": "已到达",
  "Arrived in China": "到达中国",
  "Arrived in Kurdistan": "到达库尔德斯坦",
  "Received Locally": "已到达本地",
  "Received": "已接收",
  "Received in China": "在中国已接收",
  "Registered": "已登记",
  "Sent": "已发送",
  "Returned": "已退回",
  "Out for Delivery": "派送中",
  "Ready for Delivery": "待配送",
  "Delivery Confirmation": "配送确认",
  "Customs Hold": "海关扣留",
  "Receive from China": "从中国接收",
  "Ship to Iraq": "运往伊拉克",
  "Deliver to customer": "交付给客户",
  "Recipient Name": "收件人姓名",
  "Recipient name...": "收件人姓名...",
  "Destination City": "目的城市",
  "Operations Center": "运营中心",
  "Air and sea cargo shipping to Iraq": "空运和海运到伊拉克",

  // --- Supplier ---
  "Supplier": "供应商",
  "Suppliers": "供应商",
  "Total Suppliers": "总供应商",
  "New Supplier": "新供应商",
  "Edit Supplier": "编辑供应商",
  "Supplier Name": "供应商名称",
  "Wholesaler": "批发商",

  // --- Staff / User ---
  "User": "用户",
  "Users": "用户",
  "Staff": "员工",
  "Staff Login": "员工登录",
  "Admin": "管理员",
  "Manager": "经理",
  "Agent": "代理",
  "Employee": "员工",
  "Employee Salaries": "员工工资",
  "Salary": "工资",
  "Username": "用户名",
  "Password": "密码",
  "Login": "登录",
  "Logging in...": "登录中...",
  "Login failed": "登录失败",

  // --- Common UI ---
  "Delete": "删除",
  "Edit": "编辑",
  "Add": "添加",
  "Save": "保存",
  "Cancel": "取消",
  "Search": "搜索",
  "Filter": "筛选",
  "Export": "导出",
  "Import": "导入",
  "Backup": "备份",
  "Restore": "恢复",
  "Settings": "设置",
  "Report": "报告",
  "Reports": "报告",
  "Dashboard": "仪表板",
  "Date": "日期",
  "Name": "名称",
  "Code": "代码",
  "Type": "类型",
  "Amount": "金额",
  "Amount (USD": "金额（美元",
  "Actions": "操作",
  "Details": "详情",
  "Description": "描述",
  "Notes": "备注",
  "Created": "创建",
  "Updated": "更新",
  "Deleted": "已删除",
  "Scan": "扫描",
  "Scans": "扫描",
  "Scanning": "扫描",
  "Register": "登记",
  "Registration": "登记",
  "Tracking": "追踪",
  "Tracking Number": "追踪号",
  "Tracking Alert": "追踪提醒",
  "Tracking Alerts": "追踪提醒",
  "Tracking number...": "追踪号...",
  "Tracking Added": "已添加追踪",
  "Track": "追踪",
  "Status": "状态",
  "Active": "活跃",
  "Inactive": "不活跃",
  "Enabled": "已启用",
  "Disabled": "已禁用",
  "Pending": "待处理",
  "Completed": "已完成",
  "completed": "已完成",
  "Failed": "失败",
  "Cancelled": "已取消",
  "Approved": "已批准",
  "Loading": "加载中",
  "Loading...": "加载中...",
  "Saving...": "保存中...",
  "Creating...": "创建中...",
  "Printing": "打印中",
  "Sending...": "发送中...",
  "Uploading...": "上传中...",
  "No Data": "暂无数据",
  "No Results Found": "未找到结果",
  "Success": "成功",
  "Error": "错误",
  "Error:": "错误：",
  "Warning": "警告",
  "Info": "信息",
  "Alert": "警报",
  "Close": "关闭",
  "Open": "打开",
  "Confirm": "确认",
  "Select": "选择",
  "Select All": "全选",
  "Deselect All": "取消全选",
  "Required": "必填",
  "Optional": "可选",
  "Yes": "是",
  "No": "否",
  "All": "全部",
  "None": "无",
  "New": "新",
  "Old": "旧",
  "Enable": "启用",
  "Disable": "禁用",
  "Download": "下载",
  "Upload": "上传",
  "Print": "打印",
  "Print Label": "打印标签",
  "Copy": "复制",
  "Paste": "粘贴",
  "View": "查看",
  "More": "更多",
  "more": "更多",
  "Less": "更少",
  "Show More": "查看更多",
  "Show Less": "收起",
  "Back": "返回",
  "Next": "下一步",
  "Previous": "上一步",
  "Send": "发送",
  "Reset": "重置",
  "Clear": "清除",
  "Refresh": "刷新",
  "From": "从",
  "To": "到",
  "Between": "之间",
  "And": "和",
  "Or": "或",
  "Custom": "自定义",
  "Default": "默认",
  "Ascending": "升序",
  "Descending": "降序",
  "Sort By": "排序",
  "Sort Order": "排序",
  "Filter By": "筛选",
  "Group By": "分组",
  "Per Page": "每页",
  "Page": "页",
  "Items": "项",
  "Showing": "显示",
  "Results": "结果",
  "Found": "已找到",
  "Not Found": "未找到",
  "Coming Soon": "即将推出",
  "Under Construction": "建设中",
  "Beta": "测试版",
  "Price": "价格",
  "Number": "数量",
  "Weight": "重量",
  "Weight (KG)": "重量（公斤）",
  "Weight (kg)": "重量（公斤）",
  "Volume": "体积",
  "Height": "高度",
  "Width": "宽度",
  "Length": "长度",
  "Time": "时间",
  "Start Date": "开始日期",
  "End Date": "结束日期",
  "Remaining": "剩余",
  "Progress": "进度",
  "Current": "当前",
  "Current:": "当前：",
  "Goal:": "目标：",
  "Goal": "目标",
  "Target": "目标",
  " days": "天",
  " days overdue": "天逾期",
  " records": "条记录",
  "records": "条记录",
  "of total": "占总数",
  "rate": "比率",
  "from last month": "较上月",
  "Logout": "退出",
  "Profile": "个人资料",
  "Management": "管理",
  "Auto Refresh": "自动刷新",
  "New Request": "新请求",
  "Distributed": "已分配",
  "Are you sure": "确定吗",
  "Are you sure you want to delete": "确定要删除吗",
  "What are you doing today?": "今天做什么？",
  "What are you doing today": "今天做什么",
  "How can I help you": "我能帮你什么",
  "Fast & Reliable Shipping": "快速可靠的运输",
  "All rights reserved": "版权所有",
  "Wazn Express": "Wazn Express",
  "Product Link": "产品链接",

  // --- Service ---
  "Service": "服务",
  "Services": "服务",
  "Service Types": "服务类型",
  "Service Fee": "服务费",
  "Service Profit": "服务利润",
  "Service Profit Report": "服务利润报告",
  "Extra Services": "额外服务",
  "Icon": "图标",
  "Order/Rank": "排序",
  "Cost": "费用",
  "Total Cost": "总费用",
  "Default Cost ($)": "默认费用（$）",
  "Default Price ($)": "默认价格（$）",
  "Default Price": "默认价格",

  // --- Reports ---
  "Financial Reports": "财务报告",
  "Financial Report": "财务报告",
  "Financial Goal": "财务目标",
  "Monthly Report": "月报",
  "Weekly Report": "周报",
  "Daily Report": "日报",
  "Monthly Trend": "月度趋势",
  "Balance Sheet PDF created": "资产负债表PDF已创建",
  "Debt table PDF created": "债务表PDF已创建",
  "PDF report created": "PDF报告已创建",
  "Batch report downloaded": "批次报告已下载",
  "Partner report PDF created": "合伙人报告PDF已创建",
  "Expenses report PDF created": "支出报告PDF已创建",
  "Error creating PDF": "创建PDF出错",
  "Image loading error:": "图片加载错误：",
  "Financial stats for": "财务统计",
  "Income and expense stats for": "收支统计",

  // --- Order Center ---
  "Order": "订单",
  "Order Center": "订单中心",
  "Order Code": "订单代码",
  "Order Number": "订单号",
  "Order Date": "订单日期",
  "Order Placed": "已下单",
  "Ordered": "已下单",
  "Edit Order": "编辑订单",
  "Total Orders": "订单总数",
  "Total Purchases": "采购总额",
  "Total Sales": "销售总额",
  "Purchase": "采购",
  "Resale": "转售",
  "Returns": "退回",
  "Return Rate": "退货率",
  "Return/Refund": "退回/退款",
  "By Supplier": "按供应商",
  "By Customer": "按客户",
  "Delivery Time": "配送时间",
  "Average Days": "平均天数",
  "Minimum": "最小",
  "Maximum": "最大",
  "On Time": "准时",
  "Late": "迟到",
  "Delivery Day": "配送日",
  "Goods": "商品",
  "Reason": "原因",
  "Action": "操作",
  "Pending Orders": "待处理订单",
  "Without order number": "无订单号",
  "Orders without tracking": "无追踪的订单",
  "With Tracking": "有追踪",
  "Without Tracking": "无追踪",
  "Add Tracking Number": "添加追踪号",
  "Enter tracking number...": "输入追踪号...",
  "Tracking number added": "追踪号已添加",
  "Please enter tracking number": "请输入追踪号",

  // --- Scanning ---
  "Scan Dashboard": "扫描仪表板",
  "Scan to start...": "扫描开始...",
  "Scan to start": "扫描开始",
  "Scan or type...": "扫描或输入...",
  "Continuous Scan": "连续扫描",
  "Camera Scan": "相机扫描",
  "Camera": "相机",
  "Last scan deleted": "最后一次扫描已删除",
  "Hardware scanner or typing supported": "支持硬件扫描仪或键入",
  "Recent Scans": "最近扫描",
  "Latest Scans": "最新扫描",
  "Today's Scans": "今日扫描",
  "Quick Actions": "快速操作",
  "Quick Register": "快速登记",
  "Scan Type": "扫描类型",
  "Scan List": "扫描列表",
  "Scan Report - Wazn Express": "扫描报告 - Wazn Express",
  "Wazn Express - Shipping Management System": "Wazn Express - 运输管理系统",
  "Place barcode inside the frame": "将条码放入框内",
  "Could not open camera": "无法打开相机",

  // --- Blog ---
  "Published": "已发布",
  "Archive": "归档",
  "News": "新闻",
  "Announcement": "公告",
  "Guide": "指南",

  // --- Goals ---
  "Financial Goal": "财务目标",
  "Goal Name": "目标名称",
  "Goal Type": "目标类型",
  "Goal History": "目标历史",
  "Create New Goal": "创建新目标",
  "No active goals": "没有活跃目标",
  "Goal created": "目标已创建",
  "Goal cancelled": "目标已取消",

  // --- Debtors ---
  "Debtors": "债务人",
  "Debtors Report": "债务人报告",
  "Debtors List": "债务人列表",
  "Debt Age": "债务年龄",
  "Debt Collection": "债务催收",
  "Send Reminder": "发送提醒",
  "Send Debt Reminder": "发送债务提醒",

  // --- Template ---
  "Template": "模板",
  "Templates": "模板",
  "Template Name": "模板名称",
  "Template Settings": "模板设置",
  "New Template": "新模板",
  "Create New Template": "创建新模板",
  "Edit Template": "编辑模板",
  "Default Template": "默认模板",
  "Custom Size": "自定义尺寸",

  // --- Misc ---
  "Company": "公司",
  "Logo": "标志",
  "Website": "网站",
  "Email": "邮箱",
  "Name or Email": "姓名或邮箱",
  "Discount": "折扣",
  "Penalty": "罚款",
  "Rent": "租金",
  "Card": "卡",
  "Activation": "激活",
  "Normal": "普通",
  "High": "高",
  "Low": "低",
  "Unknown": "未知",
  "Other": "其他",
  "Other Expenses": "其他支出",
  "Personal": "个人",
  "Shopkeeper": "店主",
  "Foreign": "外国",
  "Emergency": "紧急",
  "Irregular": "不规则",
  "Unclaimed": "无人认领",
  "No Customer": "无客户",
  "General": "通用",
  "Content": "内容",
  "Left": "左",
  "Center": "居中",
  "Right": "右",
  "Top Left": "左上",
  "Top Right": "右上",
  "Bottom Left": "左下",
  "Bottom Right": "右下",
  "Label Size": "标签大小",
  "(Default)": "（默认）",
  "(Dollar)": "（美元）",
  "(Number)": "（数字）",
  "+ Name": "+ 名称",
  "+ Number": "+ 号码",
  "Assyrian": "亚述",
  "Armenian": "亚美尼亚",
  "Turkmen": "土库曼",
  "Kurdish": "库尔德",
  "Arab": "阿拉伯",
  "Ahmed Mohammed": "艾哈迈德·穆罕默德",
  "Sulaymaniyah": "苏莱曼尼亚",
  "Online Page": "在线页面",
  "Date,Inflow,Outflow,Net\n": "日期,流入,流出,净值\n",
  "Skip": "跳过",
  "Calculate": "计算",
  "Added to Batch": "已加入批次",
  "Manual Entry": "手动输入",
  "Fill in information": "填写信息",
  "Waiting for...": "等待中...",
  "Wait...": "等待...",
  "Expense Limit": "支出限额",
  "No batches available": "没有可用批次",
  "Data imported successfully": "数据导入成功",
  "Data deleted successfully": "数据删除成功",
  "Data updated successfully": "数据更新成功",
  "Data saved successfully": "数据保存成功",
  "missing info": "缺少信息",
  "Special Pricing": "特殊定价",
  "Select batch (optional)": "选择批次（可选）",
  "Select batch...": "选择批次...",
  "Select platform...": "选择平台...",
  "May revenue goal": "五月收入目标",
  "May's Revenue": "五月收入",
  "e.g., Clothes": "例如：服装",
  "e.g., Clothing": "例如：服装",
  "Example: Send RMB": "示例：发送人民币",
  "Management System": "管理系统",
  "Total Suppliers": "总供应商",
  "Evaluation Center": "评估中心",
  "All Platforms": "所有平台",
  "No suppliers": "没有供应商",
  "Platform": "平台",
  "Contact": "联系",
  "Evaluation": "评估",
  "Basic Information": "基本信息",
  "Name (English) *": "名称（英文）*",
  "Name (Arabic/Kurdish)": "名称（阿拉伯语/库尔德语）",
  "Name (Chinese)": "名称（中文）",
  "Contact Information": "联系信息",
  "Contact Person Name": "联系人姓名",
  "Are you sure you want to delete?": "确定要删除吗？",
  "Search by name, contact, WeChat...": "按名称、联系方式、微信搜索...",
  "Supplier address in China": "供应商在中国的地址",
  "Note about supplier...": "关于供应商的备注...",
  "Supplier added successfully": "供应商添加成功",
  "Supplier updated successfully": "供应商更新成功",
  "Supplier deleted": "供应商已删除",
  "Please enter supplier name": "请输入供应商名称",
  "Needs immediate resolution": "需要立即解决",
  "Needs Immediate Attention": "需要立即处理",
  "Needs urgent resolution": "需要紧急解决",
  "Needs Quick Resolution": "需要快速解决",
  "Needs attention": "需要关注",
  "Needs Attention": "需要关注",
  "Needs Resolution": "需要处理",
  "Package registered in system": "包裹已在系统登记",
  "Package arrived at warehouse": "包裹到达仓库",
  "Package shipped to destination": "包裹已发往目的地",
  "Package arrived at final destination": "包裹到达最终目的地",
  "Package delivered to customer": "包裹已交付客户",
  "Register new package in system": "在系统中登记新包裹",
  "Receive package from China": "从中国接收包裹",
  "Ship package to Erbil": "将包裹运往埃尔比勒",
  "Package arrived in Erbil": "包裹到达埃尔比勒",
  "Deliver package to customer": "将包裹交付客户",
  "Package registered without owner": "无主包裹已登记",
  "Package not found": "未找到包裹",
  "No Packages Found": "未找到包裹",
  "Customer Number": "客户数量",
  "When batch is shipped from China": "批次从中国发货时",
  "When batch arrives in Kurdistan": "批次到达库尔德斯坦时",
  "When package arrives at China warehouse": "包裹到达中国仓库时",
  "When customer receives package": "客户收到包裹时",
  "Ledger Records": "账本记录",
  "scans": "扫描",
  "views": "浏览",
  "profit": "利润",
  "Daily and monthly scan reports": "每日和每月扫描报告",
  "From date": "从日期",
  "To date": "到日期",
  "All scans list for specified period": "指定期间所有扫描列表",
  "Change date range or filter": "更改日期范围或筛选",
  "Report period:": "报告期间：",
  "Scans by employee": "按员工扫描",
  "Tracking and statistics for all scans": "所有扫描的追踪和统计",
  "History of all scans by scan type": "按扫描类型的所有扫描历史",
  "No scans found": "未找到扫描",
  "Enter a tracking number or change filter": "输入追踪号或更改筛选",
  "Search by tracking number...": "按追踪号搜索...",
  "📊 Scan Report": "📊 扫描报告",
  "Reach 100 packages": "达到100个包裹",
  "⚠ Balance is incorrect": "⚠ 资产负债不平衡",
  "✓ Balance is correct": "✓ 资产负债平衡",
  "Customer required": "需要客户",
  "Customer Required": "需要客户",
  "Add to customer balance": "添加到客户余额",
  "Add to Balance": "添加到余额",
  "No service types": "没有服务类型",
  "Create service types": "创建服务类型",
  "Edit Service Type": "编辑服务类型",
  "Update service type info": "更新服务类型信息",
  "Add Type": "添加类型",
  "Add Service Type": "添加服务类型",
  "Create a new extra service type": "创建新的额外服务类型",
  "This icon will appear": "此图标将显示",
  "English Name *": "英文名 *",
  "Kurdish Name": "库尔德语名称",
  "Arabic Name": "阿拉伯语名",
  "Service type created": "服务类型已创建",
  "Manage extra service types": "管理额外服务类型",
  "All Types": "所有类型",
  "Service Profit Report - Profit and cost analysis for services": "服务利润报告 - 服务利润和成本分析",
  "Edit supplier information": "编辑供应商信息",
  "Enter new supplier information": "输入新供应商信息",
  "Are you sure you want to delete this blog?": "确定要删除此博客吗？",
  "Are you sure you want to delete this service type?": "确定要删除此服务类型吗？",
  "Delete all batch records and price levels": "删除所有批次记录和价格等级",
  "Delete all expense records": "删除所有支出记录",
  "Delete all supplier records": "删除所有供应商记录",
  "Delete all invoice records": "删除所有发票记录",
  "Delete all ledger records and transactions": "删除所有账本记录和交易",
  "Delete all payment records and reminders": "删除所有付款记录和提醒",
  "Delete all package records and tracking history": "删除所有包裹记录和追踪历史",
  "Delete all customer records and related data": "删除所有客户记录及相关数据",
  "Delete all Full Package requests and status history": "删除所有全套服务请求和状态历史",
  "Please enter username and password": "请输入用户名和密码",
  "Search by code, name, or number...": "按代码、名称或号码搜索...",
  "Price not set - must pass through Arrive": "价格未设定 - 需通过到达流程",
  "Package Payment #PKG-1234": "包裹付款 #PKG-1234",
  "Package Payment #PKG-1235": "包裹付款 #PKG-1235",
  "Full Package #FP-567": "全套服务 #FP-567",
  "Generated at": "生成于",
  "Total Transfers": "总转账",
  "Partner": "合伙人",
  "Total Revenue": "总收入",
  "Total Expenses": "总支出",
  "Total Profit": "总利润",
  "Total Debt": "总债务",
  "Total Balance": "总余额",
  "Total Packages": "总包裹",
  "Total Customers": "总客户",
  "Total Suppliers": "总供应商",
  "Total Batches": "总批次",
  "Total Payments": "总付款",
  "USD": "美元",
  "Expense Limit": "支出限额",
  "No Packages Found": "未找到包裹",
  "Tracking Alert": "追踪提醒",

  // Extra auto section specific  
  "Full Package requests": "全套服务请求",
  "Irregular": "不规则",
  "Selected": "已选",
  "Difference": "差额",
  "General Price": "通用价格",
  "Special Price List": "特殊价格列表",
  "Special Customer": "特殊客户",
  "Special Batch": "特殊批次",
  "All Customers": "所有客户",
  "Preview": "预览",
  "Load": "货物",
  "No templates": "没有模板",
  "Primary Color": "主色",
  "Secondary Color": "辅色",
  "Accent Color": "强调色",
  "Text Color": "文字颜色",
  "Font": "字体",
  "Font Size": "字号",
  "Modern": "现代",
  "Classic": "经典",
  "Minimal": "简约",
  "Template Style": "模板样式",
  "Batch Number": "批次号",
  "All Batches": "所有批次",
  "No Packages Found": "未找到包裹",
  "Selected Batch": "已选批次",
  "Company Finance Dashboard": "公司财务仪表板",

  // --- Round 3 additions: errors ---
  "Minimum value is {{min}}": "最小值为{{min}}",
  "Maximum value is {{max}}": "最大值为{{max}}",
  "Password is too weak": "密码太弱",
  "Invalid format": "格式无效",
  "Invalid date": "日期无效",
  "Invalid number": "数字无效",
  "This entry already exists": "此条目已存在",
  "Forbidden": "禁止访问",
  "Request timeout": "请求超时",
  "Please try again": "请重试",
  "Contact support": "联系客服",
  "File is too large": "文件太大",
  "Invalid file type": "文件类型无效",
  "Upload failed": "上传失败",
  "Download failed": "下载失败",
  "Delete failed": "删除失败",
  "Save failed": "保存失败",
  "Load failed": "加载失败",

  // --- Claim ---
  "Claim Package": "认领包裹",
  "Submit a claim for this package": "提交此包裹的认领申请",
  "Submit Claim": "提交认领",
  "Your claim requests will appear here": "您的认领请求将显示在此处",
  "Claim request sent successfully": "认领请求发送成功",

  // --- Units / Common ---
  "Menu": "菜单",
  "KG": "公斤",
  "LB": "磅",
  "CM": "厘米",
  "Inch": "英寸",
  "Dollar": "美元",
  "Dinar": "第纳尔",
  "Yuan": "人民币",
  "Percent": "百分比",
  "Days": "天",
  "Hours": "小时",
  "Minutes": "分钟",
  "Seconds": "秒",
  "ago": "前",
  "In Progress": "进行中",
  "Rejected": "已拒绝",
  "Confirmed": "已确认",
  "Unconfirmed": "未确认",
  "Filters": "筛选条件",
  "Export Excel": "导出Excel",
  "To Date": "截止日期",
  "Advanced Filters": "高级筛选",
  "Clear Filters": "清除筛选",
  "No file selected": "未选择文件",
  "Processing...": "处理中...",

  // --- Nav / Sections ---
  "Advanced Scanner": "高级扫描仪",
  "Warehouse Operations": "仓库操作",
  "Smart Scanner": "智能扫描仪",
  "AI Scanner": "AI扫描仪",
  "Company Dashboard": "公司仪表板",
  "Debt Reminders": "债务提醒",
  "Financial Goals": "财务目标",
  "Reports Overview": "报告概览",
  "Profit Dashboard": "利润仪表板",
  "VIP Customers": "VIP客户",
  "Product Categories": "产品分类",
  "Label Templates": "标签模板",
  "Data Management": "数据管理",
  "Warehouses": "仓库",
  "Countries": "国家",
  "Currencies": "货币",
  "Shipping Types": "运输类型",
  "Audit Logs": "审计日志",
  "Mobile Scanner": "移动扫描仪",
  "Pricing": "定价",

  // --- Dashboard ---
  "Registered Today": "今日登记",
  "In Last 7 Days": "最近7天",
  "On Route or Preparing": "在途或准备中",
  "Delivery Rate": "配送率",
  "Income Chart": "收入图表",
  "30 Days": "30天",
  "No data yet": "暂无数据",
  "Recent Activities": "最近活动",
  "New package registered": "新包裹已登记",
  "New customer": "新客户",
  "Common Tasks": "常用任务",
  "Top Debtors": "主要债务人",
  "No debtors!": "没有债务人！",
  "No debtors": "没有债务人",
  "No active batches": "没有活跃批次",
  "Top Customers": "主要客户",
  "No customer data yet": "暂无客户数据",
  "Package Status": "包裹状态",
  "Unclaimed Packages": "无人认领包裹",
  "unclaimed packages": "无人认领包裹",
  "Full Package Requests": "全套服务请求",
  "pending requests": "待处理请求",
  "Download App": "下载应用",
  "Download Wazn Express as an app for better experience": "下载Wazn Express应用获得更好体验",

  // --- Customer Management ---
  "Manage customers and their information": "管理客户及其信息",
  "Delete Customer": "删除客户",
  "Customer Code": "客户编号",
  "Secondary Phone": "备用电话",
  "Country": "国家",
  "Total Spent": "总消费",
  "Last Activity": "最近活动",
  "Package History": "包裹历史",
  "Financial Summary": "财务摘要",
  "Tags": "标签",
  "Blocked": "已封锁",
  "Search customers...": "搜索客户...",
  "Filter by Status": "按状态筛选",
  "Filter by City": "按城市筛选",
  "Export Customers": "导出客户",
  "Import Customers": "导入客户",
  "Customer created": "客户已创建",
  "Customer updated": "客户已更新",
  "Customer deleted": "客户已删除",
  "Are you sure you want to delete this customer?": "确定要删除此客户吗？",
  "No customers": "没有客户",
  "Add your first customer": "添加您的第一个客户",
  "Total Credit": "总信用额",
  "Registration Date": "注册日期",
  "Source": "来源",
  "Referred By": "推荐人",
  "Discount Percent": "折扣百分比",
  "Price per Kg": "每公斤价格",
  "Use Default Pricing": "使用默认定价",
  "Send Message": "发送消息",
  "View Packages": "查看包裹",
  "View Payments": "查看付款",
  "View Invoices": "查看发票",
  "Generate Invoice": "生成发票",

  // --- Full Package ---
  "Manage full package orders": "管理全套服务订单",
  "Full Package Dashboard": "全套服务仪表板",
  "Orders": "订单",
  "Delete Order": "删除订单",
  "Actual Delivery": "实际交付",
  "Color": "颜色",
  "Internal Notes": "内部备注",
  "Customer Notes": "客户备注",
  "Avg Order Value": "平均订单金额",
  "Completed Orders": "已完成订单",
  "Search orders...": "搜索订单...",
  "Filter by Supplier": "按供应商筛选",
  "Filter by Customer": "按客户筛选",
  "Order created": "订单已创建",
  "Order updated": "订单已更新",
  "Order deleted": "订单已删除",
  "Are you sure you want to delete this order?": "确定要删除此订单吗？",
  "No orders": "没有订单",
  "Add your first order": "添加您的第一个订单",
  "Order Details": "订单详情",
  "Timeline": "时间线",
  "Status History": "状态历史",
  "Update Status": "更新状态",
  "Add Tracking": "添加追踪",
  "View Product": "查看产品",
  "Copy Link": "复制链接",
  "Open in New Tab": "在新标签页打开",
  "Supplier Report": "供应商报告",
  "Profit Report": "利润报告",
  "1688": "1688",

  // --- Supplier Management ---
  "Manage suppliers and their information": "管理供应商及其信息",
  "Delete Supplier": "删除供应商",
  "Supplier Code": "供应商编号",
  "Phone Number": "电话号码",
  "WeChat": "微信",
  "WhatsApp": "WhatsApp",
  "Avg Delivery Time": "平均配送时间",
  "Success Rate": "成功率",
  "Search suppliers...": "搜索供应商...",
  "Filter by Platform": "按平台筛选",
  "Filter by Rating": "按评分筛选",
  "Supplier created": "供应商已创建",
  "Supplier updated": "供应商已更新",
  "Are you sure you want to delete this supplier?": "确定要删除此供应商吗？",
  "Add your first supplier": "添加您的第一个供应商",
  "Supplier Details": "供应商详情",
  "Order History": "订单历史",
  "Performance": "绩效",
  "Taobao": "淘宝",
  "Alibaba": "阿里巴巴",
  "Pinduoduo": "拼多多",
  "0-3 days": "0-3天",
  "Normal waiting": "正常等待",
  "No alerts": "无警报",
  "All orders have tracking numbers": "所有订单都有追踪号",

  // --- Package Management ---
  "Manage all packages": "管理所有包裹",
  "Package Dashboard": "包裹仪表板",
  "All Packages": "所有包裹",
  "Bulk Register": "批量登记",
  "Edit Package": "编辑包裹",
  "Delete Package": "删除包裹",
  "Actual Weight": "实际重量",
  "Volumetric Weight": "体积重量",
  "Chargeable Weight": "计费重量",
  "In Warehouse": "在仓库",
  "Lost": "丢失",
  "Damaged": "损坏",
  "Total Price": "总价格",
  "Partially Paid": "部分付款",
  "Arrival Date": "到达日期",
  "Delivery Date": "配送日期",
  "Search packages...": "搜索包裹...",
  "Filter by Batch": "按批次筛选",
  "Filter by Shipping Type": "按运输类型筛选",
  "Package registered": "包裹已登记",
  "Package updated": "包裹已更新",
  "Package deleted": "包裹已删除",
  "Are you sure you want to delete this package?": "确定要删除此包裹吗？",
  "No packages": "没有包裹",
  "Register your first package": "登记您的第一个包裹",
  "Package Details": "包裹详情",
  "Add to Batch": "添加到批次",
  "Remove from Batch": "从批次移除",
  "Mark as Delivered": "标记为已交付",
  "Mark as Paid": "标记为已付款",
  "Total Weight": "总重量",
  "Total Value": "总价值",
  "Avg Weight": "平均重量",
  "Scan to register": "扫描以登记",
  "Enter tracking number": "输入追踪号",
  "Scan another": "扫描下一个",
  "Continuous Mode": "连续模式",
  "Single Mode": "单个模式",
  "Bulk Upload": "批量上传",
  "Download Template": "下载模板",
  "Upload File": "上传文件",
  "Import Packages": "导入包裹",
  "Successfully imported": "导入成功",
  "Failed to import": "导入失败",
  "Duplicate tracking": "重复追踪号",
  "Invalid data": "数据无效",

  // --- Batch Management ---
  "Manage shipping batches": "管理运输批次",
  "Edit Batch": "编辑批次",
  "Delete Batch": "删除批次",
  "Batch Name": "批次名称",
  "Expected Arrival": "预计到达",
  "Actual Arrival": "实际到达",
  "Preparing": "准备中",
  "Departed": "已出发",
  "Origin": "始发地",
  "Destination": "目的地",
  "Search batches...": "搜索批次...",
  "Filter by Carrier": "按承运人筛选",
  "Batch created": "批次已创建",
  "Batch updated": "批次已更新",
  "Batch deleted": "批次已删除",
  "Are you sure you want to delete this batch?": "确定要删除此批次吗？",
  "Create your first batch": "创建您的第一个批次",
  "Batch Details": "批次详情",
  "Add Packages": "添加包裹",
  "Remove Packages": "移除包裹",
  "Mark as Departed": "标记为已出发",
  "Mark as Arrived": "标记为已到达",
  "Print Manifest": "打印清单",
  "Export Batch": "导出批次",
  "Shipping Cost": "运输费用",
  "Scan packages": "扫描包裹",

  // --- Scan ---
  "Scan Reports": "扫描报告",
  "Scan Package": "扫描包裹",
  "Scan Barcode": "扫描条码",
  "Scan QR Code": "扫描二维码",
  "Last Scanned": "最后扫描",
  "Scan History": "扫描历史",
  "Total Scans": "扫描总数",
  "Successful Scans": "成功扫描",
  "Failed Scans": "失败扫描",
  "Scan Rate": "扫描率",
  "Avg Scan Time": "平均扫描时间",
  "Scan Action": "扫描操作",
  "Package found": "找到包裹",
  "Already scanned": "已扫描",
  "Scan successful": "扫描成功",
  "Scan failed": "扫描失败",
  "Invalid barcode": "无效条码",
  "Select Warehouse": "选择仓库",
  "Select Action": "选择操作",
  "Sound Enabled": "声音已启用",
  "Sound Disabled": "声音已禁用",
  "Vibration Enabled": "振动已启用",
  "Vibration Disabled": "振动已禁用",

  // --- Finance ---
  "Manage customer finances": "管理客户财务",
  "Finance Management": "财务管理",
  "Ledger": "账本",
  "Transactions": "交易",
  "Debt": "债务",
  "Credit": "信用",
  "Cheque": "支票",
  "Online": "在线",
  "Payment Date": "付款日期",
  "Payment Amount": "付款金额",
  "Payment Reference": "付款参考",
  "Payment Notes": "付款备注",
  "New Payment": "新付款",
  "Edit Payment": "编辑付款",
  "Delete Payment": "删除付款",
  "Payment recorded": "付款已记录",
  "Payment updated": "付款已更新",
  "Payment deleted": "付款已删除",
  "Are you sure you want to delete this payment?": "确定要删除此付款吗？",
  "No payments": "没有付款",
  "Search payments...": "搜索付款...",
  "Filter by Method": "按方式筛选",
  "Filter by Date": "按日期筛选",
  "New Invoice": "新发票",
  "Edit Invoice": "编辑发票",
  "Delete Invoice": "删除发票",
  "Invoice Number": "发票号",
  "Invoice Date": "发票日期",
  "Due Date": "到期日",
  "Invoice Amount": "发票金额",
  "Invoice Status": "发票状态",
  "Draft": "草稿",
  "Invoice created": "发票已创建",
  "Invoice updated": "发票已更新",
  "Invoice deleted": "发票已删除",
  "No invoices": "没有发票",
  "Search invoices...": "搜索发票...",
  "Print Invoice": "打印发票",
  "Send Invoice": "发送发票",
  "Download Invoice": "下载发票",
  "Overdue Amount": "逾期金额",
  "View Statement": "查看对账单",

  // --- Company Finance ---
  "Track revenue, expenses, profit and loss": "追踪收入、支出、盈亏",
  "Profit/Loss": "盈亏",
  "Charts": "图表",
  "Revenue by Source": "按来源收入",
  "Air Batch Profit": "空运批次利润",
  "Irregular Air Batch": "特殊空运批次",
  "Sea Batch Profit": "海运批次利润",
  "Sea Shipping": "海运",
  "Commission Income": "佣金收入",
  "Purchase Price": "采购价格",
  "Total Commission": "佣金总额",
  "Activity Stats": "活动统计",
  "Full Packages Sold": "已售全套服务",
  "Commission Orders": "佣金订单",
  "Services Completed": "已完成服务",
  "Batch Profit Breakdown": "批次利润明细",
  "Net profit for all batch types": "所有批次类型的净利润",
  "Total Batch Profit": "批次总利润",
  "By Service Type": "按服务类型",
  "View All": "查看全部",
  "Expenses by Category": "按类别支出",
  "Expense Distribution": "支出分布",
  "No expenses recorded": "无支出记录",
  "No data available": "暂无数据",
  "Revenue Comparison by Source": "按来源收入比较",
  "Commission": "佣金",
  "Last 6 Months": "最近6个月",
  "Business reports": "业务报告",
  "Yearly Report": "年度报告",
  "Customer Pricing Report": "客户定价报告",
  "Batch Financial Report": "批次财务报告",
  "Select Date Range": "选择日期范围",
  "Generate Report": "生成报告",
  "Export CSV": "导出CSV",
  "Print Report": "打印报告",
  "Share Report": "分享报告",
  "Schedule Report": "定时报告",
  "New Customers": "新客户",
  "Top Products": "热门产品",
  "Sales by Category": "按类别销售",
  "Sales by Region": "按地区销售",
  "Sales Trend": "销售趋势",
  "Comparison with Previous": "与上期比较",
  "Growth": "增长",
  "Decline": "下降",
  "No Change": "无变化",

  // --- Settings ---
  "System Mode": "系统模式",
  "Email Notifications": "邮件通知",
  "Push Notifications": "推送通知",
  "SMS Notifications": "短信通知",
  "Two-Factor Auth": "双重认证",
  "Sessions": "会话",
  "Invoice Template": "发票模板",
  "Label Printing": "标签打印",
  "Notification Settings": "通知设置",
  "Roles": "角色",
  "Permissions": "权限",
  "Blog Management": "博客管理",
  "Company Info": "公司信息",
  "Company Name": "公司名称",
  "Company Address": "公司地址",
  "Company Phone": "公司电话",
  "Company Email": "公司邮箱",
  "Tax Number": "税号",
  "Default Currency": "默认货币",
  "Default Language": "默认语言",
  "Default Timezone": "默认时区",
  "Save Settings": "保存设置",
  "Reset to Default": "恢复默认",

  // --- Blog ---
  "Manage blog and announcements": "管理博客和公告",
  "Posts": "文章",
  "Delete Post": "删除文章",
  "Likes": "点赞",
  "Comments": "评论",
  "Search posts...": "搜索文章...",
  "Filter by Category": "按类别筛选",
  "Post created": "文章已创建",
  "Post updated": "文章已更新",
  "Post deleted": "文章已删除",
  "Are you sure you want to delete this post?": "确定要删除此文章吗？",
  "No posts": "没有文章",
  "Add your first post": "添加您的第一篇文章",
  "Publish": "发布",
  "Unpublish": "取消发布",
  "Save Draft": "保存草稿",
  "Customer Portal": "客户门户",
  "Welcome": "欢迎",
  "Welcome back": "欢迎回来",
  "No announcements": "没有公告",
  "Estimated Delivery": "预计配送",
  "Current Location": "当前位置",
  "Notification Preferences": "通知偏好",
  "Quick Stats": "快速统计",

  // --- Auth ---
  "Login with Google": "Google登录",
  "Login with Facebook": "Facebook登录",
  "Don't have an account?": "没有账户？",
  "Already have an account?": "已有账户？",
  "Create Account": "创建账户",
  "Login to your account": "登录账户",
  "Enter your credentials": "输入凭据",
  "Invalid email or password": "邮箱或密码无效",
  "Account is locked": "账户已锁定",
  "Session expired": "会话已过期",
  "Login successful": "登录成功",
  "Logout successful": "退出成功",
  "Registration successful": "注册成功",
  "Password reset link sent": "密码重置链接已发送",
  "Password changed": "密码已更改",
  "Copied successfully": "复制成功",
  "Uploaded successfully": "上传成功",
  "Downloaded successfully": "下载成功",
  "Sent successfully": "发送成功",
  "Are you sure you want to cancel?": "确定要取消吗？",
  "Are you sure you want to save?": "确定要保存吗？",
  "Are you sure you want to logout?": "确定要退出吗？",
  "Operation completed": "操作完成",
  "Downloading...": "下载中...",
  "No changes": "无更改",
  "You have unsaved changes": "您有未保存的更改",
  "Discard changes?": "放弃更改？",
  "Keep editing": "继续编辑",
  "Leave without saving": "不保存离开",

  // --- Welcome / Time ---
  "Welcome to Wazn Express": "欢迎来到Wazn Express",
  "Good morning": "早上好",
  "Good afternoon": "下午好",
  "Good evening": "晚上好",
  "Good night": "晚安",
  "First": "第一",
  "Last": "最后",
  "Search...": "搜索...",
  "Sort": "排序",
  "Columns": "列",
  "Show Columns": "显示列",
  "Hide Columns": "隐藏列",
  "Reset Filters": "重置筛选",
  "Clear Search": "清除搜索",
  "Select an option": "选择选项",
  "Select date": "选择日期",
  "Select time": "选择时间",
  "Select file": "选择文件",
  "Drag and drop": "拖放",
  "Browse": "浏览",
  "Upload image": "上传图片",
  "Upload file": "上传文件",
  "Remove file": "删除文件",
  "Remove": "删除",
  "Enter value": "输入值",
  "Enter text": "输入文本",
  "Enter number": "输入数字",
  "Enter email": "输入邮箱",
  "Enter phone number": "输入电话号码",
  "Enter password": "输入密码",
  "Enter address": "输入地址",
  "Enter notes": "输入备注",
  "characters": "字符",
  "Just now": "刚刚",
  "minutes ago": "分钟前",
  "hours ago": "小时前",
  "days ago": "天前",
  "weeks ago": "周前",
  "months ago": "月前",
  "years ago": "年前",
  "in minutes": "分钟后",
  "in hours": "小时后",
  "in days": "天后",
  "in weeks": "周后",
  "in months": "月后",
  "in years": "年后",
  "Next week": "下周",
  "Next month": "下个月",
  "Next year": "明年",
  "On Hold": "暂停",
  "Archived": "已归档",
  "Closed": "已关闭",
  "Resolved": "已解决",
  "Unresolved": "未解决",

  // --- Units ---
  "kg": "公斤",
  "g": "克",
  "lb": "磅",
  "oz": "盎司",
  "cm": "厘米",
  "m": "米",
  "inch": "英寸",
  "ft": "英尺",
  "cbm": "立方米",
  "box": "箱",
  "carton": "纸箱",
  "pallet": "托盘",
  "container": "集装箱",
  "US Dollar": "美元",
  "Iraqi Dinar": "伊拉克第纳尔",
  "Chinese Yuan": "人民币",
  "Euro": "欧元",
  "British Pound": "英镑",
  "UAE Dirham": "阿联酋迪拉姆",
  "Turkish Lira": "土耳其里拉",
  "Are you sure you want to delete this goal?": "确定要删除此目标吗？",

  // --- Treasury ---
  "Add Account": "添加账户",
  "Add a new account for financial management": "为财务管理添加新账户",
  "Account added successfully": "账户添加成功",
  "Enter account name": "输入账户名称",
  "Account Type": "账户类型",
  "Enter bank name": "输入银行名称",
  "Initial Balance": "初始余额",
  "Account description": "账户描述",
  "Transaction History": "交易历史",
  "Select Account": "选择账户",
  "Select destination account": "选择目标账户",
  "No transactions found": "未找到交易",
  "Record Transaction": "记录交易",
  "Transaction recorded successfully": "交易记录成功",
  "Transaction Type": "交易类型",
  "Transaction Description": "交易描述",
  "Transaction description": "交易描述",
  "Receipt Number": "收据号",
  "Transfer Out": "转出",
  "Transfer completed successfully": "转账完成",
  "Search transactions...": "搜索交易...",

  // --- Expense Alerts ---
  "Expense Alert System": "支出警报系统",
  "Automatic notifications when expenses exceed configured thresholds": "当支出超过配置阈值时自动通知",
  "New Alert": "新警报",
  "Edit Alert": "编辑警报",
  "Set a threshold for expenses and receive notifications when exceeded": "设置支出阈值并在超出时接收通知",
  "Total Alerts": "警报总数",
  "Times Triggered": "触发次数",
  "Trigger History": "触发历史",
  "No alerts configured": "未配置警报",
  "Create a new alert to track your expenses": "创建新警报以追踪支出",
  "Create your first alert": "创建您的第一个警报",
  "No triggers yet": "尚无触发",
  "When expenses exceed thresholds, triggers will be logged here": "当支出超过阈值时，触发记录将在此处显示",
  "Threshold": "阈值",
  "Threshold Amount": "阈值金额",
  "Alert Type": "警报类型",
  "Total daily expenses": "每日总支出",
  "Total weekly expenses": "每周总支出",
  "Total monthly expenses": "每月总支出",
  "Per Transaction": "每笔交易",
  "Each individual expense": "每笔单独支出",
  "Alert triggers if any single expense exceeds this amount": "任何单笔支出超过此金额时触发警报",
  "Alert triggers if total expenses in this period exceed this amount": "此期间总支出超过此金额时触发警报",
  "Expense Category": "支出类别",
  "Notification Method": "通知方式",
  "System Notification": "系统通知",
  "Both": "两者",
  "Add a note (optional)...": "添加备注（可选）...",
  "Delete Alert": "删除警报",
  "Are you sure you want to delete this alert? This action cannot be undone.": "确定要删除此警报吗？此操作不可撤销。",
  "Alert created successfully": "警报创建成功",
  "Error creating alert": "创建警报出错",
  "Alert updated successfully": "警报更新成功",
  "Error updating alert": "更新警报出错",
  "Alert deleted successfully": "警报删除成功",
  "Error deleting alert": "删除警报出错",
  "Please specify a threshold amount": "请指定阈值金额",
  "Expense Count": "支出数量",
  "And": "和",
  "VIP": "VIP",
  "S, M, L, XL...": "S, M, L, XL...",
  "CBM": "CBM",
};

// ============================================================
// COMPREHENSIVE English → Arabic DICTIONARY
// ============================================================

const enToAr = {
  // --- Financial / Balance Sheet ---
  "Balance Sheet": "الميزانية العمومية",
  "Assets": "الأصول",
  "Total Assets": "إجمالي الأصول",
  "Liabilities": "الالتزامات",
  "Total Liabilities": "إجمالي الالتزامات",
  "Liabilities & Equity": "الالتزامات وحقوق الملكية",
  "Equity": "حقوق الملكية",
  "Current Assets": "الأصول المتداولة",
  "Cash": "نقد",
  "Bank Account": "حساب مصرفي",
  "Bank Accounts": "حسابات البنك",
  "Customer Debts": "ديون العملاء",
  "Customer Debt": "دين العميل",
  "Packages in Transit": "طرود في الطريق",
  "Supplier Debts": "ديون الموردين",
  "Unpaid Expenses": "مصروفات غير مدفوعة",
  "Bank Debt": "دين مصرفي",
  "Owners' Equity": "حقوق الملكية",
  "Capital Structure": "هيكل رأس المال",
  "Initial Capital": "رأس المال الأولي",
  "Revenue": "الإيرادات",
  "Total Revenue": "إجمالي الإيرادات",
  "Total Income": "إجمالي الدخل",
  "Expenses": "المصروفات",
  "Expense": "مصروف",
  "Total Expenses": "إجمالي المصروفات",
  "Profit": "ربح",
  "Net Profit": "صافي الربح",
  "Net Loss": "صافي الخسارة",
  "Loss": "خسارة",
  "Gross Profit": "الربح الإجمالي",
  "Total Cost": "إجمالي التكلفة",
  "Total Profit": "إجمالي الربح",
  "Total Debt": "إجمالي الدين",
  "Total Balance": "إجمالي الرصيد",
  "Total": "إجمالي",
  "Total Cash": "إجمالي النقد",
  "Income": "دخل",
  "Income Increase": "زيادة الدخل",
  "Income Decrease": "نقص الدخل",
  "Expenditures": "المصروفات",
  "Total Expenditures": "إجمالي المصروفات",
  "Accumulated Profit": "الأرباح المتراكمة",
  "Retained Profit": "الأرباح المحتجزة",
  "Retained Balance": "الرصيد المحتجز",
  "Profit Share": "حصة الأرباح",
  "Profit Rate": "نسبة الربح",
  "Profit Margin": "هامش الربح",
  "Total Capital": "إجمالي رأس المال",
  "Financial Ratios": "النسب المالية",
  "Current Ratio": "نسبة التداول",
  "Debt Ratio": "نسبة الدين",
  "Equity Ratio": "نسبة حقوق الملكية",
  "Working Capital": "رأس المال العامل",
  "Capital": "رأس المال",
  "Withdrawal": "سحب",
  "Debt to Company": "دين للشركة",
  "Debt Repayment": "سداد الدين",
  "Adjustment": "تعديل",
  "Debit Adjustment": "تعديل مدين",
  "Credit Adjustment": "تعديل دائن",
  "Other Debit": "مدين آخر",
  "Other Credit": "دائن آخر",
  "Cash Flow": "التدفق النقدي",
  "Cash Flow Report\n\n": "تقرير التدفق النقدي\n\n",
  "Net Cash Flow": "صافي التدفق النقدي",
  "Total Inflow": "إجمالي التدفق الداخل",
  "Total Outflow": "إجمالي التدفق الخارج",
  "Inflow": "وارد",
  "Outflow": "صادر",
  "Negative": "سالب",
  "Positive": "إيجابي",
  "Current Cash": "النقد الحالي",
  "Cash Box": "صندوق النقد",
  "Cash Accounts": "حسابات النقد",
  "Main Cash": "النقد الرئيسي",
  "Bank Card": "بطاقة بنكية",
  "Main Bank Account": "الحساب المصرفي الرئيسي",
  "FIB Account": "حساب FIB",
  "Kurdistan Bank": "بنك كردستان",
  "Mobile Wallet": "محفظة الجوال",
  "Transfer": "تحويل",
  "Transfer (In)": "تحويل (وارد)",
  "Transfer (Out)": "تحويل (صادر)",
  "Bank Transfer": "تحويل بنكي",
  "Deposit": "إيداع",
  "Account": "حساب",
  "Account Name": "اسم الحساب",
  "Account Number": "رقم الحساب",
  "Transaction": "معاملة",
  "Balance": "رصيد",
  "Balance Sheet\n": "الميزانية العمومية\n",
  "Assets\n": "الأصول\n",
  "Liabilities\n": "الالتزامات\n",
  "Equity\n": "حقوق الملكية\n",
  "\nExpenses\n": "\nالمصروفات\n",
  "Revenue\n": "الإيرادات\n",
  "Profit & Loss Report\n\n": "تقرير الأرباح والخسائر\n\n",
  "Profit & Loss Statement": "بيان الأرباح والخسائر",
  "Profit & Loss Report": "تقرير الأرباح والخسائر",

  // --- Monthly / Time ---
  "Monthly": "شهري",
  "Daily": "يومي",
  "Weekly": "أسبوعي",
  "Quarterly": "ربع سنوي",
  "Yearly": "سنوي",
  "January": "يناير",
  "February": "فبراير",
  "March": "مارس",
  "April": "أبريل",
  "May": "مايو",
  "June": "يونيو",
  "July": "يوليو",
  "August": "أغسطس",
  "September": "سبتمبر",
  "October": "أكتوبر",
  "November": "نوفمبر",
  "December": "ديسمبر",
  "Today": "اليوم",
  "Yesterday": "أمس",
  "Tomorrow": "غداً",
  "This Week": "هذا الأسبوع",
  "Last Week": "الأسبوع الماضي",
  "This Month": "هذا الشهر",
  "Last Month": "الشهر الماضي",
  "This Year": "هذه السنة",
  "Last Year": "السنة الماضية",
  "All Time": "كل الوقت",
  "Last 3 Months": "آخر 3 أشهر",
  "Period": "الفترة",

  // --- Payment ---
  "Payment": "دفعة",
  "Payments": "المدفوعات",
  "Total Payments": "إجمالي المدفوعات",
  "Payment Method": "طريقة الدفع",
  "Payment Status": "حالة الدفع",
  "Customer Payment": "دفعة العميل",
  "Record Payment": "تسجيل دفعة",
  "Record Customer Payment": "تسجيل دفع العميل",
  "Paid": "مدفوع",
  "Unpaid": "غير مدفوع",
  "Invoice": "فاتورة",
  "Invoices": "الفواتير",
  "Invoice Style": "نمط الفاتورة",
  "Invoice Template Settings": "إعدادات قالب الفاتورة",
  "Invoice Number Prefix": "بادئة رقم الفاتورة",
  "Full Package Payment": "دفعة الطرد الكامل",

  // --- Customer ---
  "Customer": "العميل",
  "Customers": "العملاء",
  "customers": "عملاء",
  "Total Customers": "إجمالي العملاء",
  "Customer Income": "دخل العميل",
  "Customer Name": "اسم العميل",
  "Customer Login": "تسجيل دخول العميل",
  "Customer Pricing": "تسعير العميل",
  "Customer-Specific Pricing": "تسعير خاص بالعميل",
  "Customer Report": "تقرير العميل",
  "customers selected": "عملاء محددون",
  "Selected Customers": "العملاء المحددون",

  // --- Package ---
  "Package": "طرد",
  "Packages": "الطرود",
  "Total Packages": "إجمالي الطرود",
  "Package Price": "سعر الطرد",
  "Package Number": "رقم الطرد",
  "Package Delivery": "توصيل الطرد",
  "Selected Packages": "الطرود المحددة",
  "Full Package": "طرد كامل",
  "Full Package Sale": "بيع الطرد الكامل",
  "Full Package Commission": "عمولة الطرد الكامل",
  "Full Package Profit": "ربح الطرد الكامل",
  "Full Package Report": "تقرير الطرد الكامل",

  // --- Batch ---
  "Batch": "دفعة",
  "Batches": "الدفعات",
  "Total Batches": "إجمالي الدفعات",
  "Select Batch": "اختيار الدفعة",
  "In Batch": "في الدفعة",
  "No Batch": "بدون دفعة",
  "Selected Batch": "الدفعة المحددة",
  "Group/Batch": "مجموعة/دفعة",

  // --- Warehouse / Shipping ---
  "Warehouse": "المستودع",
  "Delivery": "التوصيل",
  "Shipping": "الشحن",
  "Shipping Type": "نوع الشحن",
  "Shipping Fee": "رسوم الشحن",
  "Air": "جوي",
  "Air Regular": "جوي عادي",
  "Air Irregular": "جوي خاص",
  "Sea": "بحري",
  "In Transit": "في الطريق",
  "In China Warehouse": "في مستودع الصين",
  "Delivered": "تم التوصيل",
  "Arrived": "وصل",
  "Arrived in China": "وصل إلى الصين",
  "Arrived in Kurdistan": "وصل إلى كردستان",
  "Received Locally": "وصل محلياً",
  "Received": "تم الاستلام",
  "Received in China": "تم الاستلام في الصين",
  "Registered": "مسجل",
  "Sent": "تم الإرسال",
  "Returned": "مرتجع",
  "Out for Delivery": "للتوصيل",
  "Ready for Delivery": "جاهز للتوصيل",
  "Delivery Confirmation": "تأكيد التوصيل",
  "Customs Hold": "الجمارك",
  "Receive from China": "الاستلام من الصين",
  "Ship to Iraq": "الإرسال للعراق",
  "Deliver to customer": "التسليم للعميل",
  "Recipient Name": "اسم المستلم",
  "Recipient name...": "اسم المستلم...",
  "Destination City": "المدينة الوجهة",
  "Operations Center": "مركز العمليات",
  "Air and sea cargo shipping to Iraq": "شحن جوي وبحري إلى العراق",

  // --- Supplier ---
  "Supplier": "المورد",
  "Suppliers": "الموردون",
  "Total Suppliers": "إجمالي الموردين",
  "New Supplier": "مورد جديد",
  "Edit Supplier": "تعديل المورد",
  "Supplier Name": "اسم المورد",
  "Wholesaler": "تاجر جملة",

  // --- Staff ---
  "User": "المستخدم",
  "Users": "المستخدمون",
  "Staff": "الموظفون",
  "Staff Login": "تسجيل دخول الموظفين",
  "Admin": "المشرف",
  "Manager": "المدير",
  "Agent": "وكيل",
  "Employee": "موظف",
  "Employee Salaries": "رواتب الموظفين",
  "Salary": "راتب",
  "Username": "اسم المستخدم",
  "Password": "كلمة المرور",
  "Login": "تسجيل الدخول",
  "Logging in...": "جاري تسجيل الدخول...",
  "Login failed": "فشل تسجيل الدخول",

  // --- Common UI ---
  "Delete": "حذف",
  "Edit": "تعديل",
  "Add": "إضافة",
  "Save": "حفظ",
  "Cancel": "إلغاء",
  "Search": "بحث",
  "Filter": "تصفية",
  "Export": "تصدير",
  "Import": "استيراد",
  "Backup": "نسخ احتياطي",
  "Restore": "استعادة",
  "Settings": "الإعدادات",
  "Report": "تقرير",
  "Reports": "التقارير",
  "Dashboard": "لوحة التحكم",
  "Date": "التاريخ",
  "Name": "الاسم",
  "Code": "الرمز",
  "Type": "النوع",
  "Amount": "المبلغ",
  "Amount (USD": "المبلغ (دولار",
  "Actions": "الإجراءات",
  "Details": "التفاصيل",
  "Description": "الوصف",
  "Notes": "ملاحظات",
  "Created": "تم الإنشاء",
  "Updated": "تم التحديث",
  "Deleted": "تم الحذف",
  "Scan": "مسح",
  "Scans": "عمليات المسح",
  "Scanning": "جاري المسح",
  "Register": "تسجيل",
  "Registration": "التسجيل",
  "Tracking": "التتبع",
  "Tracking Number": "رقم التتبع",
  "Tracking Alert": "تنبيه التتبع",
  "Tracking Alerts": "تنبيهات التتبع",
  "Tracking number...": "رقم التتبع...",
  "Tracking Added": "تمت إضافة التتبع",
  "Track": "تتبع",
  "Status": "الحالة",
  "Active": "نشط",
  "Inactive": "غير نشط",
  "Enabled": "مفعل",
  "Disabled": "معطل",
  "Pending": "قيد الانتظار",
  "Completed": "مكتمل",
  "completed": "مكتمل",
  "Failed": "فشل",
  "Cancelled": "ملغي",
  "Approved": "موافق عليه",
  "Loading": "جاري التحميل",
  "Loading...": "جاري التحميل...",
  "Saving...": "جاري الحفظ...",
  "Creating...": "جاري الإنشاء...",
  "Printing": "جاري الطباعة",
  "Sending...": "جاري الإرسال...",
  "Uploading...": "جاري الرفع...",
  "No Data": "لا توجد بيانات",
  "No Results Found": "لم يتم العثور على نتائج",
  "Success": "نجاح",
  "Error": "خطأ",
  "Error:": "خطأ:",
  "Warning": "تحذير",
  "Info": "معلومات",
  "Alert": "تنبيه",
  "Close": "إغلاق",
  "Open": "فتح",
  "Confirm": "تأكيد",
  "Select": "اختيار",
  "Select All": "اختيار الكل",
  "Deselect All": "إلغاء تحديد الكل",
  "Required": "مطلوب",
  "Optional": "اختياري",
  "Yes": "نعم",
  "No": "لا",
  "All": "الكل",
  "None": "لا شيء",
  "New": "جديد",
  "Old": "قديم",
  "Enable": "تفعيل",
  "Disable": "تعطيل",
  "Download": "تنزيل",
  "Upload": "رفع",
  "Print": "طباعة",
  "Print Label": "طباعة الملصق",
  "Copy": "نسخ",
  "Paste": "لصق",
  "View": "عرض",
  "More": "المزيد",
  "more": "المزيد",
  "Less": "أقل",
  "Show More": "عرض المزيد",
  "Show Less": "عرض أقل",
  "Back": "رجوع",
  "Next": "التالي",
  "Previous": "السابق",
  "Send": "إرسال",
  "Reset": "إعادة تعيين",
  "Clear": "مسح",
  "Refresh": "تحديث",
  "From": "من",
  "To": "إلى",
  "Between": "بين",
  "And": "و",
  "Or": "أو",
  "Custom": "مخصص",
  "Default": "افتراضي",
  "Ascending": "تصاعدي",
  "Descending": "تنازلي",
  "Sort By": "ترتيب حسب",
  "Sort Order": "ترتيب",
  "Filter By": "تصفية حسب",
  "Group By": "تجميع حسب",
  "Per Page": "لكل صفحة",
  "Page": "صفحة",
  "Items": "عناصر",
  "Showing": "عرض",
  "Results": "النتائج",
  "Found": "تم العثور",
  "Not Found": "غير موجود",
  "Coming Soon": "قريباً",
  "Under Construction": "قيد الإنشاء",
  "Beta": "تجريبي",
  "Price": "السعر",
  "Number": "رقم",
  "Weight": "الوزن",
  "Weight (KG)": "الوزن (كغ)",
  "Weight (kg)": "الوزن (كغ)",
  "Volume": "الحجم",
  "Height": "الارتفاع",
  "Width": "العرض",
  "Length": "الطول",
  "Time": "الوقت",
  "Start Date": "تاريخ البدء",
  "End Date": "تاريخ الانتهاء",
  "Remaining": "المتبقي",
  "Progress": "التقدم",
  "Current": "الحالي",
  "Current:": "الحالي:",
  "Goal:": "الهدف:",
  "Goal": "هدف",
  "Target": "الهدف",
  " days": " يوم",
  " days overdue": " يوم متأخر",
  " records": " سجل",
  "records": "سجلات",
  "of total": "من الإجمالي",
  "rate": "نسبة",
  "from last month": "من الشهر الماضي",
  "Logout": "تسجيل الخروج",
  "Profile": "الملف الشخصي",
  "Management": "الإدارة",
  "Auto Refresh": "تحديث تلقائي",
  "New Request": "طلب جديد",
  "Distributed": "موزع",
  "Are you sure": "هل أنت متأكد",
  "Are you sure you want to delete": "هل أنت متأكد من الحذف",
  "What are you doing today?": "ماذا تفعل اليوم؟",
  "What are you doing today": "ماذا تفعل اليوم",
  "How can I help you": "كيف يمكنني مساعدتك",
  "Fast & Reliable Shipping": "شحن سريع وموثوق",
  "All rights reserved": "جميع الحقوق محفوظة",
  "Wazn Express": "وزن إكسبرس",
  "Product Link": "رابط المنتج",

  // --- Service ---
  "Service": "خدمة",
  "Services": "الخدمات",
  "Service Types": "أنواع الخدمات",
  "Service Fee": "رسوم الخدمة",
  "Service Profit": "ربح الخدمة",
  "Service Profit Report": "تقرير أرباح الخدمة",
  "Extra Services": "خدمات إضافية",
  "Icon": "أيقونة",
  "Order/Rank": "الترتيب",
  "Cost": "التكلفة",
  "Total Cost": "إجمالي التكلفة",
  "Default Cost ($)": "التكلفة الافتراضية ($)",
  "Default Price ($)": "السعر الافتراضي ($)",
  "Default Price": "السعر الافتراضي",

  // --- Reports ---
  "Financial Reports": "التقارير المالية",
  "Financial Report": "تقرير مالي",
  "Financial Goal": "هدف مالي",
  "Monthly Report": "تقرير شهري",
  "Weekly Report": "تقرير أسبوعي",
  "Daily Report": "تقرير يومي",
  "Monthly Trend": "الاتجاه الشهري",
  "Balance Sheet PDF created": "تم إنشاء الميزانية PDF",
  "Debt table PDF created": "تم إنشاء جدول الديون PDF",
  "PDF report created": "تم إنشاء تقرير PDF",
  "Batch report downloaded": "تم تنزيل تقرير الدفعة",
  "Partner report PDF created": "تم إنشاء تقرير الشريك PDF",
  "Expenses report PDF created": "تم إنشاء تقرير المصروفات PDF",
  "Error creating PDF": "خطأ في إنشاء PDF",
  "Image loading error:": "خطأ في تحميل الصورة:",
  "Financial stats for": "إحصائيات مالية لـ",
  "Income and expense stats for": "إحصائيات الدخل والمصروفات لـ",

  // --- Order Center ---
  "Order": "طلب",
  "Order Center": "مركز الطلبات",
  "Order Code": "رمز الطلب",
  "Order Number": "رقم الطلب",
  "Order Date": "تاريخ الطلب",
  "Order Placed": "تم الطلب",
  "Ordered": "مطلوب",
  "Edit Order": "تعديل الطلب",
  "Total Orders": "إجمالي الطلبات",
  "Total Purchases": "إجمالي المشتريات",
  "Total Sales": "إجمالي المبيعات",
  "Purchase": "شراء",
  "Resale": "إعادة البيع",
  "Returns": "المرتجعات",
  "Return Rate": "نسبة الإرجاع",
  "Return/Refund": "إرجاع/استرداد",
  "By Supplier": "حسب المورد",
  "By Customer": "حسب العميل",
  "Delivery Time": "وقت التسليم",
  "Average Days": "متوسط الأيام",
  "Minimum": "الأقل",
  "Maximum": "الأقصى",
  "On Time": "في الوقت",
  "Late": "متأخر",
  "Delivery Day": "يوم التسليم",
  "Goods": "بضائع",
  "Reason": "السبب",
  "Action": "إجراء",
  "Pending Orders": "الطلبات المعلقة",
  "Without order number": "بدون رقم طلب",
  "Orders without tracking": "طلبات بدون تتبع",
  "With Tracking": "مع تتبع",
  "Without Tracking": "بدون تتبع",
  "Add Tracking Number": "إضافة رقم التتبع",
  "Enter tracking number...": "أدخل رقم التتبع...",
  "Tracking number added": "تمت إضافة رقم التتبع",
  "Please enter tracking number": "الرجاء إدخال رقم التتبع",

  // --- Scanning ---
  "Scan Dashboard": "لوحة المسح",
  "Scan to start...": "امسح للبدء...",
  "Scan to start": "امسح للبدء",
  "Scan or type...": "امسح أو اكتب...",
  "Continuous Scan": "مسح مستمر",
  "Camera Scan": "مسح الكاميرا",
  "Camera": "الكاميرا",
  "Last scan deleted": "تم حذف آخر مسح",
  "Hardware scanner or typing supported": "يدعم الماسح الضوئي أو الكتابة",
  "Recent Scans": "عمليات المسح الأخيرة",
  "Latest Scans": "آخر عمليات المسح",
  "Today's Scans": "مسح اليوم",
  "Quick Actions": "إجراءات سريعة",
  "Quick Register": "تسجيل سريع",
  "Scan Type": "نوع المسح",
  "Scan List": "قائمة المسح",
  "Scan Report - Wazn Express": "تقرير المسح - وزن إكسبرس",
  "Wazn Express - Shipping Management System": "وزن إكسبرس - نظام إدارة الشحن",
  "Place barcode inside the frame": "ضع الباركود داخل الإطار",
  "Could not open camera": "لم يتم فتح الكاميرا",

  // --- Blog ---
  "Published": "منشور",
  "Archive": "أرشيف",
  "News": "أخبار",
  "Announcement": "إعلان",
  "Guide": "دليل",

  // --- Goals ---
  "Financial Goal": "هدف مالي",
  "Goal Name": "اسم الهدف",
  "Goal Type": "نوع الهدف",
  "Goal History": "سجل الأهداف",
  "Create New Goal": "إنشاء هدف جديد",
  "No active goals": "لا توجد أهداف نشطة",
  "Goal created": "تم إنشاء الهدف",
  "Goal cancelled": "تم إلغاء الهدف",

  // --- Debtors ---
  "Debtors": "المدينون",
  "Debtors Report": "تقرير المدينين",
  "Debtors List": "قائمة المدينين",
  "Debt Age": "عمر الدين",
  "Debt Collection": "تحصيل الديون",
  "Send Reminder": "إرسال تذكير",
  "Send Debt Reminder": "إرسال تذكير بالدين",

  // --- Template ---
  "Template": "قالب",
  "Templates": "القوالب",
  "Template Name": "اسم القالب",
  "Template Settings": "إعدادات القالب",
  "New Template": "قالب جديد",
  "Create New Template": "إنشاء قالب جديد",
  "Edit Template": "تعديل القالب",
  "Default Template": "القالب الافتراضي",
  "Custom Size": "حجم مخصص",

  // --- Misc ---
  "Company": "الشركة",
  "Logo": "الشعار",
  "Website": "الموقع الإلكتروني",
  "Email": "البريد الإلكتروني",
  "Name or Email": "الاسم أو البريد الإلكتروني",
  "Discount": "خصم",
  "Penalty": "غرامة",
  "Rent": "إيجار",
  "Card": "بطاقة",
  "Activation": "تفعيل",
  "Normal": "عادي",
  "High": "مرتفع",
  "Low": "منخفض",
  "Unknown": "غير معروف",
  "Other": "أخرى",
  "Other Expenses": "مصروفات أخرى",
  "Personal": "شخصي",
  "Shopkeeper": "صاحب متجر",
  "Foreign": "أجنبي",
  "Emergency": "طوارئ",
  "Irregular": "غير عادي",
  "Unclaimed": "بدون مالك",
  "No Customer": "بدون عميل",
  "General": "عام",
  "Content": "المحتوى",
  "Left": "يسار",
  "Center": "وسط",
  "Right": "يمين",
  "Top Left": "أعلى يسار",
  "Top Right": "أعلى يمين",
  "Bottom Left": "أسفل يسار",
  "Bottom Right": "أسفل يمين",
  "Label Size": "حجم الملصق",
  "(Default)": "(افتراضي)",
  "(Dollar)": "(دولار)",
  "(Number)": "(رقم)",
  "+ Name": "+ اسم",
  "+ Number": "+ رقم",
  "Assyrian": "آشوري",
  "Armenian": "أرمني",
  "Turkmen": "تركمان",
  "Kurdish": "كردي",
  "Arab": "عربي",
  "Ahmed Mohammed": "أحمد محمد",
  "Sulaymaniyah": "السليمانية",
  "Online Page": "الصفحة الإلكترونية",
  "Date,Inflow,Outflow,Net\n": "تاريخ,وارد,صادر,صافي\n",
  "Skip": "تخطي",
  "Calculate": "حساب",
  "Added to Batch": "في الدفعة",
  "Manual Entry": "إدخال يدوي",
  "Fill in information": "ملء المعلومات",
  "Waiting for...": "في انتظار...",
  "Wait...": "انتظر...",
  "Expense Limit": "حد المصروفات",
  "No batches available": "لا توجد دفعات",
  "Data imported successfully": "تم استيراد البيانات بنجاح",
  "Data deleted successfully": "تم حذف البيانات بنجاح",
  "Data updated successfully": "تم تحديث البيانات بنجاح",
  "Data saved successfully": "تم حفظ البيانات بنجاح",
  "missing info": "معلومات ناقصة",
  "Special Pricing": "تسعير خاص",
  "Select batch (optional)": "اختر الدفعة (اختياري)",
  "Select batch...": "اختر الدفعة...",
  "Select platform...": "اختر المنصة...",
  "May revenue goal": "هدف إيرادات شهر مايو",
  "May's Revenue": "إيرادات شهر مايو",
  "e.g., Clothes": "مثال: ملابس",
  "e.g., Clothing": "مثال: ملابس",
  "Example: Send RMB": "مثال: تحويل يوان",
  "Management System": "نظام الإدارة",
  "Total Suppliers": "إجمالي الموردين",
  "Evaluation Center": "مركز التقييم",
  "All Platforms": "جميع المنصات",
  "No suppliers": "لا يوجد موردون",
  "Platform": "المنصة",
  "Contact": "اتصال",
  "Evaluation": "التقييم",
  "Basic Information": "المعلومات الأساسية",
  "Name (English) *": "الاسم (إنجليزي) *",
  "Name (Arabic/Kurdish)": "الاسم (عربي/كردي)",
  "Name (Chinese)": "الاسم (صيني)",
  "Contact Information": "معلومات الاتصال",
  "Contact Person Name": "اسم جهة الاتصال",
  "Are you sure you want to delete?": "هل أنت متأكد من الحذف؟",
  "Search by name, contact, WeChat...": "البحث بالاسم، جهة الاتصال، WeChat...",
  "Supplier address in China": "عنوان المورد في الصين",
  "Note about supplier...": "ملاحظة عن المورد...",
  "Supplier added successfully": "تمت إضافة المورد بنجاح",
  "Supplier updated successfully": "تم تحديث المورد بنجاح",
  "Supplier deleted": "تم حذف المورد",
  "Please enter supplier name": "الرجاء إدخال اسم المورد",
  "Needs immediate resolution": "يجب حلها فوراً",
  "Needs Immediate Attention": "يحتاج اهتمام فوري",
  "Needs urgent resolution": "يجب حلها قريباً",
  "Needs Quick Resolution": "يحتاج حل سريع",
  "Needs attention": "يحتاج انتباه",
  "Needs Attention": "يحتاج انتباه",
  "Needs Resolution": "يحتاج حل",
  "Package registered in system": "تم تسجيل الطرد في النظام",
  "Package arrived at warehouse": "وصل الطرد للمستودع",
  "Package shipped to destination": "تم شحن الطرد للوجهة",
  "Package arrived at final destination": "وصل الطرد للوجهة النهائية",
  "Package delivered to customer": "تم تسليم الطرد للعميل",
  "Register new package in system": "تسجيل طرد جديد في النظام",
  "Receive package from China": "استلام الطرد من الصين",
  "Ship package to Erbil": "إرسال الطرد إلى أربيل",
  "Package arrived in Erbil": "وصول الطرد إلى أربيل",
  "Deliver package to customer": "تسليم الطرد للعميل",
  "Package registered without owner": "تم تسجيل الطرد بدون مالك",
  "Package not found": "لم يتم العثور على الطرد",
  "No Packages Found": "لم يتم العثور على طرود",
  "Customer Number": "رقم العميل",
  "When batch is shipped from China": "عند إرسال الدفعة من الصين",
  "When batch arrives in Kurdistan": "عند وصول الدفعة لكردستان",
  "When package arrives at China warehouse": "عند وصول الطرد لمستودع الصين",
  "When customer receives package": "عند استلام العميل للطرد",
  "Ledger Records": "سجلات الدفتر",
  "scans": "عمليات مسح",
  "views": "مشاهدات",
  "profit": "ربح",
  "Daily and monthly scan reports": "تقارير المسح اليومية والشهرية",
  "From date": "من تاريخ",
  "To date": "إلى تاريخ",
  "All scans list for specified period": "جميع عمليات المسح للفترة المحددة",
  "Change date range or filter": "تغيير نطاق التاريخ أو التصفية",
  "Report period:": "فترة التقرير:",
  "Scans by employee": "المسح حسب الموظف",
  "Tracking and statistics for all scans": "التتبع والإحصائيات لجميع عمليات المسح",
  "History of all scans by scan type": "سجل جميع عمليات المسح حسب النوع",
  "No scans found": "لم يتم العثور على عمليات مسح",
  "Enter a tracking number or change filter": "أدخل رقم التتبع أو غيّر التصفية",
  "Search by tracking number...": "البحث برقم التتبع...",
  "📊 Scan Report": "📊 تقرير المسح",
  "Reach 100 packages": "وصول 100 طرد",
  "⚠ Balance is incorrect": "⚠ الميزانية غير صحيحة",
  "✓ Balance is correct": "✓ الميزانية صحيحة",
  "Customer required": "يتطلب عميل",
  "Customer Required": "يتطلب عميل",
  "Add to customer balance": "إضافة لرصيد العميل",
  "Add to Balance": "إضافة للرصيد",
  "No service types": "لا توجد أنواع خدمات",
  "Create service types": "إنشاء أنواع الخدمات",
  "Edit Service Type": "تعديل نوع الخدمة",
  "Update service type info": "تحديث معلومات نوع الخدمة",
  "Add Type": "إضافة نوع",
  "Add Service Type": "إضافة نوع خدمة",
  "Create a new extra service type": "إنشاء نوع خدمة إضافية جديد",
  "This icon will appear": "ستظهر هذه الأيقونة",
  "English Name *": "الاسم الإنجليزي *",
  "Kurdish Name": "الاسم الكردي",
  "Arabic Name": "الاسم العربي",
  "Service type created": "تم إنشاء نوع الخدمة",
  "Manage extra service types": "إدارة أنواع الخدمات الإضافية",
  "All Types": "جميع الأنواع",
  "Service Profit Report - Profit and cost analysis for services": "تقرير أرباح الخدمة - تحليل الأرباح والتكاليف للخدمات",
  "Edit supplier information": "تعديل معلومات المورد",
  "Enter new supplier information": "إدخال معلومات المورد الجديد",
  "Are you sure you want to delete this blog?": "هل أنت متأكد من حذف هذه المدونة؟",
  "Are you sure you want to delete this service type?": "هل أنت متأكد من حذف نوع الخدمة هذا؟",
  "Delete all batch records and price levels": "حذف جميع سجلات الدفعات ومستويات الأسعار",
  "Delete all expense records": "حذف جميع سجلات المصروفات",
  "Delete all supplier records": "حذف جميع سجلات الموردين",
  "Delete all invoice records": "حذف جميع سجلات الفواتير",
  "Delete all ledger records and transactions": "حذف جميع سجلات الدفتر والمعاملات",
  "Delete all payment records and reminders": "حذف جميع سجلات المدفوعات والتذكيرات",
  "Delete all package records and tracking history": "حذف جميع سجلات الطرود وسجل التتبع",
  "Delete all customer records and related data": "حذف جميع سجلات العملاء والبيانات المرتبطة",
  "Delete all Full Package requests and status history": "حذف جميع طلبات الطرد الكامل وسجل الحالة",
  "Please enter username and password": "الرجاء إدخال اسم المستخدم وكلمة المرور",
  "Search by code, name, or number...": "البحث بالرمز أو الاسم أو الرقم...",
  "Price not set - must pass through Arrive": "السعر غير محدد - يجب أن يمر من الوصول",
  "Package Payment #PKG-1234": "دفعة الطرد #PKG-1234",
  "Package Payment #PKG-1235": "دفعة الطرد #PKG-1235",
  "Full Package #FP-567": "طرد كامل #FP-567",
  "Generated at": "تم الإنشاء في",
  "Total Transfers": "إجمالي التحويلات",
  "Partner": "شريك",
  "USD": "دولار",
  "Full Package requests": "طلبات الطرد الكامل",
  "Selected": "محدد",
  "Difference": "الفرق",
  "General Price": "السعر العام",
  "Special Price List": "قائمة الأسعار الخاصة",
  "Special Customer": "عميل خاص",
  "Special Batch": "دفعة خاصة",
  "All Customers": "جميع العملاء",
  "Preview": "معاينة",
  "Load": "تحميل",
  "No templates": "لا توجد قوالب",
  "Primary Color": "اللون الرئيسي",
  "Secondary Color": "اللون الثانوي",
  "Accent Color": "لون التمييز",
  "Text Color": "لون النص",
  "Font": "الخط",
  "Font Size": "حجم الخط",
  "Modern": "حديث",
  "Classic": "كلاسيكي",
  "Minimal": "بسيط",
  "Template Style": "نمط القالب",
  "Batch Number": "رقم الدفعة",
  "All Batches": "جميع الدفعات",
  "Company Finance Dashboard": "لوحة مالية الشركة",

  // --- Round 3 additions: errors ---
  "Minimum value is {{min}}": "الحد الأدنى {{min}}",
  "Maximum value is {{max}}": "الحد الأقصى {{max}}",
  "Password is too weak": "كلمة المرور ضعيفة",
  "Invalid format": "تنسيق غير صالح",
  "Invalid date": "تاريخ غير صالح",
  "Invalid number": "رقم غير صالح",
  "This entry already exists": "هذا الإدخال موجود مسبقاً",
  "Forbidden": "ممنوع",
  "Request timeout": "انتهت مهلة الطلب",
  "Please try again": "يرجى المحاولة مرة أخرى",
  "Contact support": "اتصل بالدعم",
  "File is too large": "الملف كبير جداً",
  "Invalid file type": "نوع الملف غير صالح",
  "Upload failed": "فشل الرفع",
  "Download failed": "فشل التنزيل",
  "Delete failed": "فشل الحذف",
  "Save failed": "فشل الحفظ",
  "Load failed": "فشل التحميل",
  "Claim Package": "المطالبة بالطرد",
  "Submit a claim for this package": "تقديم طلب مطالبة لهذا الطرد",
  "Submit Claim": "إرسال المطالبة",
  "Your claim requests will appear here": "ستظهر طلبات المطالبة الخاصة بك هنا",
  "Claim request sent successfully": "تم إرسال طلب المطالبة بنجاح",
  "Menu": "القائمة",
  "KG": "كغ",
  "LB": "رطل",
  "CM": "سم",
  "Inch": "بوصة",
  "Dollar": "دولار",
  "Dinar": "دينار",
  "Yuan": "يوان",
  "Percent": "بالمئة",
  "Days": "أيام",
  "Hours": "ساعات",
  "Minutes": "دقائق",
  "Seconds": "ثوانٍ",
  "ago": "مضت",
  "In Progress": "قيد التنفيذ",
  "Rejected": "مرفوض",
  "Confirmed": "مؤكد",
  "Unconfirmed": "غير مؤكد",
  "Filters": "التصفيات",
  "Export Excel": "تصدير Excel",
  "To Date": "إلى تاريخ",
  "Advanced Filters": "تصفية متقدمة",
  "Clear Filters": "مسح التصفيات",
  "No file selected": "لم يتم اختيار ملف",
  "Processing...": "جاري المعالجة...",
  "Advanced Scanner": "ماسح متقدم",
  "Warehouse Operations": "عمليات المستودع",
  "Smart Scanner": "ماسح ذكي",
  "AI Scanner": "ماسح AI",
  "Company Dashboard": "لوحة تحكم الشركة",
  "Debt Reminders": "تذكيرات الديون",
  "Financial Goals": "الأهداف المالية",
  "Reports Overview": "نظرة عامة على التقارير",
  "Profit Dashboard": "لوحة الأرباح",
  "VIP Customers": "عملاء VIP",
  "Product Categories": "فئات المنتجات",
  "Label Templates": "قوالب الملصقات",
  "Data Management": "إدارة البيانات",
  "Warehouses": "المستودعات",
  "Countries": "الدول",
  "Currencies": "العملات",
  "Shipping Types": "أنواع الشحن",
  "Audit Logs": "سجلات المراجعة",
  "Mobile Scanner": "ماسح الجوال",
  "Pricing": "التسعير",
  "Registered Today": "مسجل اليوم",
  "In Last 7 Days": "آخر 7 أيام",
  "On Route or Preparing": "في الطريق أو قيد التحضير",
  "Delivery Rate": "نسبة التوصيل",
  "Income Chart": "مخطط الدخل",
  "30 Days": "30 يوم",
  "No data yet": "لا توجد بيانات بعد",
  "Recent Activities": "الأنشطة الأخيرة",
  "New package registered": "تم تسجيل طرد جديد",
  "New customer": "عميل جديد",
  "Common Tasks": "المهام الشائعة",
  "Top Debtors": "أكبر المدينين",
  "No debtors!": "لا يوجد مدينون!",
  "No debtors": "لا يوجد مدينون",
  "No active batches": "لا توجد دفعات نشطة",
  "Top Customers": "أفضل العملاء",
  "No customer data yet": "لا توجد بيانات عملاء بعد",
  "Package Status": "حالة الطرد",
  "Unclaimed Packages": "طرود بدون مالك",
  "unclaimed packages": "طرود بدون مالك",
  "Full Package Requests": "طلبات الطرد الكامل",
  "pending requests": "طلبات معلقة",
  "Download App": "تنزيل التطبيق",
  "Download Wazn Express as an app for better experience": "قم بتنزيل وزن إكسبرس كتطبيق للحصول على تجربة أفضل",
  "Manage customers and their information": "إدارة العملاء ومعلوماتهم",
  "Delete Customer": "حذف العميل",
  "Customer Code": "رمز العميل",
  "Secondary Phone": "هاتف ثانوي",
  "Country": "الدولة",
  "Total Spent": "إجمالي الإنفاق",
  "Last Activity": "آخر نشاط",
  "Package History": "سجل الطرود",
  "Financial Summary": "ملخص مالي",
  "Tags": "الوسوم",
  "Blocked": "محظور",
  "Search customers...": "البحث عن عملاء...",
  "Filter by Status": "تصفية حسب الحالة",
  "Filter by City": "تصفية حسب المدينة",
  "Export Customers": "تصدير العملاء",
  "Import Customers": "استيراد العملاء",
  "Customer created": "تم إنشاء العميل",
  "Customer updated": "تم تحديث العميل",
  "Customer deleted": "تم حذف العميل",
  "Are you sure you want to delete this customer?": "هل أنت متأكد من حذف هذا العميل؟",
  "No customers": "لا يوجد عملاء",
  "Add your first customer": "أضف أول عميل",
  "Total Credit": "إجمالي الائتمان",
  "Registration Date": "تاريخ التسجيل",
  "Source": "المصدر",
  "Referred By": "أحيل بواسطة",
  "Discount Percent": "نسبة الخصم",
  "Price per Kg": "السعر لكل كغ",
  "Use Default Pricing": "استخدام التسعير الافتراضي",
  "Send Message": "إرسال رسالة",
  "View Packages": "عرض الطرود",
  "View Payments": "عرض المدفوعات",
  "View Invoices": "عرض الفواتير",
  "Generate Invoice": "إنشاء فاتورة",
  "Manage full package orders": "إدارة طلبات الطرد الكامل",
  "Full Package Dashboard": "لوحة الطرد الكامل",
  "Orders": "الطلبات",
  "Delete Order": "حذف الطلب",
  "Actual Delivery": "التوصيل الفعلي",
  "Color": "اللون",
  "Internal Notes": "ملاحظات داخلية",
  "Customer Notes": "ملاحظات العميل",
  "Avg Order Value": "متوسط قيمة الطلب",
  "Completed Orders": "الطلبات المكتملة",
  "Search orders...": "البحث في الطلبات...",
  "Filter by Supplier": "تصفية حسب المورد",
  "Filter by Customer": "تصفية حسب العميل",
  "Order created": "تم إنشاء الطلب",
  "Order updated": "تم تحديث الطلب",
  "Order deleted": "تم حذف الطلب",
  "Are you sure you want to delete this order?": "هل أنت متأكد من حذف هذا الطلب؟",
  "No orders": "لا توجد طلبات",
  "Add your first order": "أضف أول طلب",
  "Order Details": "تفاصيل الطلب",
  "Timeline": "الجدول الزمني",
  "Status History": "سجل الحالة",
  "Update Status": "تحديث الحالة",
  "Add Tracking": "إضافة تتبع",
  "View Product": "عرض المنتج",
  "Copy Link": "نسخ الرابط",
  "Open in New Tab": "فتح في علامة تبويب جديدة",
  "Supplier Report": "تقرير المورد",
  "Profit Report": "تقرير الأرباح",
  "1688": "1688",
  "Manage suppliers and their information": "إدارة الموردين ومعلوماتهم",
  "Delete Supplier": "حذف المورد",
  "Supplier Code": "رمز المورد",
  "Phone Number": "رقم الهاتف",
  "WeChat": "WeChat",
  "WhatsApp": "WhatsApp",
  "Avg Delivery Time": "متوسط وقت التوصيل",
  "Success Rate": "نسبة النجاح",
  "Search suppliers...": "البحث عن موردين...",
  "Filter by Platform": "تصفية حسب المنصة",
  "Filter by Rating": "تصفية حسب التقييم",
  "Supplier created": "تم إنشاء المورد",
  "Supplier updated": "تم تحديث المورد",
  "Are you sure you want to delete this supplier?": "هل أنت متأكد من حذف هذا المورد؟",
  "Add your first supplier": "أضف أول مورد",
  "Supplier Details": "تفاصيل المورد",
  "Order History": "سجل الطلبات",
  "Performance": "الأداء",
  "Taobao": "تاوباو",
  "Alibaba": "علي بابا",
  "Pinduoduo": "بيندودو",
  "0-3 days": "0-3 أيام",
  "Normal waiting": "انتظار عادي",
  "No alerts": "لا توجد تنبيهات",
  "All orders have tracking numbers": "جميع الطلبات لديها أرقام تتبع",
  "Manage all packages": "إدارة جميع الطرود",
  "Package Dashboard": "لوحة الطرود",
  "All Packages": "جميع الطرود",
  "Bulk Register": "تسجيل جماعي",
  "Edit Package": "تعديل الطرد",
  "Delete Package": "حذف الطرد",
  "Actual Weight": "الوزن الفعلي",
  "Volumetric Weight": "الوزن الحجمي",
  "Chargeable Weight": "الوزن المحاسب",
  "In Warehouse": "في المستودع",
  "Lost": "مفقود",
  "Damaged": "تالف",
  "Total Price": "السعر الإجمالي",
  "Partially Paid": "مدفوع جزئياً",
  "Arrival Date": "تاريخ الوصول",
  "Delivery Date": "تاريخ التوصيل",
  "Search packages...": "البحث في الطرود...",
  "Filter by Batch": "تصفية حسب الدفعة",
  "Filter by Shipping Type": "تصفية حسب نوع الشحن",
  "Package registered": "تم تسجيل الطرد",
  "Package updated": "تم تحديث الطرد",
  "Package deleted": "تم حذف الطرد",
  "Are you sure you want to delete this package?": "هل أنت متأكد من حذف هذا الطرد؟",
  "No packages": "لا توجد طرود",
  "Register your first package": "سجل أول طرد",
  "Package Details": "تفاصيل الطرد",
  "Add to Batch": "إضافة للدفعة",
  "Remove from Batch": "إزالة من الدفعة",
  "Mark as Delivered": "تحديد كمسلم",
  "Mark as Paid": "تحديد كمدفوع",
  "Total Weight": "الوزن الإجمالي",
  "Total Value": "القيمة الإجمالية",
  "Avg Weight": "متوسط الوزن",
  "Scan to register": "امسح للتسجيل",
  "Enter tracking number": "أدخل رقم التتبع",
  "Scan another": "مسح آخر",
  "Continuous Mode": "وضع مستمر",
  "Single Mode": "وضع فردي",
  "Bulk Upload": "رفع جماعي",
  "Download Template": "تنزيل القالب",
  "Upload File": "رفع ملف",
  "Import Packages": "استيراد الطرود",
  "Successfully imported": "تم الاستيراد بنجاح",
  "Failed to import": "فشل الاستيراد",
  "Duplicate tracking": "رقم تتبع مكرر",
  "Invalid data": "بيانات غير صالحة",
  "Manage shipping batches": "إدارة دفعات الشحن",
  "Edit Batch": "تعديل الدفعة",
  "Delete Batch": "حذف الدفعة",
  "Batch Name": "اسم الدفعة",
  "Expected Arrival": "الوصول المتوقع",
  "Actual Arrival": "الوصول الفعلي",
  "Preparing": "قيد التحضير",
  "Departed": "غادر",
  "Origin": "المنشأ",
  "Destination": "الوجهة",
  "Search batches...": "البحث في الدفعات...",
  "Filter by Carrier": "تصفية حسب الناقل",
  "Batch created": "تم إنشاء الدفعة",
  "Batch updated": "تم تحديث الدفعة",
  "Batch deleted": "تم حذف الدفعة",
  "Are you sure you want to delete this batch?": "هل أنت متأكد من حذف هذه الدفعة؟",
  "Create your first batch": "أنشئ أول دفعة",
  "Batch Details": "تفاصيل الدفعة",
  "Add Packages": "إضافة طرود",
  "Remove Packages": "إزالة طرود",
  "Mark as Departed": "تحديد كمغادر",
  "Mark as Arrived": "تحديد كواصل",
  "Print Manifest": "طباعة البيان",
  "Export Batch": "تصدير الدفعة",
  "Shipping Cost": "تكلفة الشحن",
  "Scan packages": "مسح الطرود",
  "Scan Reports": "تقارير المسح",
  "Scan Package": "مسح الطرد",
  "Scan Barcode": "مسح الباركود",
  "Scan QR Code": "مسح رمز QR",
  "Last Scanned": "آخر مسح",
  "Scan History": "سجل المسح",
  "Total Scans": "إجمالي المسح",
  "Successful Scans": "مسح ناجح",
  "Failed Scans": "مسح فاشل",
  "Scan Rate": "نسبة المسح",
  "Avg Scan Time": "متوسط وقت المسح",
  "Scan Action": "إجراء المسح",
  "Package found": "تم العثور على الطرد",
  "Already scanned": "تم مسحه مسبقاً",
  "Scan successful": "المسح ناجح",
  "Scan failed": "فشل المسح",
  "Invalid barcode": "باركود غير صالح",
  "Select Warehouse": "اختر المستودع",
  "Select Action": "اختر الإجراء",
  "Sound Enabled": "الصوت مفعل",
  "Sound Disabled": "الصوت معطل",
  "Vibration Enabled": "الاهتزاز مفعل",
  "Vibration Disabled": "الاهتزاز معطل",
  "Manage customer finances": "إدارة مالية العملاء",
  "Finance Management": "إدارة المالية",
  "Ledger": "الدفتر",
  "Transactions": "المعاملات",
  "Debt": "دين",
  "Credit": "ائتمان",
  "Cheque": "شيك",
  "Online": "عبر الإنترنت",
  "Payment Date": "تاريخ الدفع",
  "Payment Amount": "مبلغ الدفع",
  "Payment Reference": "مرجع الدفع",
  "Payment Notes": "ملاحظات الدفع",
  "New Payment": "دفعة جديدة",
  "Edit Payment": "تعديل الدفعة",
  "Delete Payment": "حذف الدفعة",
  "Payment recorded": "تم تسجيل الدفع",
  "Payment updated": "تم تحديث الدفع",
  "Payment deleted": "تم حذف الدفع",
  "Are you sure you want to delete this payment?": "هل أنت متأكد من حذف هذه الدفعة؟",
  "No payments": "لا توجد مدفوعات",
  "Search payments...": "البحث في المدفوعات...",
  "Filter by Method": "تصفية حسب الطريقة",
  "Filter by Date": "تصفية حسب التاريخ",
  "New Invoice": "فاتورة جديدة",
  "Edit Invoice": "تعديل الفاتورة",
  "Delete Invoice": "حذف الفاتورة",
  "Invoice Number": "رقم الفاتورة",
  "Invoice Date": "تاريخ الفاتورة",
  "Due Date": "تاريخ الاستحقاق",
  "Invoice Amount": "مبلغ الفاتورة",
  "Invoice Status": "حالة الفاتورة",
  "Draft": "مسودة",
  "Invoice created": "تم إنشاء الفاتورة",
  "Invoice updated": "تم تحديث الفاتورة",
  "Invoice deleted": "تم حذف الفاتورة",
  "No invoices": "لا توجد فواتير",
  "Search invoices...": "البحث في الفواتير...",
  "Print Invoice": "طباعة الفاتورة",
  "Send Invoice": "إرسال الفاتورة",
  "Download Invoice": "تنزيل الفاتورة",
  "Overdue Amount": "المبلغ المتأخر",
  "View Statement": "عرض كشف الحساب",
  "Track revenue, expenses, profit and loss": "تتبع الإيرادات والمصروفات والأرباح والخسائر",
  "Profit/Loss": "الأرباح/الخسائر",
  "Charts": "المخططات",
  "Revenue by Source": "الإيرادات حسب المصدر",
  "Air Batch Profit": "ربح الشحن الجوي",
  "Irregular Air Batch": "دفعة جوية غير عادية",
  "Sea Batch Profit": "ربح الشحن البحري",
  "Sea Shipping": "الشحن البحري",
  "Commission Income": "دخل العمولة",
  "Purchase Price": "سعر الشراء",
  "Total Commission": "إجمالي العمولة",
  "Activity Stats": "إحصائيات النشاط",
  "Full Packages Sold": "الطرود الكاملة المباعة",
  "Commission Orders": "طلبات العمولة",
  "Services Completed": "الخدمات المكتملة",
  "Batch Profit Breakdown": "تفصيل أرباح الدفعات",
  "Net profit for all batch types": "صافي الربح لجميع أنواع الدفعات",
  "Total Batch Profit": "إجمالي أرباح الدفعات",
  "By Service Type": "حسب نوع الخدمة",
  "View All": "عرض الكل",
  "Expenses by Category": "المصروفات حسب الفئة",
  "Expense Distribution": "توزيع المصروفات",
  "No expenses recorded": "لا توجد مصروفات مسجلة",
  "No data available": "لا توجد بيانات",
  "Revenue Comparison by Source": "مقارنة الإيرادات حسب المصدر",
  "Commission": "عمولة",
  "Last 6 Months": "آخر 6 أشهر",
  "Business reports": "تقارير الأعمال",
  "Yearly Report": "تقرير سنوي",
  "Customer Pricing Report": "تقرير أسعار العملاء",
  "Batch Financial Report": "تقرير مالي للدفعات",
  "Select Date Range": "اختر نطاق التاريخ",
  "Generate Report": "إنشاء تقرير",
  "Export CSV": "تصدير CSV",
  "Print Report": "طباعة التقرير",
  "Share Report": "مشاركة التقرير",
  "Schedule Report": "جدولة التقرير",
  "New Customers": "عملاء جدد",
  "Top Products": "أفضل المنتجات",
  "Sales by Category": "المبيعات حسب الفئة",
  "Sales by Region": "المبيعات حسب المنطقة",
  "Sales Trend": "اتجاه المبيعات",
  "Comparison with Previous": "مقارنة مع السابق",
  "Growth": "نمو",
  "Decline": "انخفاض",
  "No Change": "بدون تغيير",
  "System Mode": "وضع النظام",
  "Email Notifications": "إشعارات البريد",
  "Push Notifications": "إشعارات الدفع",
  "SMS Notifications": "إشعارات SMS",
  "Two-Factor Auth": "المصادقة الثنائية",
  "Sessions": "الجلسات",
  "Invoice Template": "قالب الفاتورة",
  "Label Printing": "طباعة الملصقات",
  "Notification Settings": "إعدادات الإشعارات",
  "Roles": "الأدوار",
  "Permissions": "الصلاحيات",
  "Blog Management": "إدارة المدونة",
  "Company Info": "معلومات الشركة",
  "Company Name": "اسم الشركة",
  "Company Address": "عنوان الشركة",
  "Company Phone": "هاتف الشركة",
  "Company Email": "بريد الشركة",
  "Tax Number": "الرقم الضريبي",
  "Default Currency": "العملة الافتراضية",
  "Default Language": "اللغة الافتراضية",
  "Default Timezone": "المنطقة الزمنية الافتراضية",
  "Save Settings": "حفظ الإعدادات",
  "Reset to Default": "إعادة التعيين للافتراضي",
  "Manage blog and announcements": "إدارة المدونة والإعلانات",
  "Posts": "المنشورات",
  "Delete Post": "حذف المنشور",
  "Likes": "الإعجابات",
  "Comments": "التعليقات",
  "Search posts...": "البحث في المنشورات...",
  "Filter by Category": "تصفية حسب الفئة",
  "Post created": "تم إنشاء المنشور",
  "Post updated": "تم تحديث المنشور",
  "Post deleted": "تم حذف المنشور",
  "Are you sure you want to delete this post?": "هل أنت متأكد من حذف هذا المنشور؟",
  "No posts": "لا توجد منشورات",
  "Add your first post": "أضف أول منشور",
  "Publish": "نشر",
  "Unpublish": "إلغاء النشر",
  "Save Draft": "حفظ المسودة",
  "Customer Portal": "بوابة العميل",
  "Welcome": "مرحباً",
  "Welcome back": "مرحباً بعودتك",
  "No announcements": "لا توجد إعلانات",
  "Estimated Delivery": "التوصيل المتوقع",
  "Current Location": "الموقع الحالي",
  "Notification Preferences": "تفضيلات الإشعارات",
  "Quick Stats": "إحصائيات سريعة",
  "Login with Google": "تسجيل الدخول بـ Google",
  "Login with Facebook": "تسجيل الدخول بـ Facebook",
  "Don't have an account?": "ليس لديك حساب؟",
  "Already have an account?": "لديك حساب بالفعل؟",
  "Create Account": "إنشاء حساب",
  "Login to your account": "تسجيل الدخول لحسابك",
  "Enter your credentials": "أدخل بيانات الاعتماد",
  "Invalid email or password": "البريد أو كلمة المرور غير صالحة",
  "Account is locked": "الحساب مقفل",
  "Session expired": "انتهت الجلسة",
  "Login successful": "تم تسجيل الدخول بنجاح",
  "Logout successful": "تم تسجيل الخروج بنجاح",
  "Registration successful": "تم التسجيل بنجاح",
  "Password reset link sent": "تم إرسال رابط إعادة تعيين كلمة المرور",
  "Password changed": "تم تغيير كلمة المرور",
  "Copied successfully": "تم النسخ بنجاح",
  "Uploaded successfully": "تم الرفع بنجاح",
  "Downloaded successfully": "تم التنزيل بنجاح",
  "Sent successfully": "تم الإرسال بنجاح",
  "Are you sure you want to cancel?": "هل أنت متأكد من الإلغاء؟",
  "Are you sure you want to save?": "هل أنت متأكد من الحفظ؟",
  "Are you sure you want to logout?": "هل أنت متأكد من تسجيل الخروج؟",
  "Operation completed": "تمت العملية",
  "Downloading...": "جاري التنزيل...",
  "No changes": "لا توجد تغييرات",
  "You have unsaved changes": "لديك تغييرات غير محفوظة",
  "Discard changes?": "تجاهل التغييرات؟",
  "Keep editing": "متابعة التعديل",
  "Leave without saving": "المغادرة دون حفظ",
  "Welcome to Wazn Express": "مرحباً بك في وزن إكسبرس",
  "Good morning": "صباح الخير",
  "Good afternoon": "مساء الخير",
  "Good evening": "مساء الخير",
  "Good night": "ليلة سعيدة",
  "First": "الأول",
  "Last": "الأخير",
  "Search...": "بحث...",
  "Sort": "ترتيب",
  "Columns": "الأعمدة",
  "Show Columns": "إظهار الأعمدة",
  "Hide Columns": "إخفاء الأعمدة",
  "Reset Filters": "إعادة تعيين التصفيات",
  "Clear Search": "مسح البحث",
  "Select an option": "اختر خياراً",
  "Select date": "اختر التاريخ",
  "Select time": "اختر الوقت",
  "Select file": "اختر ملف",
  "Drag and drop": "اسحب وأفلت",
  "Browse": "تصفح",
  "Upload image": "رفع صورة",
  "Upload file": "رفع ملف",
  "Remove file": "حذف الملف",
  "Remove": "إزالة",
  "Enter value": "أدخل القيمة",
  "Enter text": "أدخل النص",
  "Enter number": "أدخل الرقم",
  "Enter email": "أدخل البريد",
  "Enter phone number": "أدخل رقم الهاتف",
  "Enter password": "أدخل كلمة المرور",
  "Enter address": "أدخل العنوان",
  "Enter notes": "أدخل الملاحظات",
  "characters": "أحرف",
  "Just now": "الآن",
  "minutes ago": "دقائق مضت",
  "hours ago": "ساعات مضت",
  "days ago": "أيام مضت",
  "weeks ago": "أسابيع مضت",
  "months ago": "أشهر مضت",
  "years ago": "سنوات مضت",
  "in minutes": "في دقائق",
  "in hours": "في ساعات",
  "in days": "في أيام",
  "in weeks": "في أسابيع",
  "in months": "في أشهر",
  "in years": "في سنوات",
  "Next week": "الأسبوع القادم",
  "Next month": "الشهر القادم",
  "Next year": "السنة القادمة",
  "On Hold": "معلق",
  "Archived": "مؤرشف",
  "Closed": "مغلق",
  "Resolved": "تم الحل",
  "Unresolved": "لم يتم الحل",
  "kg": "كغ",
  "g": "غرام",
  "lb": "رطل",
  "oz": "أونصة",
  "cm": "سم",
  "m": "متر",
  "inch": "بوصة",
  "ft": "قدم",
  "cbm": "متر مكعب",
  "box": "صندوق",
  "carton": "كرتون",
  "pallet": "منصة",
  "container": "حاوية",
  "US Dollar": "دولار أمريكي",
  "Iraqi Dinar": "دينار عراقي",
  "Chinese Yuan": "يوان صيني",
  "Euro": "يورو",
  "British Pound": "جنيه إسترليني",
  "UAE Dirham": "درهم إماراتي",
  "Turkish Lira": "ليرة تركية",
  "Are you sure you want to delete this goal?": "هل أنت متأكد من حذف هذا الهدف؟",
  "Add Account": "إضافة حساب",
  "Add a new account for financial management": "إضافة حساب جديد للإدارة المالية",
  "Account added successfully": "تمت إضافة الحساب بنجاح",
  "Enter account name": "أدخل اسم الحساب",
  "Account Type": "نوع الحساب",
  "Enter bank name": "أدخل اسم البنك",
  "Initial Balance": "الرصيد الأولي",
  "Account description": "وصف الحساب",
  "Transaction History": "سجل المعاملات",
  "Select Account": "اختر الحساب",
  "Select destination account": "اختر حساب الوجهة",
  "No transactions found": "لم يتم العثور على معاملات",
  "Record Transaction": "تسجيل معاملة",
  "Transaction recorded successfully": "تم تسجيل المعاملة بنجاح",
  "Transaction Type": "نوع المعاملة",
  "Transaction Description": "وصف المعاملة",
  "Transaction description": "وصف المعاملة",
  "Receipt Number": "رقم الإيصال",
  "Transfer Out": "تحويل صادر",
  "Transfer completed successfully": "تم إتمام التحويل بنجاح",
  "Search transactions...": "البحث في المعاملات...",
  "Expense Alert System": "نظام تنبيه المصروفات",
  "Automatic notifications when expenses exceed configured thresholds": "إشعارات تلقائية عند تجاوز المصروفات للحدود المحددة",
  "New Alert": "تنبيه جديد",
  "Edit Alert": "تعديل التنبيه",
  "Set a threshold for expenses and receive notifications when exceeded": "حدد حداً للمصروفات واستلم إشعاراً عند التجاوز",
  "Total Alerts": "إجمالي التنبيهات",
  "Times Triggered": "مرات التفعيل",
  "Trigger History": "سجل التفعيل",
  "No alerts configured": "لا توجد تنبيهات محددة",
  "Create a new alert to track your expenses": "أنشئ تنبيهاً جديداً لتتبع مصروفاتك",
  "Create your first alert": "أنشئ أول تنبيه",
  "No triggers yet": "لا يوجد تفعيل بعد",
  "When expenses exceed thresholds, triggers will be logged here": "عند تجاوز المصروفات للحدود، سيتم تسجيل التفعيل هنا",
  "Threshold": "الحد",
  "Threshold Amount": "مبلغ الحد",
  "Alert Type": "نوع التنبيه",
  "Total daily expenses": "إجمالي المصروفات اليومية",
  "Total weekly expenses": "إجمالي المصروفات الأسبوعية",
  "Total monthly expenses": "إجمالي المصروفات الشهرية",
  "Per Transaction": "لكل معاملة",
  "Each individual expense": "كل مصروف على حدة",
  "Alert triggers if any single expense exceeds this amount": "يُفعل التنبيه إذا تجاوز أي مصروف فردي هذا المبلغ",
  "Alert triggers if total expenses in this period exceed this amount": "يُفعل التنبيه إذا تجاوزت المصروفات الإجمالية في هذه الفترة هذا المبلغ",
  "Expense Category": "فئة المصروف",
  "Notification Method": "طريقة الإشعار",
  "System Notification": "إشعار النظام",
  "Both": "كلاهما",
  "Add a note (optional)...": "أضف ملاحظة (اختياري)...",
  "Delete Alert": "حذف التنبيه",
  "Are you sure you want to delete this alert? This action cannot be undone.": "هل أنت متأكد من حذف هذا التنبيه؟ لا يمكن التراجع عن هذا الإجراء.",
  "Alert created successfully": "تم إنشاء التنبيه بنجاح",
  "Error creating alert": "خطأ في إنشاء التنبيه",
  "Alert updated successfully": "تم تحديث التنبيه بنجاح",
  "Error updating alert": "خطأ في تحديث التنبيه",
  "Alert deleted successfully": "تم حذف التنبيه بنجاح",
  "Error deleting alert": "خطأ في حذف التنبيه",
  "Please specify a threshold amount": "يرجى تحديد مبلغ الحد",
  "Expense Count": "عدد المصروفات",
  "And": "و",
  "VIP": "VIP",
  "S, M, L, XL...": "S, M, L, XL...",
  "CBM": "CBM",
};

// ============================================================
// MAIN LOGIC
// ============================================================

// Read files
const ku = JSON.parse(readFileSync(resolve(LOCALES_DIR, 'ku.json'), 'utf8'));
const en = JSON.parse(readFileSync(resolve(LOCALES_DIR, 'en.json'), 'utf8'));
const ar = JSON.parse(readFileSync(resolve(LOCALES_DIR, 'ar.json'), 'utf8'));
const zh = JSON.parse(readFileSync(resolve(LOCALES_DIR, 'zh.json'), 'utf8'));

// Flatten all
const kuFlat = flatten(ku);
const enFlat = flatten(en);
const arFlat = flatten(ar);
const zhFlat = flatten(zh);

// Count remaining before
let zhRemainingBefore = 0;
let arRemainingBefore = 0;
let enRemainingBefore = 0;

for (const key of Object.keys(kuFlat)) {
  if (zhFlat[key] !== undefined && zhFlat[key] === kuFlat[key]) zhRemainingBefore++;
  if (arFlat[key] !== undefined && arFlat[key] === kuFlat[key]) arRemainingBefore++;
  if (enFlat[key] !== undefined && enFlat[key] === kuFlat[key]) enRemainingBefore++;
}

console.log('=== BEFORE Round 3 ===');
console.log(`zh.json remaining (Kurdish values): ${zhRemainingBefore}`);
console.log(`ar.json remaining (Kurdish values): ${arRemainingBefore}`);
console.log(`en.json remaining (Kurdish values): ${enRemainingBefore}`);
console.log('');

// Apply translations
let zhFixed = 0;
let arFixed = 0;
let enFixed = 0;

for (const key of Object.keys(kuFlat)) {
  const kuVal = kuFlat[key];
  const enVal = enFlat[key];
  
  // Skip if English is not available or is also Kurdish
  const enIsKurdish = enVal === undefined || enVal === kuVal || containsKurdish(enVal);
  
  // Fix zh.json
  if (zhFlat[key] !== undefined && zhFlat[key] === kuVal) {
    if (!enIsKurdish && enVal in enToZh) {
      zhFlat[key] = enToZh[enVal];
      zhFixed++;
    } else if (!enIsKurdish) {
      // Try to translate using partial matching for common patterns
      let translated = tryTranslateZh(enVal);
      if (translated) {
        zhFlat[key] = translated;
        zhFixed++;
      }
    }
  }
  
  // Fix ar.json
  if (arFlat[key] !== undefined && arFlat[key] === kuVal) {
    if (!enIsKurdish && enVal in enToAr) {
      arFlat[key] = enToAr[enVal];
      arFixed++;
    } else if (!enIsKurdish) {
      let translated = tryTranslateAr(enVal);
      if (translated) {
        arFlat[key] = translated;
        arFixed++;
      }
    }
  }
  
  // Fix en.json where still Kurdish (translate from Kurdish value patterns)
  if (enFlat[key] !== undefined && enFlat[key] === kuVal) {
    const enTranslation = tryTranslateKuToEn(kuVal);
    if (enTranslation) {
      enFlat[key] = enTranslation;
      enFixed++;
      // Now also try to translate zh and ar using the new English value
      if (zhFlat[key] !== undefined && zhFlat[key] === kuVal) {
        if (enTranslation in enToZh) {
          zhFlat[key] = enToZh[enTranslation];
          zhFixed++;
        } else {
          let zhTrans = tryTranslateZh(enTranslation);
          if (zhTrans) { zhFlat[key] = zhTrans; zhFixed++; }
        }
      }
      if (arFlat[key] !== undefined && arFlat[key] === kuVal) {
        if (enTranslation in enToAr) {
          arFlat[key] = enToAr[enTranslation];
          arFixed++;
        } else {
          let arTrans = tryTranslateAr(enTranslation);
          if (arTrans) { arFlat[key] = arTrans; arFixed++; }
        }
      }
    }
  }
}

// Kurdish → English dictionary for remaining en.json entries
function tryTranslateKuToEn(kuVal) {
  const kuToEnMap = {
    "ئاگادارکردنەوەی تراکینگ": "Tracking Alert",
    "جزدانی مۆبایل": "Mobile Wallet",
    "داواکاریەکانی فوڵ پاکەج": "Full Package Requests",
    "دڵنیایت لە سڕینەوەی ئەم ئامانجە؟": "Are you sure you want to delete this goal?",
    "پاکەت گەیشتە کۆگا": "Package arrived at warehouse",
    "نوێکردنەوەی ئۆتۆماتیکی": "Auto Refresh",
    "چوونەژوورەوەی کڕیار": "Customer Login",
    "ئامانجی دارایی": "Financial Goal",
    "ئاگاداری تراکینگ": "Tracking Alert",
    "داهاتی کڕیار": "Customer Income",
    "پێویستە ڕاستەوخۆ چارەسەر بکرێت": "Needs Immediate Attention",
    "پێویستە زوو چارەسەر بکرێت": "Needs Quick Resolution",
    "پێویستە سەرنج بدرێت": "Needs Attention",
  };
  return kuToEnMap[kuVal] || null;
}

// Try partial/pattern-based translation to Chinese
function tryTranslateZh(enVal) {
  if (!enVal || typeof enVal !== 'string') return null;
  
  // Exact match already checked - try common patterns
  const trimmed = enVal.trim();
  
  // Handle very short or single-word matches via the dictionary  
  if (enToZh[trimmed]) return enToZh[trimmed];
  
  return null;
}

// Try partial/pattern-based translation to Arabic
function tryTranslateAr(enVal) {
  if (!enVal || typeof enVal !== 'string') return null;
  
  const trimmed = enVal.trim();
  if (enToAr[trimmed]) return enToAr[trimmed];
  
  return null;
}

// Count remaining after
let zhRemainingAfter = 0;
let arRemainingAfter = 0;
let enRemainingAfter = 0;

for (const key of Object.keys(kuFlat)) {
  if (zhFlat[key] !== undefined && zhFlat[key] === kuFlat[key]) zhRemainingAfter++;
  if (arFlat[key] !== undefined && arFlat[key] === kuFlat[key]) arRemainingAfter++;
  if (enFlat[key] !== undefined && enFlat[key] === kuFlat[key]) enRemainingAfter++;
}

console.log('=== Round 3 Results ===');
console.log(`zh.json: fixed ${zhFixed} entries (${zhRemainingBefore} → ${zhRemainingAfter} remaining)`);
console.log(`ar.json: fixed ${arFixed} entries (${arRemainingBefore} → ${arRemainingAfter} remaining)`);
console.log(`en.json: fixed ${enFixed} entries (${enRemainingBefore} → ${enRemainingAfter} remaining)`);
console.log('');

// Write updated files
const zhResult = unflatten(zhFlat);
const arResult = unflatten(arFlat);
const enResult = unflatten(enFlat);

writeFileSync(resolve(LOCALES_DIR, 'zh.json'), JSON.stringify(zhResult, null, 2) + '\n', 'utf8');
writeFileSync(resolve(LOCALES_DIR, 'ar.json'), JSON.stringify(arResult, null, 2) + '\n', 'utf8');
writeFileSync(resolve(LOCALES_DIR, 'en.json'), JSON.stringify(enResult, null, 2) + '\n', 'utf8');

console.log('✅ Files written successfully!');

// Show some remaining entries for debugging
if (zhRemainingAfter > 0) {
  console.log(`\n--- Sample remaining zh.json Kurdish values (up to 20): ---`);
  let count = 0;
  for (const key of Object.keys(kuFlat)) {
    if (count >= 20) break;
    if (zhFlat[key] !== undefined && zhFlat[key] === kuFlat[key]) {
      const enVal = enFlat[key];
      console.log(`  ${key}: ku="${kuFlat[key]?.substring(0, 40)}" en="${enVal?.substring(0, 40)}"`);
      count++;
    }
  }
}

if (arRemainingAfter > 0) {
  console.log(`\n--- Sample remaining ar.json Kurdish values (up to 20): ---`);
  let count = 0;
  for (const key of Object.keys(kuFlat)) {
    if (count >= 20) break;
    if (arFlat[key] !== undefined && arFlat[key] === kuFlat[key]) {
      const enVal = enFlat[key];
      console.log(`  ${key}: ku="${kuFlat[key]?.substring(0, 40)}" en="${enVal?.substring(0, 40)}"`);
      count++;
    }
  }
}
